### ISSUE TITLE
Change Opts for FACEBOOK login for user_friends

### ISSUE THREAD

**Issue by LoveenDyall** [abacritt/angularx-social-login#100]
Hi, 
How do I set custom Opts for facebook login.

tried:

`	    provider: new FacebookLoginProvider('APIKEY', {scope: 'email,public_profile,user_friends', return_scopes: true})
`

but it's not showing when console logging social user returned. the permissions are requested however during login

**Comment by jaibatrik** [comment]
@bodinaren That sounds fine to me. Please submit PR if you have time 👍
