### ISSUE TITLE
Login with Facebook is not working in IE

### ISSUE THREAD

**Issue by davidfrias** [abacritt/angularx-social-login#105]
Hi!
It seems facebook login is not working in IE. It's also happening in demo:
https://abacritt.github.io/angularx-social-login/

The error:
![image](https://user-images.githubusercontent.com/7084805/41999717-d4695fba-7a34-11e8-8ca0-f9422a814adb.png)

**Comment by bodinaren** [comment]
Did you add the appropriate polyfills for your Angular app to run in IE11? See `src/polyfills.ts` of your app.
Ps. The demo page does not do this.
