### ISSUE TITLE
Multiple time call AuthService if open/close multiple time popup in angularx-social-login

### ISSUE THREAD

**Issue by harleenarora** [abacritt/angularx-social-login#106]
I am using angularx-social-login package for social login. Issue is:- If am open/close multiple time social login like google popup, so that time call angularx-social-login call multiple time. So user register so many times.

**Comment by bodinaren** [comment]
Are you per-chance registering to the observable on every click? You'll want to make sure you only subscribe once, otherwise the subscription will obviously get triggered multiple times as well.

**Comment by jaibatrik** [comment]
Kindly provide us with a small sample so that we can debug.
