### ISSUE TITLE
auth token refresh ?

### ISSUE THREAD

**Issue by dsuwirya** [abacritt/angularx-social-login#107]
Hi,

Google auth token, for example, expires in 1H. Is there any way to do a token refresh in order to get a new extended auth token?

Thanks.

**Comment by webcat12345** [comment]
@jaibatrik according to the google doc, i should send `prompt: consent` but it doesn't work....

**Comment by webcat12345** [comment]
https://github.com/google/google-api-javascript-client/issues/383

**Comment by jaibatrik** [comment]
PRs are welcome. Thanks!

**Comment by dsuwirya** [comment]
This is probably the answer: [](https://developers.google.com/identity/sign-in/web/reference#googleuserreloadauthresponse) ?

**Comment by jaibatrik** [comment]
@radyash I myself will not work on this. If you need this feature, feel free to add this feature to the library. I'll be happy to merge the pull request and publish to npm.

**Comment by ShahoG** [comment]
This would certainly make sense to have, especially for use with AWS

**Comment by fabriziogelsi** [comment]
@webcat12345 could you do something to get the token refreshed?

**Comment by taujoey** [comment]
I would like to know this too.
Just started using this library, and based on the google api doc-s, i need a refresh token.
Does anybody have a solution for this?

**Comment by ostankin** [comment]
I have a pretty lame workaround, but it works.

First of all, I wrote a small helper called `JwtHelper` that makes use of [@auth0/angular-jwt](https://www.npmjs.com/package/@auth0/angular-jwt) to do the following:
* decode the JWT token
* extract its `exp` field
* tell if it is about to expire

```ts
import { JwtHelperService } from '@auth0/angular-jwt';

export class JwtHelper {
  static jwtHelperService = new JwtHelperService();

  static decode(jwtToken: string) {
    return this.jwtHelperService.decodeToken(jwtToken);
  }

  static expiresInLessThan(jwtToken: string, milliseconds: number): boolean {
    const decodedJwtToken = this.jwtHelperService.decodeToken(jwtToken);
    // in JS timestamps are in milliseconds, while UNIX timestamps used in JWT tokens are in seconds
    const tokenExpiresAt = new Date(decodedJwtToken.exp * 1000);
    const now = new Date();
    return (tokenExpiresAt.getTime() - now.getTime()) < milliseconds;
  }
}
```
Then, before sending the token to backend, I check if it is about to expire (or has already expired), and if yes, then I explicitly invoke `signIn()` again:
```ts
async sendToBackend() {
    const needRefresh = JwtHelper.expiresInLessThan(this.authService.user.idToken, 5 * 60 * 1000); // 5 minutes
    if (needRefresh) {
      await this.authService.signIn(this.providerId);
    }
   // Create and send `XMLHttpRequest`
}
```

Since earlier we subscribed to `this.authService.authState`, we get a new `SocialUser` object, with a new JWT token in it.

Two caveats here:
1. Calling `signIn()` fires a popup window that appears for a fraction of a second and then disappears. This may be pretty annoying for the user.
1. Since browsers tend to block unsolicited popups, make sure to call `sendToBackend()` **only** on some user action (mouse click or a keypress), otherwise the popup will be blocked and `authService` will throw an exception:
```
ERROR: Uncaught (in promise): User cancelled login or did not fully authorize.
```

**Comment by carbon-wpa** [comment]
> PRs are welcome. Thanks!

I have just created a PR for refreshing google auth token, please check it once you have some free time 🔢

**Comment by mvoorberg** [comment]
I saw the PR but it still requires manually "refreshing" the access_token.  Given that the Google's platform.js (GAPI) is self refreshing and puts a "gapi"  instance into  into the global space, you can access it directly at any time for the current access_token.

In the service you use for accessing login protected resources, add the following bits to get the currently valid access token.
```typescript
// more imports above this line...
import { SocialAuthService } from 'angularx-social-login';

declare var gapi;  // let typescript tolerate the gapi variable declared in platform.js
```

Then, in the same service class after the constructor... Where `this.authService` is an instance of `SocialAuthService`.

```typescript
  getBearerHeaders(options?: any) {
    return this.authService.authState.pipe(
      take(1),
      map((currentUser) => {
        if (currentUser) {
          // ***********************************************
          const currentUserAuthToken = currentUser.authToken;

          // Use the latest access token direct from the gapi.
          const gapiAuthToken = gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse().access_token;

          if (gapiAuthToken !== currentUserAuthToken) {
            console.log(`GAPI token mismatch!`, gapiAuthToken, currentUserAuthToken);
          } else {
            console.log(`GAPI token:`, gapiAuthToken);
          }
          // ***********************************************
          return Object.assign(
            {},
            {
              headers: { authorization: `Bearer ${gapiAuthToken}` },
            },
            options
          );
        }
        return options;
      })
    );
  }
```
The above code works without this PR and doesn't require any additional intervention to ensure the token is current.

**Comment by jaibatrik** [comment]
Hi, thanks for the info!

This probably means when someone wants the token, they should just call the `getLoginStatus` method (without the newly introduced parameter) that in turn calls `gapi.auth2.currentUser.get().getAuthResponse(true)`. Is that correct?

**Comment by mvoorberg** [comment]
Yes, I believe that's correct.

**Comment by jaibatrik** [comment]
I think we can keep the `refreshToken` method exposed for the sake of verbosity. I think we can close this issue as well, now that there is a solution.
