### ISSUE TITLE
[Feature] Be able to use different versions of Facebook SDK

### ISSUE THREAD

**Issue by rafa-as** [abacritt/angularx-social-login#109]
Hi,

It's simple, just add the possibility to set some other version of Facebook SDK.

If you want I can do the PR.

**Comment by bodinaren** [comment]
Couldn't different versions affect how the logic of the provider need to work? I feel like it's probably better to just update to the latest version (or at least latest of the 2.x releases to start with)? Is there a compelling reason to be able to choose which version to use?

**Comment by rafa-as** [comment]
@bodinaren Thanks for your quick response! Maybe a major change can affect, but a minor not. I checked the last changelogs of the Facebook Graph login section and all the changes are fields and permissions, not on the SDK functions.

Anyway I think that if some API change breaks the library, it's better to know and allow the people to test it and report bugs/feature to upgrade and support the new API versions.

I'm going to do a PR to allow the version customization

**Comment by jaibatrik** [comment]
Thanks @rafa-as and @bodinaren. I merged it as I thought this is just an add-on and people will only need this if the default option is not working for them.
