### ISSUE TITLE
login popup was closed by user Error.

### ISSUE THREAD

**Issue by jokerrider007** [abacritt/angularx-social-login#111]
I use this angularx-social-login in my angular 6 project. when i click google login and closed it. 
my console show some error. 

![capture1](https://user-images.githubusercontent.com/12674933/42563340-3b5fd41c-8528-11e8-91de-9fac55b35e8d.PNG)

**Comment by bodinaren** [comment]
Sounds like the same issue as #112, but for Google. PR's on this are welcome.

**Comment by BruneXX** [comment]
Hi guys, I think this is still an issue, please take a look at this:

```
core.js:1673 ERROR Error: Uncaught (in promise): User cancelled login or did not fully authorize.
    at resolvePromise (zone.js:814)
    at zone.js:724
    at angularx-social-login.es5.js:3903
```

any solution for this? I'm running **v1.2.5** of angularx-social-login under angular **v7.1.3**

**Comment by edwinnjorogekiburu** [comment]
It's definitely an issue, I'm running v1.2.7 and ran into the same issue

![image](https://user-images.githubusercontent.com/1876593/58248100-e3e23d80-7d63-11e9-9791-8e3007bd832f.png)

Angular v7.2.15

**Comment by jaibatrik** [comment]
When does the error appear?

**Comment by BruneXX** [comment]
Hi @jaibatrik The error appears when you close the login pop-up for Google, Facebook, etc.

**Comment by skylove123** [comment]
@BruneXX  Do you find out the solution for this issue ?

**Comment by BruneXX** [comment]
Hi @skylove123 not really, In fact there’ a a lot of time I’ve reviewed this, I think we’ll need to fix this on our own.
