### ISSUE TITLE
Facebook Login popup closed by user not handled

### ISSUE THREAD

**Issue by JuanCruzReines** [abacritt/angularx-social-login#112]
When user close facebook login popup, this event is not being handled and therefore the application can´t react to it.

According to Facebook SDK documentatión a proper usage of FB.Login should be:

```
FB.login(function(response) {
    if (response.authResponse) {
      //Correct login
    } else {
     //User cancelled login or did not fully authorize
    }
});
```

In the implementation of this library the else statemant is not present and therefore that scenario where the user closes the popup is not covered.

I suggest add the else statement and reject  the promise inside of it so it can be handled by the application.

**Comment by bodinaren** [comment]
PR's on this are welcome.

**Comment by jaibatrik** [comment]
Solved for FB via #114

**Comment by JuanCruzReines** [comment]
Hi.  I would like to know when this version will be updated to npm since i need to use it in a project. Thanks.

**Comment by jaibatrik** [comment]
I just released it to npm. Get v1.2.2.

**Comment by piyush-ampersand** [comment]
@bodinaren Hi I am facing the same issue with v1.2.6. Whenever I login using Fb and then log out from the application as well as from Fb and then again try to login using fb and now if I close the popup window without login into fb it does not go to the catch block instead it logs user using last credentials used for fb. Hope I am clear. Any idea why this is happening ? 
Please help !!

**Comment by bagnos** [comment]
Same Issue! The promise is not rejected when the user click the cancel button on facebook login popup. Any idea?

**Comment by lakshaygupta21** [comment]
There is a property known as auth_type, you need to set that to "reauthenticate" and everything will work.
Refer to this for more details: <a href="https://www.wellhow.online/Facebook%20login%20dialog%20is%20logging%20in%20even%20on%20closing%20the%20popup%20%7C%20Solved%20%7C%20Facebook%20Developers%20%7C%20React.js/607d7aa4ba8a9a3e6bd93fd3">
Facebook Login popup onClose | Solved
</a>

**Comment by ignisf0x** [comment]
With reauthenticate:
- LOGIN: Failed
- Exit Login Window: Success

Without reauthenticate
- LOGIN: Success
- Exit Login Window: Failed

Any Idea why using "reauthenticate" will throw undefined fields?  @lakshaygupta21

**Comment by lakshaygupta21** [comment]
Re-authentication enables your app to confirm a person's identity even if it was verified previously. Facebook Login lets your app ask a person to re-enter their Facebook password at any time. You can use this to prevent cases where a user leaves a device logged in or where a third party hijacks someone's session with your app.

This is what is the definition of "reauthenticate" by Facebook
[https://developers.facebook.com/docs/facebook-login/reauthentication/](url)
