### ISSUE TITLE
FB.api('/me?fields=name,email,picture,first_name,last_name') cause an issue

### ISSUE THREAD

**Issue by nicoprida** [abacritt/angularx-social-login#119]
Hi!
Facebook app added a new security parameter: **appsecret_proof**
More info: https://developers.facebook.com/docs/graph-api/securing-requests#appsecret_proof

If this security funcionality is active, the "me?" method fail because it requiere this new parameter to continue, this situation provoke that "me?" method execute with error and ID parameter don't set on SocialUser object.

The error is: "API calls from the server require an appsecret_proof argument"

![untitled](https://user-images.githubusercontent.com/13623898/43465460-c623b6c8-94b3-11e8-8a0b-a63c5699ccc0.png)

Its necessary create the SocialUser object outside the FB.api method to avoid this situation and fill it with the information later in case the method execute correctly

Thank you!

**Comment by nicoprida** [comment]
I propose this as solution
![untitled](https://user-images.githubusercontent.com/13623898/43466620-5478cb3c-94b6-11e8-9581-7c0236e7891a.png)

Let me know your thoughts

**Comment by jaibatrik** [comment]
According to the documentation, the `appsecret_proof` parameter is applicable for requests sent from a server; whereas, requests from this library are always sent from client. Why do you think we should consider this parameter?

**Comment by nicoprida** [comment]
I read the documentation again and it said this parameter can be used from both sides, anyway, I detected this issue when the client tried to execute the "me?" functionality from the API.

So, in this case, its failing from the client side. That is the reason because I want to move the ID property outside the method. Because, when the method fails, the socialUser don't get the ID

**Comment by jaibatrik** [comment]
I thought so because the documentation had statements like - 
> Calls from a server can be better secured by adding a parameter called `appsecret_proof`.

and

> You can prevent this by adding the `appsecret_proof` parameter to every API call from a server...

It'd be interesting to check this since you have encountered this from client side using the library. By any chance, is the sample where you encountered this accessible so that we can better understand the situation?

Thanks for reporting the issue!

**Comment by nicoprida** [comment]
Sorry, I don't understand your question, but you can check this allowing that security parameter in you facebook application and then try the "me?" funcionality.

You will see this error: "API calls from the server require an appsecret_proof argument" and the user object will be empty.

Let me know if that helps you with the sample

**Comment by jaibatrik** [comment]
Will reopen this if more reports come.
