### ISSUE TITLE
Not working after build

### ISSUE THREAD

**Issue by wrufeger** [abacritt/angularx-social-login#124]
Login works as expected in development mode using "ng serve", but after building not logging into google for example. No popup, no errors, no additional information I could give you, its just not working. Tried to build without aot and without build optimizer. Any help or suggestions would be appreciated.

**Comment by JayzeeHuang** [comment]
Did you try ng build --aot?

**Comment by wrufeger** [comment]
Sure I did, that was he first I tried.

**Comment by jaibatrik** [comment]
You have a sample of this for us to debug?

**Comment by jaibatrik** [comment]
Reopen with a reproducible sample. Closing for now.
