### ISSUE TITLE
General Login issue

### ISSUE THREAD

**Issue by BruneXX** [abacritt/angularx-social-login#127]
After follow all steps in the guide, when I'm trying to login with any of those posibilities (Google, Facebook, Linkedin) when I click on button it's doing nothing..

I've checked the function for GoogleProvider in my environment and it's working, I'm receiving even the data of the authService when I debug.

But,I'm not receiving any error on the console and the login pop-up is not appearing when I click on social login button, any ideas?

Will be really appreciated.

Thanks,

**Comment by jakecleary** [comment]
I'm getting a similar issue. It seems to fail when trying to get the login provider from the `providers` `Map` internally. I'm passing in the ID using the provided constant, but it's returning `undefined`.

When I click the button it just silently fails and nothing happens.

---

![image](https://user-images.githubusercontent.com/4572429/44992008-e7435800-af8d-11e8-883b-605303ebceb2.png)

---

![image](https://user-images.githubusercontent.com/4572429/44991953-b8c57d00-af8d-11e8-8dd7-7ab45d737e93.png)

---

![image](https://user-images.githubusercontent.com/4572429/44991882-7e5be000-af8d-11e8-954a-d77d55164ab1.png)

**Comment by jakecleary** [comment]
@BruneXX for the time being, downgrading to `1.1.9` fixed this issue for me.

**Comment by BruneXX** [comment]
Hi! @jakecleary I'll give a try and I'll let you know if that solve the issue, thanks a lot!

**Comment by BruneXX** [comment]
Hi @jakecleary Excellent! downgrading to 1.1.9 works like a charm! BTW what are you using to trace the provider workflow? thanks!

**Comment by MarceloRGomes** [comment]
I have same problem with Google... With 1.1.9 version I have issue with Google close popup...
The Linkedin not working too...
If anyone can fix it, I will really appreciate..

**Comment by BruneXX** [comment]
Hi @MarceloRGomes what issue with pop-up? downgrading to 1.1.9 work fine for me.

**Comment by MarceloRGomes** [comment]
Hi @BruneXX ,
I don´t know why, but angularx-social-login@1.2.3 is working now with Google auth.
But in this version the Linkedin always open modal to register user, even not clicking on button.

But at 1.1.9 the error was on Google "closing popup"... but I´m using 1.2.3 now...

**Comment by jaibatrik** [comment]
Anyone facing this issue still? Does anyone have a sample?

**Comment by LorenzoBatto** [comment]
> Anyone facing this issue still? Does anyone have a sample?

Yes, I still face this issue. Downgrading to 1.1.9 has worked for me as well.

But it's weird, because I have two projects, and in one of them the latest version is working fine while in the other I had to downgrade. Maybe there are collisions with other packages, I don't know.

**Comment by BruneXX** [comment]
Hi guys, I can confirm that with v1.2.5 it's working now, I can see the Google pop-up open, I haven't tried other providers like Facebook yet, but when I do that, I'll let you know the results.
Best!

**Comment by tettusud** [comment]
@BruneXX Still popup is not coming I am using angular 7

**Comment by BruneXX** [comment]
Hi @tettusud It's actually working for me with angular 7.1.3..

**Comment by BruneXX** [comment]
@tettusud Are you correctly generated the provider id for your domain?

**Comment by jaibatrik** [comment]
@BruneXX Has this been fixed or are we still seeing the issue?

**Comment by BruneXX** [comment]
Hi @jaibatrik it's working for me with angular 7.1.3 with the proper google client id, but it seems this is still an issue for other users like @tettusud

**Comment by maturecheese** [comment]
I had no popup appear for google login either. Here's what fixed it for me:
 
Google developer console -> credentials -> delete existing OAuth 2.0 client IDs
then
Create credentials  -> OAuth client ID -> web application
-add http://localhost:4200 to Authorized Javascript origins (or what you are using)
-update config with new client ID 

... wait 20 minutes (maybe not necessary?), and then it worked!

**Comment by bhatikuldeep** [comment]
> @BruneXX for the time being, downgrading to `1.1.9` fixed this issue for me.

works for me as well, thanks!

**Comment by Carvald** [comment]
what @maturecheese  suggested was what has worked for me 
(didn't have to wait the 20 minutes 👍 )

**Comment by jaibatrik** [comment]
Closing this as this seems mostly fixed with the newer version and with the suggestion from @maturecheese.

**Comment by kapilSoni101** [comment]
@BruneXX :sir i got below error in the console can you help me please?

**Error: Uncaught (in promise): Login providers not ready yet. Are there errors on your console?**
