### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by gultyaev** [abacritt/angularx-social-login#129]
How do I do a "redirect" to a backend API to save my user data?

**Comment by kodeine** [comment]
you would not do a "redirect", you would listen to the subscription and update call to the API once an event is received.

**Comment by gultyaev** [comment]
Well then. According to https://medium.com/@barryvdh/oauth-in-javascript-apps-with-angular-and-lumen-using-satellizer-and-laravel-socialite-bb05661c0d5c I need to send to an API the Authorization code. How do I get it if I get a user? I need to store user profile on backend

**Comment by gultyaev** [comment]
It looks like it's not that token I need because I've tried to pass it as is and it wasn't worked. I've tried to pass it as a {token: userData.authToken} also as {code: userData.authToken} and as JSON.stringify({code: userData.authToken}). Nothing is working and an error 400 bad response returns from facebook

**Comment by jaibatrik** [comment]
This is not an issue, rather a question. @kodeine has pointed to the right direction. Thanks!
