### ISSUE TITLE
Could any good soul implement Instagram?

### ISSUE THREAD

**Issue by MarceloRGomes** [abacritt/angularx-social-login#133]
Sorry open "issue" with suggestionm, but I really need Instagram login...

**Comment by MarceloRGomes** [comment]
Twitter can be good too! :)

**Comment by MarceloRGomes** [comment]
No one?

**Comment by jaibatrik** [comment]
Both Instagram and Twitter support only OAuth based authentication. They don't have client side libraries that would enable a client-only Angular application to use them.
