### ISSUE TITLE
Email is undefined

### ISSUE THREAD

**Issue by isaleem** [abacritt/angularx-social-login#134]
SocialUser object in authState.subscribe does not have email field populated, I have confirmed at the developer portal the email permissions are granted, any thoughts on what I am possibly missing?

**Comment by calcinai** [comment]
@isaleem are you sure that the SocialUser is actually populated?  The `BehavourSubject`'s initial value is `null`

**Comment by jaibatrik** [comment]
@isaleem Do you have a reproducible sample for this?

**Comment by jaibatrik** [comment]
@Brijeshlakkad Have you tried searching in Google / StackOverflow with this problem. Generally, this library is just a wrapper around FB's library and populate whatever email value FB is sending as response.

**Comment by marcellobarile** [comment]
@isaleem  @Brijeshlakkad it might be that Facebook doesn't expose the email address if the user set it to private in the privacy settings.
