### ISSUE TITLE
Support for Custom Parameters

### ISSUE THREAD

**Issue by lavikumargupta** [abacritt/angularx-social-login#135]
Hi, Is there any way to use custom parameters for a provider, e.g for google i need to pass accesstype='offine' in google auth request.

**Comment by jaibatrik** [comment]
I think you can pass it in the `opt` parameter for `GoogleLoginProvider` constructor. Check https://github.com/abacritt/angularx-social-login/blob/master/src/lib/src/providers/google-login-provider.ts
