### ISSUE TITLE
Google not working in production

### ISSUE THREAD

**Issue by faridhajnal** [abacritt/angularx-social-login#136]
Hi,

I've implemented both Facebook and Login on my Angular 6 application. They are both working properly while on localhost. As I published my application (using Now) I can go throughout the Facebook login flow, however when trying Google, the application does nothing. 
The external window (from Google) does not get triggered and I get no errors on the browser console. It simply does not do anything (at least anything that can be seen)

Any idea why this could be happening? Any help would be much much appreciated.

Thanks

**Comment by faridhajnal** [comment]
if anyone runs into this, remember to properly configure your google credentials here

**Comment by trippygif** [comment]
I am having the same issue, strangely it works on some of the client's machines but not on everyone's. Make sure your Chrome (or whatever browser you are using) allows popups from that domain as well!

**Comment by prince2398** [comment]
I'm having a same problem.
checked Allowed JS Origins and Authorized Redirect URIs 
Allowed Popups in chrome browser.
Still having the same issue . by clicking on google login button its calling the function associated with that but didn't login and don't even returns any error

**Comment by faridhajnal** [comment]
@prince2398 Is it working for you locally ?

**Comment by chrstphrrbn** [comment]
I have a lot of users running in to the same issue as @prince2398. It works for me personally though.

They seem to have chrome/android in common.

**Comment by ImATechnophile** [comment]
@chrstphrrbn Is it working for you in Chrome?
Except for Chrome, it runs in all the browser.

**Comment by Chiragpwar** [comment]
@ImATechnophile you are right its run all browser expect Crome.
in Crome not getting any response.. after run my project on firefox it was worked.
