### ISSUE TITLE
No logout Facebook 

### ISSUE THREAD

**Issue by davidoween** [abacritt/angularx-social-login#137]
I cant logout en Facebook. Why?
  I just call the method signout()

**Comment by agnaveen** [comment]
Even I am facing the same issue still, also facing it in live domain too, thought it comes like this in localhost, but same issue everywhere :(

**Comment by davidoween** [comment]
I still have a problem. If you find the solution please let me know

**Comment by TokkeDev** [comment]
I had the same problem and found two different causes. One was that I didn't run my page over HTTPS (which you need to do for full FB support) and the other was that I hadn't added the correct `Valid OAuth Redirect URIs` in the FB developer console. Hope it helps :)

**Comment by jaibatrik** [comment]
Try to check the JS console if you are getting any error. This might not be a problem with the library itself but with the configuration in the Facebook Developer site.

**Comment by bioman** [comment]
Also facing this problem, I found out that Safari is work correctly but not in Google Chrome.

**Comment by nelcab** [comment]
Have you check out this answer: [https://stackoverflow.com/questions/22331373/facebook-js-api-cant-logout](stackoverflow answer).
This could be the reason you can't logout.

**Comment by jaibatrik** [comment]
Closing this. Reopen if the suggestion from @nelcab did not work.
