### ISSUE TITLE
https://api.linkedin.com/v1/people/~:(undefined): 400 Error

### ISSUE THREAD

**Issue by agnaveen** [abacritt/angularx-social-login#139]
After signin with Linkedin getting the below errors in the console:
xdrpc.html?v=1.0.348-1429:1677 GET https://api.linkedin.com/v1/people/~:(undefined) 400

Any idea or help on how to resolve please ?

**Comment by Ahmed3laa** [comment]
I am having the same issue.

**Comment by Ahmed3laa** [comment]
A workaround for that:
open "node_modules/angularx-social-login/angularx-social-login.es5"
for line 9704:

 function () {
        var _this = this;
        return new Promise(function (resolve, reject) {
            _this.onReady().then(function () {
				var _this2=_this; //add this
                IN.User.authorize(function () {
                    IN.API.Raw("/people/~:(" + _this2.fields + ")").result(function (res) // and edit this

**Comment by shubhamagrawal280395** [comment]
Hi I faced same issue today but it is fixed by the solution of @Ahmed3laa , so when are you planning to update this

**Comment by ahsanalam314** [comment]
> Hi I faced same issue today but it is fixed by the solution of @Ahmed3laa , so when are you planning to update this

I'm facing the same issue. It will be glad if u tell me about the solution that was suggested by you from @Ahmed3laa.

Thank You.

**Comment by piyush-ampersand** [comment]
Hey has anyone found the solution for this issue ?

**Comment by piyush-ampersand** [comment]
@doughlass you can track the issue here #97. Summary is PR has been generated but still it needs to be reviewed and then publish on the npm  and that can be done by @jaibatrik only.

**Comment by UsmanMalik04** [comment]
@Ahmed3laa  this thing  is working fine on localhost but when i deployed to the server, i am getting the same issue. any suggestion

**Comment by jaibatrik** [comment]
Fixed and merged via #152. Pushed v1.2.6 to npm.
