### ISSUE TITLE
subscribing on authState fires constantly

### ISSUE THREAD

**Issue by Berno** [abacritt/angularx-social-login#141]
I'm facing with this issue in a login component where i have the standard login (user registered by standard site registration) and facebook login. I put the subscription in ngOnInit function    
```
ngOnInit() {
   this.authService.authState.subscribe( 
       (user) => { if (user) { // login on server } } 
   )
}
```
When the user click on fb login button I call 
```
this.authService.signIn(FacebookLoginProvider.PROVIDER_ID);
```
if I log the user in the subscription I see that the value is printed every time the component is created even if the user doesn't click on the button therefore the user is constantly logged since he has authorized the app on the first login. This makes impossibile to log out the user in a component where the login component is included. Is the expected behavior or I made a mistake?

**Comment by Bubimirac** [comment]
Any update on this, I am having exactly the same issue.

**Comment by Jindu0506** [comment]
Facing the same issue.

**Comment by mkh004059** [comment]
Facing same issue

**Comment by nicolasecolman** [comment]
You sould subscribe to the observable when the user clicks on the fb login button. 

`fbLogin() {
   this.authService.authState.subscribe( 
       (user) => { if (user) { // login on server } } 
   );
  this.authService.signIn(FacebookLoginProvider.PROVIDER_ID);
}`

**Comment by jaibatrik** [comment]
Appears to be intermittent. The issue is quite old. Reopen if you have a reproducible environment.
