### ISSUE TITLE
Request for updating documentation to SignIn with different authConfiguration than global authConfiguration.

### ISSUE THREAD

**Issue by Tilak1996** [abacritt/angularx-social-login#142]
I was trying to SignIn with **custom** `LoginOpt` as I wanted only **specific permissions** from facebook for a user. As I went down to **documentation** I did not find any way to set **custom** `LoginOpt`  .Hope documentation will be updated soon... Thanks.

**Comment by jaibatrik** [comment]
The login options accept the same parameters as the provider JS API documentation says. You need to check with specific provider documentation. Else, it'd be great if someone can send a PR.

**Comment by jaibatrik** [comment]
This has been added now under "Specifying custom scope" heading in the README.
