### ISSUE TITLE
Angularx-social-login errors (Peer Dependency Errors)

### ISSUE THREAD

**Issue by Tuskillz** [abacritt/angularx-social-login#146]
I got this errors while trying to install npm install --save angularx-social-login. Pls can you tell me what am not doing right and what to do in order to get the package install.

Below are the errors.

C:\Users\DELL\Desktop\FrontEnd>npm install --save angularx-social-login
npm WARN @angular/animations@6.1.3 requires a peer of @angular/core@6.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.2.0 requires a peer of @angular/common@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.2.0 requires a peer of @angular/core@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.2.0 requires a peer of @angular/forms@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-forms/file-upload@1.1.0 requires a peer of @angular/common@^6.0.7 but none is installed. You must install peer dependencies
yourself.
npm WARN @ng-forms/file-upload@1.1.0 requires a peer of @angular/compiler@^6.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-forms/file-upload@1.1.0 requires a peer of @angular/core@^6.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-forms/file-upload@1.1.0 requires a peer of @angular/forms@^6.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-forms/file-upload@1.1.0 requires a peer of @angular/http@^6.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-forms/file-upload@1.1.0 requires a peer of @angular/platform-browser@^6.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-forms/file-upload@1.1.0 requires a peer of @angular/platform-browser-dynamic@^6.0.7 but none is installed. You must install
peer dependencies yourself.
npm WARN @ng-forms/file-upload@1.1.0 requires a peer of @angular/router@^6.0.7 but none is installed. You must install peer dependencies
yourself.
npm WARN angular2-image-upload@1.0.0-rc.1 requires a peer of @angular/common@^2.4.9 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-image-upload@1.0.0-rc.1 requires a peer of @angular/core@^2.4.9 || ^4.0.0 but none is installed. You must install peer
dependencies yourself.
npm WARN angular2-image-upload@1.0.0-rc.1 requires a peer of @angular/http@^2.4.9 || ^4.0.0 but none is installed. You must install peer
dependencies yourself.
npm WARN angular2-image-upload@1.0.0-rc.1 requires a peer of rxjs@^5.0.0-rc.2 but none is installed. You must install peer dependencies yourself.
npm WARN ng-circle-progress@1.1.0 requires a peer of rxjs@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-snackbar@1.2.0-rc.2 requires a peer of @angular/common@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-snackbar@1.2.0-rc.2 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN patternfly-ng@4.5.1 requires a peer of typescript@^2.9.2 but none is installed. You must install peer dependencies yourself.
npm WARN patternfly-ng@4.5.1 requires a peer of rxjs@^6.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN angularx-social-login@1.2.5 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\DELL\Desktop\FrontEnd\node_modules\.staging\fsevents-300da7c0\node_modules\abbrev' -> 'C:\Users\DELL\Desktop\FrontEnd\node_modules\.staging\abbrev-edca6c5f'

npm ERR! code E404
npm ERR! 404 Not Found: flatmap-stream@0.1.2

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2018-11-28T21_08_59_644Z-debug.log

**Comment by jaibatrik** [comment]
Appears to be related to `flatmap-stream` package. Problem is not with this package. Try searching in Google. Also, you need to install Angular before installing this package.
