### ISSUE TITLE
LinkedIn Api call using access token returned by authState

### ISSUE THREAD

**Issue by prince2398** [abacritt/angularx-social-login#147]
Hey, 

How can I make calls using access token(in user) provided by authState function. When I am making http request to api from my Angular app it shows 'http://localhost:4200' has been blocked by CORS.

Thank you in advance.

**Comment by doughlass** [comment]
https://www.npmjs.com/package/angularx-social-login

**Comment by jaibatrik** [comment]
Closing as LinkedIn not supporting JS SDK any more. See #157.
