### ISSUE TITLE
I am getting this error can you please guide me how to fix this "Uncaught (in promise): TypeError: Cannot read property 'isAuthorized' of undefined"

### ISSUE THREAD

**Issue by ahmedanees** [abacritt/angularx-social-login#149]
core.js:12970 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'isAuthorized' of undefined
TypeError: Cannot read property 'isAuthorized' of undefined
    at eval (angularx-social-login.es5.js:9693)
I am trying to use it with angular 7

**Comment by achapman009** [comment]
This is happening to me as well. Were you able to find a solution?

**Comment by UsmanMalik04** [comment]
i am getting the same issue, any one find a solution ?

**Comment by jaibatrik** [comment]
Can anyone provide a sample for this?

**Comment by jaibatrik** [comment]
Looks like issue is related to `LinkedInLoginProvider`. May be the `setTimeout` value needs to be increased.

**Comment by developerant** [comment]
+1

**Comment by nilesh-sutar** [comment]
I'm also getting the same error 
![isauthorisederror](https://user-images.githubusercontent.com/37416096/51183652-e3d6ba80-18f7-11e9-8ef2-c0f0829a0171.png)

**Comment by razorphish** [comment]
This looks like a bug in the code as 'IsAuthorized' is being called when the IN.User object has not been instantiated or initialized yet.   An easy work-around would be check for object NULL or undefined..  

![image](https://user-images.githubusercontent.com/4053010/51542682-ac44a280-1e10-11e9-9390-4dd123e65701.png)

**Comment by jaibatrik** [comment]
Closing as LinkedIn is not supporting JS SDK any more. See #157.
