### ISSUE TITLE
LinkedIn getting authToken instead of accessToken

### ISSUE THREAD

**Issue by piyush-ampersand** [abacritt/angularx-social-login#153]
@jaibatrik  Hi I am need to get the accessToken from linked but it return authToken. 
Can you let me know why I am not getting accessToken??

**Comment by jaibatrik** [comment]
Hey, not sure how exactly the LinkedIn provider was implemented. As far as I remember, the Facebook provider has provision to retrieve both auth and access token. May be we need a similar solution for LinkedIn.

**Comment by jaibatrik** [comment]
LinkedIn not supporting JS SDK any more. Already reported at #157.
