### ISSUE TITLE
authState not returning on first load

### ISSUE THREAD

**Issue by Sonaryr** [abacritt/angularx-social-login#154]
I'm having an issue with using this package in a route guard.
On first load when a user is not logged in, the `authState` does not fire.

```
@Injectable({
  providedIn: 'root'
})
export class LoginGuard implements CanActivate {

  constructor(private authService: AuthService, private router: Router) {}

  canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): Observable<boolean> | Promise<boolean> | boolean {
    return this.authService.authState.pipe(
      map(user => user !== null),
      catchError(err => of(false)),
      tap((isLoggedIn) => {
        if(!isLoggedIn) {
          this.router.navigate(['/public']);
        }
      })
    );
  }
}
```

I'm guessing it's because the promise returned in `getLoginStatus()` in a provider (google in my case) is not resolved or rejected if `this.auth2.isSignedIn.get()` returns false.

Is this a deliberate use case? Or am I doing something wrong?

**Comment by jaibatrik** [comment]
I don't think that is the intention. In fact #85 was submitted and subsequently merged to address the route guard issues. I think you can submit a PR with the fix and get it reviewed and merged.

CC: @bodinaren @lianyi

**Comment by Sonaryr** [comment]
Created a PR that fixes this issue

**Comment by Womballs** [comment]
Could we merge this fix please ?

**Comment by Womballs** [comment]
Up @jaibatrik @bodinaren @lianyi
