### ISSUE TITLE
Login with linkedin is not working..

### ISSUE THREAD

**Issue by UsmanMalik04** [abacritt/angularx-social-login#157]
![lindd](https://user-images.githubusercontent.com/36415562/50976724-794a0700-1512-11e9-8187-a4b588ddd3fb.PNG)

**Comment by captainjackrana** [comment]
From now on, Linkedin SDK will stop working, as mentioned in their latest v2 migration document.

> SDKs: Our JavaScript and Mobile Software Development Kits (SDKs) will stop working. Developers will need to migrate to using OAuth 2.0 directly from their apps.  

https://engineering.linkedin.com/blog/2018/12/developer-program-updates

**Comment by jaibatrik** [comment]
Yeah, looks like it... Thanks for providing the information. I don't think there would be a way to support OAuth 2 with this library.

**Comment by jaibatrik** [comment]
Closing. LinkedIn has stopped supporting JS SDK for authentication.
