### ISSUE TITLE
Add lazy load of login providers SDKs to prevent setting excess cookies before it's needed

### ISSUE THREAD

**Issue by mbarouski** [abacritt/angularx-social-login#158]
# Description:
Would be good to have opportunity to laod login providers SDKs after some moment to prevent loading of login providers cookies before this moment.

Will try to add such functionality. Maybe it will be merged to master.

**Comment by prem6667** [comment]
There is no option for lazyLoad in the latest version **Angular 9/10**,

**Comment by jaibatrik** [comment]
Right, these changes got omitted in version 3 refactoring. I am in the middle of refactoring the login providers again due to #280. I need to incorporate this as well.

**Comment by raphaelApard** [comment]
Lazyload has been incoprated with fix of #280 ?

**Comment by raphaelApard** [comment]
I made a try here : https://github.com/acolad-developpement/angularx-social-login/commit/4890f0c02dc16ed0b4f99bf3144b0a92f7182628
I'm not sure it's the best way to achieve this, but it works for signIn.
Can we reach signOut without signIn initialization ?

**Comment by jaibatrik** [comment]
> 
> 
> I made a try here : [acolad-developpement@4890f0c](https://github.com/acolad-developpement/angularx-social-login/commit/4890f0c02dc16ed0b4f99bf3144b0a92f7182628)
> I'm not sure it's the best way to achieve this, but it works for signIn.
> Can we reach signOut without signIn initialization ?

Someone can choose to call it I think; though it doesn't make sense. The `autoLogin` itself does not make sense with lazy load.

**Comment by raphaelApard** [comment]
Yes if lazyLoad is enabled, autoLogin is ignored

**Comment by raphaelApard** [comment]
I think this issue needs to be re-open
