### ISSUE TITLE
handle error when social popup is closed

### ISSUE THREAD

**Issue by Mridul16** [abacritt/angularx-social-login#16]
I integrated this module and its working fine. But If I choose signin with google or facebook and then decide to close the popup without signing in then error should be handled. But I am not able to handle  this event. please help.

**Comment by jaibatrik** [comment]
Are you getting a callback in the function you registered with `this.authService.authState.subscribe`?

**Comment by Mridul16** [comment]
no i am getting callback in this.

**Comment by jaibatrik** [comment]
Hi, will check this.

**Comment by chloe-s** [comment]
hello!
i have the same issue, can't catch an error after closing the popup

**Comment by djsanj007** [comment]
Any update on this issue?

**Comment by jaibatrik** [comment]
I made the changes for GoogleLoginProvider to return a Promise that rejects with the error message if there is any error. Same needs to be done for Facebook also.

**Comment by jaibatrik** [comment]
From FB documentation, it is not clear that if they return any promise or error object when the user cancels the operation. Made changes for Google and pushed to npm as well.

**Comment by skylove123** [comment]
@Mridul16  I get the same issue in the latest version (2.2.0), do you have a solution to fix this issue ?
