### ISSUE TITLE
Invalid request for user credentials

### ISSUE THREAD

**Issue by zetremoco** [abacritt/angularx-social-login#161]
Hello,

I am having the following issue. I have done everything accordingly to your tutorial, but after allowing permission for login with the linkedin email and password, this error pops up.
Any chance you know how to help me?
P.S. I am running my Angular app on localhost.
Thank you.

![image](https://user-images.githubusercontent.com/47149361/51916880-2ad3ae00-23d6-11e9-90c2-4d7636ed9731.png)

**Comment by diksha-webguruz** [comment]
Are you able to resolve this issue? As I am also facing the same problem.

Thanks

**Comment by Asaddddd** [comment]
Same Issue. :(

**Comment by jaibatrik** [comment]
LinkedIn not supporting JS SDK any more. Already reported at #157.
