### ISSUE TITLE
LinkedIn integration not working giving error in session.html also it is calling localhost:port/null

### ISSUE THREAD

**Issue by ShwetaVe** [abacritt/angularx-social-login#162]
LinkedIn integration not working giving error in session.html as The source list for Content Security Policy directive 'script-src' contains an invalid source: ''report-sample''. It will be ignored.

Also it is  fiving null:1 GET http://localhost:4200/null 404 (Not Found)

![linkedin issue](https://user-images.githubusercontent.com/42967636/51962447-2e267280-2486-11e9-84bf-d66d948c9a9a.png)

**Comment by captainjackrana** [comment]
Linkedin SDK will no longer be supported by linkedin. See #157

**Comment by ShwetaVe** [comment]
so, what is the solution for this? can you please suggest me an alternative

**Comment by jaibatrik** [comment]
See #157.
