### ISSUE TITLE
Not able to singin via Google or Facebook when build is deployed to nginx docker container

### ISSUE THREAD

**Issue by nagendragillalu** [abacritt/angularx-social-login#166]
Hi ,

I have deployed the build to nginx server inside a docker container  and when I try signin through  google.
Nothing happening. i.e no google signin screen is shown to me.

But it works perfectly fine in my local development environment.
I check for any network issue but found none.
Even Browser console shows nothing when button is clicked.

 you can get demo container image through this: `docker pull nagendragillalu/social_login_demo`

**Comment by jaibatrik** [comment]
Does not appear to be issue with this library. Closing this.
