### ISSUE TITLE
Google auth not work

### ISSUE THREAD

**Issue by mrioso** [abacritt/angularx-social-login#168]
After "this.authService.signIn(GoogleLoginProvider.PROVIDER_ID)" nothing happens. I have my "Google-OAuth-Client-Id", i tried on localhost and shared hosting. 

In GoogleChrome not show errors on console, in Safari show this: _The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored._ 

Anyone know what happens?

**Comment by rfallara** [comment]
seeing I think the same issue. If I run on the dev server using 'ng serve' all seems to work correctly. If I go and build a deployment with 'ng build' or 'ng build --prod' the google signin does nothing. First saw this behavior in my project, then also validated the same behavior with the bundled demo app in this repo

**Comment by nagendragillalu** [comment]
Even I have same issue. I had raised issue here  [https://github.com/abacritt/angularx-social-login/issues/166](url)

**Comment by rofallar** [comment]
Looks like I was chasing a ghost on this one. The issue was on the Google API side it was not trusting the domain the auth request was sourcing from. I fixed in the Google console it all works now. This API will need some better error handling to bubble this up when it fails.

**Comment by mrioso** [comment]
Apparently this was an "error" from google API side, i had all configurated on google console and login did not work, past a few days i try again the login google without modify anything and i finally get success the login google

**Comment by nagendragillalu** [comment]
@mrioso clould youy please share what changes you did on Google console. I am hosting my site in docker container and even setting correct JS origin doesn't work for me.

Regards
Nagendra

**Comment by mrioso** [comment]
Immediately after create "client id oauth" credential, i configured the authorized javascript sources and authorized redirection URIs:

![screenshot at feb 19 19-53-27](https://user-images.githubusercontent.com/11713550/53058160-15571e80-3480-11e9-9888-557d16ce961a.png)

Then i just had to wait for google.
