### ISSUE TITLE
Google Login button not responding

### ISSUE THREAD

**Issue by mightymatth** [abacritt/angularx-social-login#170]
Using standard setup as described in readme.md.

Version 1.2.6 (also tested 1.2.5, 1.2.3)

When I click on button to sign in, pop-up **does not open** and promise on `authService.signIn(GoogleLoginProvider.PROVIDER_ID)` does not return anything (neither in `.then()` or `.catch()` blocks).

Just to mention:
Version 1.1.9

When I click on button to sign in, pop-up **does open**, but after choosing account, pop-up closes and `authService.signIn(GoogleLoginProvider.PROVIDER_ID)` promise returns error in `.catch()` block with object `{ error: "popup_closed_by_user" }` (and I actually didn't close it by myself).

Also tried Facebook login and it works fine. Is there any way to debug this process to figure out where is the problem with Google login? I mean, Google login works fine without using this library, I tried it on separate projects and there is not problem on their side.

**Comment by mightymatth** [comment]
Well, it works now after 1 hour since I've made new Google OAuth client ID. 
I would just like to propose if you can add some error handling in this situation when it fails on Google's side.

**Comment by Mayocampo** [comment]
Good morning. I'm facing the same issue but no luck at all. I've created my client id 4 days ago and still got no response when clicking button. Can you please explain a little bit the process you followed to configure your client id? Thanks.

**Comment by ian-allstar-ms** [comment]
Running the demo app on my local machine brings up the popup box but when the plugin has been included in a ionic 4 app the facebook button works while the google one does not

**Comment by cope** [comment]
Same here :(

I created a new client id as @mightymatth suggested, but this did not help :(

facebook login works just fine.

**Comment by wlojkowski** [comment]
The problem occurs when the browser saved incorrect token in cache. The plugin automatically sending it to iframe and throws an exception. There should be some way to clear saved token.

**Comment by oliverreid** [comment]
I had this issue and it was due to not being configured correctly with Google, there is a call to https://accounts.google.com/o/oauth2/iframerpc or some such with a bunch of parameters. This came back with valid: false until I allowed localhost on the Credentials page within GCP.

Hope this helps.

**Comment by sajinrules** [comment]
@oliverreid Where do we add localhost in Google settings? I couldn't find that. Thanks.

**Comment by Cris87** [comment]
I'm also having the same issue, Google client id created a few days ago and I added the `http://localhost:4200` to the authorized origins in the Credentials settings within GCP but it's still not working... any ideas? (Facebook is working) 

To clarify the Google button click function gets called, I added a `console.log('trying to sign in with google')` and I can see the output in the console but I don't get the pop-up or any kind of response from the actual `this.authService.signIn(GoogleLoginProvider.PROVIDER_ID)`

@sajinrules it's in [Google API Console](https://console.developers.google.com/apis/dashboard) there you select the project, then go to Credentials on the left side menu, select the OAuth you're using (matching client_id) and you will see the option to add authorized origin for JS

![google_authed_origin](https://user-images.githubusercontent.com/10406629/54729257-214e0300-4b48-11e9-8ef0-c6ba9ee48969.png)

**Comment by ruthirlekar** [comment]
@Cris87 I tried changing the URI from Authorized redirect URIs to Authorized Javascript origins still it's not working. I do get an error in the console as mentioned by @oliverreid

**Comment by Cris87** [comment]
Hey @ruthirlekar I'm sorry to hear that, it's working on my project now, I had the same as @mightymatth it just started working the next day (after I added localhost to the url whitelist). I think some Google configuration takes a like 24 to 48 hrs to take effect. This was the only step I took outside of the provided instruction in the ReadMe file, I hope it's the same for you and it's only a matter of time 🤞 

_Small side note:_ It doesn't work when using Incognito/Private browser window, in case you are only testing there. (I usually test my apps on Incognito/Private windows as I develop) If this is the case for you, try testing it in a normal browser. Sorry I couldn't be of more help.

**Comment by steveboy199** [comment]
@Cris87 your implementation works correctly, just letting you know.

**Comment by ovidio** [comment]
@Cris87, don't forget to add the s in https. The Google logon process doesn't really work without it. Also, when I'm testing locally I use `ng serve --port {RandomPortNumber} --ssl` to serve a fake ssl cert which then allows the logon process to work. Make sure to add https://localhost:RandomPortNumber to the Google whitelisting

**Comment by Cris87** [comment]
Great catch and very important tip @ovidio thanks!!

**Comment by DerekFangming** [comment]
@wlojkowski is right. This has something to do with browser cache.

It works in Edge, another browser called "QQ browser", but just not in Chrome. Also I tried incognito mode and it works. Finally, cleaning all caches from Chrome and restarts it also works.

**Comment by jaibatrik** [comment]
Seems like stale token issue. Please try checking if `GoogleLoginProvider#signOut(true)` helps.

**Comment by ImATechnophile** [comment]
@wlojkowski is almost right.
It works in Edge and other browser's but just not in Chrome. Even after clearing all the cache's, cookies it doesn't work in chrome(Incognito as well as in normal window). I guess something we want to enable(true) in the GoogleLoginProvider implementation so that Chrome will allow the process.

**Comment by xErik** [comment]
In Chrome / Ghostery I have to disable the Ghostery setting _Enhanced Ad Blocking_ and _Enhanced Anti-Tracking_.

Telling Ghostery to _Trust this site_ did not help.

All on http://localhost:4200 .

**Comment by mightymatth** [comment]
Like few of you already mentioned, in Brave browser, I've tried to disable _Cross-site cookies blocked_ option and now pop-up opens as it should, but it doesn't fix the issue

> Seems like stale token issue. Please try checking if `GoogleLoginProvider#signOut(true)` helps.

There is no `signOut` method on `GoogleLoginProvider`. Did you mean to use `signOut` method on `AuthService` instance, this does not work. Moreover, I don't even use signOut method because I have global session management mechanism in my application.

**Comment by canerandagio1983** [comment]
Delete google's cookie worked for me

**Comment by vishwanathgrpoli** [comment]
If i use "angularx-social-login": "^3.5.4", then there is no issue, latest version "angularx-social-login": "^4.0.1" is not supporting
