### ISSUE TITLE
Error this.providers is undefined Authservice

### ISSUE THREAD

**Issue by kfragkedaki** [abacritt/angularx-social-login#171]
Hello, 

I am new in programming. I would like to use this library in my angular 7 project. I did everything described and the error it is occurred when I am trying to use AuthService in my Component (as I see it in console) is that this.providers is undefined. Any suggestions?

**Comment by jaibatrik** [comment]
Kindly provide us a sample.

**Comment by jaibatrik** [comment]
It might have been an issue with dependency injection. Closing this for now.
