### ISSUE TITLE
Please rename AuthService to more Social related name

### ISSUE THREAD

**Issue by arnoldsi** [abacritt/angularx-social-login#175]
Hello,
Thank you for this great module.
There is an issue with "AuthService" service name, this is too generic and probably used in many apps to manage authentication process. I suggesting to rename it to something more module related, like "SocialAuthService". I know we can rename the import, but it still seems more logical to rename it

**Comment by jaibatrik** [comment]
From the perspective of this library, won't it be an overhead (considering backward compatibility)?

**Comment by andlewis** [comment]
I just change the name on import to avoid name collisions:

`import { AuthService as SocialAuthService } from 'angularx-social-login'`

**Comment by jaibatrik** [comment]
Changing this in the latest release.
