### ISSUE TITLE
Not getting birthdate after facebook login

### ISSUE THREAD

**Issue by prajaktatkare1234** [abacritt/angularx-social-login#176]
hi,
I am using scope for getting birthdate while login,still it's not getting into query string.
My app id is reviewed.
Below is my scope
scope: 'email,user_birthday',
return_scopes: true

**Comment by prajaktatkare1234** [comment]
hi,
I am using scope for getting birthdate while login,still it's not getting into query string.
My app id is review.
Below is my scope
scope: 'email,user_birthday',
return_scopes: true

**Comment by prajaktatkare1234** [comment]
hi,
 My code in app.module.ts
  const fbLoginOptions: LoginOpt = {
    scope: 'user_birthday, email, public_profile',
    return_scopes: true,
    enable_profile_selector: true
  }
  let config = new AuthServiceConfig([
    {
      id: FacebookLoginProvider.PROVIDER_ID,
      provider: new FacebookLoginProvider(environment.FB_SOCIALLOGIN_ID,
      fbLoginOptions,"en_US","email,birthday,last_name")
    }])
Above code has birthday passed into scope and a function having scope passed into it, but still I am not getting birthdate into response.
When I check it into facebook debugger using access-token, I can't find 'user_birthday' into scope but it's there in query string

**Comment by labun7** [comment]
Here is fix for this problem: https://github.com/abacritt/angularx-social-login/pull/182 
For now only fork and applying this changes is a fix.

**Comment by jaibatrik** [comment]
@prajaktatkare1234 Why are you specifying scope twice?
