### ISSUE TITLE
Not Working for me please help

### ISSUE THREAD

**Issue by jaypalkadam** [abacritt/angularx-social-login#180]
Getting Errors like this

Angular is running in the development mode. Call enableProdMode() to enable the production mode.
sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:52 The method FB.getLoginStatus will soon stop working when called from http pages. Please update your site to use https for Facebook Login. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/
b @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:52
accounts.google.com/o/oauth2/iframerpc?action=checkOrigin&origin=http%3A%2F%2Flocalhost%3A4200&client_id=Google-OAuth-Client-Id:1 Failed to load resource: the server responded with a status of 401 ()
sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:52 The method FB.login will soon stop working when called from http pages. Please update your site to use https for Facebook Login. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/
b @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:52
a @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:128
login @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:150
(anonymous) @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:112
(anonymous) @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:110
(anonymous) @ angularx-social-login.es5.js:9588
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:17299
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17290
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:52 FB.login() called before FB.init().
b @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:52
transform @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:148
prepareCall @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:148
a @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:149
login @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:150
(anonymous) @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:112
(anonymous) @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:110
(anonymous) @ angularx-social-login.es5.js:9588
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:17299
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17290
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:52 The method FB.login will soon stop working when called from http pages. Please update your site to use https for Facebook Login. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/
b @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:52
a @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:128
login @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:150
(anonymous) @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:112
(anonymous) @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:110
(anonymous) @ angularx-social-login.es5.js:9588
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:17299
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17290
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:52 FB.login() called before FB.init().
b @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:52
transform @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:148
prepareCall @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:148
a @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:149
login @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:150
(anonymous) @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:112
(anonymous) @ sdk.js?hash=2a335cfc397a2debc29ca818c4a8d5c2&ua=modern_es6:110
(anonymous) @ angularx-social-login.es5.js:9588
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:17299
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17290
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
core.js:15724 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at Object.authorize (in.js:18)
    at angularx-social-login.es5.js:9710
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:17299)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at resolvePromise (zone.js:831)
    at zone.js:896
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1770)
defaultErrorLogger @ core.js:15724
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15772
next @ core.js:17771
schedulerFn @ core.js:13515
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:13499
(anonymous) @ core.js:17321
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17258
onHandleError @ core.js:17321
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
push../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ zone.js:164
_loop_1 @ zone.js:694
api.microtaskDrainDone @ zone.js:703
drainMicroTaskQueue @ zone.js:608
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770

**Comment by jaibatrik** [comment]
Does not appear to be a problem with the library. Facebook is asking you to use https.
