### ISSUE TITLE
Google Scopes

### ISSUE THREAD

**Issue by AndyHaas** [abacritt/angularx-social-login#183]
Newb here working on getting the google login working with scopes. We have the login prompting us for the permission, but I have looked around docs and the code to try to figure out where I can access this data. Since we have a G Suite account some of the users' information is in a different API.

Let me know or send some examples.

**Comment by jaibatrik** [comment]
If you need more information from API specific for G Suite, you can try adding that to the library. PRs are welcome.

**Comment by jaibatrik** [comment]
@AndyHaas Closing this. I feel that this does not need to be part of the library because the use case is probably not that common.

However, a PR is welcome if it conforms to the current structure of the library. I'll be glad to discuss should you be interested to add the features.
