### ISSUE TITLE
Cannot update to Angular 8

### ISSUE THREAD

**Issue by mbouclas** [abacritt/angularx-social-login#184]
Package "angularx-social-login" has an incompatible peer dependency to "zone.js" (requires "^0.8.29", would install "0.9.1").

**Comment by jaibatrik** [comment]
Submit a PR if possible.

**Comment by suwigyarathore** [comment]
really? i did got update with Angular 8

**Comment by luiscmas** [comment]
How did you got update with Angular 8? I receive this error:
Package "angularx-social-login" has an incompatible peer dependency to "zone.js" (requires "^0.8.29", would install "0.9.1").

**Comment by luiscmas** [comment]
> Submit a PR if possible.

Do you have instructions on how to contribute? Thanks!!! I'd like to make it compatible to Angular 8.

**Comment by ydang204** [comment]
> > Submit a PR if possible.
> 
> Do you have instructions on how to contribute? Thanks!!! I'd like to make it compatible to Angular 8.

Did you make a PR for this issue?

**Comment by rafa-as** [comment]
Some news here? @luiscmas  ?

**Comment by luiscmas** [comment]
> Some news here? @luiscmas ?

Nope... sorry... I can't figure out how to contribute to this repo. 

@jaibatrik could you share instructions on how could I contribute?

@rafa-as I just upgraded to Angular 8, removing the package, upgrading and then adding the package and it worked fine...

**Comment by rafa-as** [comment]
@jaibatrik @luiscmas no worries, we will do the PR this afternoon.

**Comment by jaibatrik** [comment]
Will test with Angular 8 this weekend. It seems to work with Angular 8 for many.

**Comment by robertrandallphillips** [comment]
I also get the incompatible peer dependency error.

Package "angularx-social-login" has an incompatible peer dependency to "zone.js" (requires "^0.8.29", would install "0.9.1").

Wonder why it works for some but not others. Thanks for looking into it @jaibatrik.

**Comment by robertrandallphillips** [comment]
Just a follow up. I did get my app updated to ng8. I had to update zone.js to 0.9.1 first. However, this module shows these warning when building...

npm WARN angularx-social-login@1.2.7 requires a peer of @angular/core@^7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN angularx-social-login@1.2.7 requires a peer of zone.js@^0.8.29 but none is installed. You must install peer dependencies yourself.

**Comment by luiscmas** [comment]
> Will test with Angular 8 this weekend. It seems to work with Angular 8 for many.

Hi @jaibatrik @rafa-as, did you test it against angular 8 and submit the PR? Angular 9 with ivy enabled is going live next November...

**Comment by somcoder** [comment]
This has been fixed with #209 
@jaibatrik please take a look and review.

**Comment by bielas** [comment]
when this gonna be merged?
