### ISSUE TITLE
Not working with Ivy

### ISSUE THREAD

**Issue by suwigyarathore** [abacritt/angularx-social-login#186]
Trying to update my project to use ivy but this package is breaking the build 

```
ERROR in Failed to find exported name of node (CommonModule = /** @class */ (function () {
    function CommonModule() {
    }
    CommonModule.decorators = [
        { type: NgModule, args: [{
                    declarations: [COMMON_DIRECTIVES, COMMON_PIPES],
                    exports: [COMMON_DIRECTIVES, COMMON_PIPES],
                    providers: [
                        { provide: NgLocalization, useClass: NgLocaleLocalization },
                    ],
                },] }
    ];
    /** @nocollapse */
    CommonModule.ctorParameters = function () { return []; };
    return CommonModule;
}()))

```

**Comment by zepekenio** [comment]
same for me

**Comment by GarrettCulos** [comment]
Any movement on this? same issue here.

**Comment by keserwan** [comment]
same here.
any progress?

**Comment by elementalPRESS** [comment]
are there any news?

**Comment by aershov24** [comment]
Same. Failing with **enableIvy** option. 

**ERROR in Value at position 0 in the NgModule.imports of SocialLoginModule is not a reference: [object Object]**

**Comment by zawars** [comment]
@aershov24 Any solution so far?
i am facing the same issue.

**Comment by nadeemse** [comment]
Same. Failing with enable Ivy option.

ERROR in Value at position 0 in the NgModule.imports of SocialLoginModule is not a reference: [object Object]

Any update on this ?

**Comment by keserwan** [comment]
any progress? or any similar package for ivy?

**Comment by elementalPRESS** [comment]
unfortunately, even with the new version 2.1.1 Ivy is not working :-(

**Comment by jaibatrik** [comment]
I'll look into this when I get some time.

**Comment by elementalPRESS** [comment]
> I'll look into this when I get some time.

This would be really great, because (I guess not just me) are going to prepare our apps for the next major release of Angular :-)

**Comment by ALEXOTANO** [comment]
Same case here. 😐, any news? need more data ?

**Comment by somcoder** [comment]
Reproduced this, and I can confirm that the issue exists. What's really interesting about this is the fact that this issue is caused by the `CommonModule` in `SocialLoginModule`'s imports, that does nothing (AFAIK) but to break everything!
Will submit a PR on this. ☺️

**Comment by ALEXOTANO** [comment]
> Reproduced this, and I can confirm that the issue exists. What's really interesting about this is the fact that this issue is caused by the `CommonModule` in `SocialLoginModule`'s imports, that does nothing (AFAIK) but to break everything!
> Will submit a PR on this. ☺️

I can confirm that if you use `ng-packagr` as ( I think ) you suggested in other issue, solves the problem, I haven't PR beacause I didn't fully tested. (deploy to https server).

**Comment by somcoder** [comment]
@ALEXOTANO That wasn't me, but from now on I'm suggesting `ng-packagr`. 😄
I checked with `ng-packagr`, and it works. I think so much overhead could've been removed just by using `ng-packagr`.

**Comment by ALEXOTANO** [comment]
> @ALEXOTANO That wasn't me, but from now on I'm suggesting `ng-packagr`. 😄

An impostor!😆, sorry kind of dizzy with the back and forth with the IVY compiler. 

> I checked with `ng-packagr`, and it works. I think so much overhead could've been removed just by using `ng-packagr`.

Great! Yes, I've been able to solve that same problem with a couple of libraries just by using `ng-packagr`. Are you PRing it now ? did you test it in production?

**Comment by somcoder** [comment]
@ALEXOTANO Yeah, I tested it with a project that I'm working on, and it works.
About the PR, the changes are higher, 32 so far, without even removing what needs to be removed.
Will wait for @jaibatrik to confirm on this, and then I will PR.

**Comment by ALEXOTANO** [comment]
I know by first hand that the changes needed to be done won't take long but as you said its a major change (compiler), hope @jaibatrik  can approve on this soon. I want to test IVY since vesion 9 will be a default and we're behind the wave.

**Comment by omahjoub** [comment]
Hi, Is there any plan to fix this?

**Comment by manchuwook** [comment]
Even with AOT fix, getting this:
```
ERROR in Failed to compile entry-point angularx-social-login due to compilation errors:
node_modules/angularx-social-login/angularx-social-login.js(8050,26): error TS-991010: Value at position 0 in the NgModule.imports of SocialLoginModule is not a reference: [object Object]
```

**Comment by jaibatrik** [comment]
#229 addresses this. I merged it and published it in npm. C2.2.0 should support Ivy according to the submitter of the PR.
