### ISSUE TITLE
Setting the token on load

### ISSUE THREAD

**Issue by anandhuajayakumar** [abacritt/angularx-social-login#191]
I need to allow my users to revoke their facebook permissions at any time they want. I implemented the app with the package and log in and log out works correctly.
But when I refresh the page after logging in to facebook it still shows log in. 
This issue is there in the demo too.
 I need to be able to show log out even after refresh if the user is logged in

**Comment by jaibatrik** [comment]
Your logout must not have happened properly. Check console for errors. The issue is not present on the demo page. I verified it now.
