### ISSUE TITLE
localhost also requesting for HTTPS

### ISSUE THREAD

**Issue by dhananshan** [abacritt/angularx-social-login#192]
As per facebook they allow http only when it is in development mode, but the plugin enforcing to use https.

> The method FB.getLoginStatus can no longer be called from http pages. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/

> "Facebook Login status is only available to HTTPS pages."

**Comment by dunstontc** [comment]
You're gonna need to setup an SSL cert on your machine for localhost.
You'll probably want to look at [this project](https://github.com/dakshshah96/local-cert-generator/)

**Comment by dhananshan** [comment]
> You're gonna need to setup an SSL cert on your machine for localhost.
> You'll probably want to look at [this project](https://github.com/dakshshah96/local-cert-generator/)

I previously tried ng serve --ssl by setting up load SSL.. but its not stable in debug mode. At least for me.

**Comment by jaibatrik** [comment]
Not a problem with the library itself. Closing the issue. Kindly search the web for possible solution.
