### ISSUE TITLE
Unable to unsubscribe from authState Observable

### ISSUE THREAD

**Issue by sjmiller85** [abacritt/angularx-social-login#196]
Calling ``this.authService.authState.unsubscribe()`` returns the error ``Property 'unsubscribe' does not exist on type 'Observable<SocialUser>'.``  What do I need to do to unsubscribe from this observable?

**Comment by jaibatrik** [comment]
Does not appear to be an issue with the library. Observables are from RxJS. Do you have a sample?

**Comment by jaibatrik** [comment]
I think the way you are trying to unsubscribe is incorrect. If I remember correctly, the subscription is returned when you call `subscribe` function. You need to call `unsubscribe` on the `subscription` object. Something like below.

```
this.subscription = this.authService.authState.subscribe();
// ... later
this.subscription.unsubscribe();
```

**Comment by TLKG** [comment]
@jaibatrik For every subscription, we supposed to unsubscribe. Although don't see it's mention for this package, believe it's needed, right?

**Comment by jaibatrik** [comment]
> @jaibatrik For every subscription, we supposed to unsubscribe. Although don't see it's mention for this package, believe it's needed, right?

Nothing special about this subscription. It'd be needed to avoid leaks.
