### ISSUE TITLE
Facebook login - always prompt

### ISSUE THREAD

**Issue by anandhuajayakumar** [abacritt/angularx-social-login#197]
I am using this package in my angular 7 application for login into both facebook and youtube.
My issue is that google always has the prompt but facebook does not have the **prompt**. Hence I am not able to allow/disallow permissions. 

**_Is there any way to make sure that the prompt always appears?_**

I have tried changing the auth type, but the prompt is still not available

**Comment by jaibatrik** [comment]
Not an issue with the library itself.

You could call signOut initially when your page loads perhaps.
