### ISSUE TITLE
Token refresh support

### ISSUE THREAD

**Issue by SetV** [abacritt/angularx-social-login#198]
After login how token is refreshed? Any additional implementation required?

The Readme document doesn't have an explanation. Please add for clarity.

**Comment by SetV** [comment]
Token refresh is been supported already?

**Comment by jaibatrik** [comment]
@SetV There might already be support for this. Check the `GoogleLoginProvide` or `FacebookLoginProvider` for example. Reopen if it does not satisfy you. You are always welcome to submit a PR.
