### ISSUE TITLE
Error: Uncaught (in promise): Not logged in

### ISSUE THREAD

**Issue by Helveg** [abacritt/angularx-social-login#199]
I'm unable to catch this error, and it's annoying :p

It occurs when you try to sign out when you're not signed in. I need to make this call however because if you were logged in to multiple providers the AuthState might be logged out but you're still logged in with another provider.

```
Error: Uncaught (in promise): Not logged in
    at resolvePromise (zone.js:831)
    at zone.js:741
    at angularx-social-login.es5.js:1843
    at new ZoneAwarePromise (zone.js:910)
    at AuthService.push../node_modules/angularx-social-login/angularx-social-login.es5.js.AuthService.signOut (angularx-social-login.es5.js:1836)
```

**Comment by jaibatrik** [comment]
You could use `signOut().then().catch(yourHandler)` or something in the similar lines.

**Comment by Helveg** [comment]
Ah sorry, never used promises before, sorry ;)
