### ISSUE TITLE
Exception when offline access is set

### ISSUE THREAD

**Issue by khelmar** [abacritt/angularx-social-login#201]
I am getting the following exception when trying to login using offline access with Google:

Uncaught (in promise): TypeError: Cannot read property 'access_token' of null
TypeError: Cannot read property 'access_token' of null at angularx-social-login.es5.js:8121

It looks like even when offline access is set to true you are expecting the full response and only at the end trying to get the auth code. It seems like the correct way to do this is to do an if/else and separate the auth code section from the other section.

Also, with offline access you should only be returning the authorization code, not any of the other inofrmation.

**Comment by jaibatrik** [comment]
A PR for this will be welcome. Thanks!

**Comment by BruneXX** [comment]
Hi guys, before report a new ticket I want to know if anyone has experienced this issue before:

> You are overriding current access token, that means some other app is expecting different access token and you will probably break things. Please consider passing access_token directly to API parameters instead of overriding the global settings.

**Comment by jaibatrik** [comment]
Keeping open for now. Has PR.

**Comment by RodrigoBoviIS** [comment]
angularx-social-login": "^2.2.1

Hi all, i get the same error, when i use visitor user to navigate on google chrome.

Uncaught (in promise): TypeError: Cannot read property 'access_token' of null

**Comment by jaibatrik** [comment]
Try checking if the above fix is available in the code for that version.
