### ISSUE TITLE
Pop is not open for choose google id if single id is login in gmail.

### ISSUE THREAD

**Issue by gurpreet-developer** [abacritt/angularx-social-login#205]
HI

I'm getting issue when login first time its working and after logout when again try to login with different id it not open the popup for choose different id. i logging with prev id when click on login.

if you have login multiple accounts in gmail. then thay asking for choose id for login with,.

**Comment by digitlz** [comment]
Could you provide more details and code examples? Can you provide a reproducible scenario on [stackblitz](https://stackblitz.com/)?

**Comment by jaibatrik** [comment]
Try using `signOut(true)` instead of `signOut()`. Reopen if it does not help.
