### ISSUE TITLE
error catch?...

### ISSUE THREAD

**Issue by 4i-helpynet** [abacritt/angularx-social-login#206]
how can I catch this error:

ERROR Error: Uncaught (in promise): Object: {"error":"idpiframe_initialization_failed","details":"Not a valid origin for the client: ... 

thank you.

**Comment by jaibatrik** [comment]
Not an issue with the library. Try searching on the internet. See examples such as https://stackoverflow.com/questions/44068680/not-a-valid-origin-for-the-client-from-google-api-oauth

**Comment by funar** [comment]
It may not be a library issue, but the ability to catch() the error would certainly be desired. Seeing as the library does all the setup of the Google auth flow, there's no clear place to insert a catch(). Google has had some OAuth issues this week, which is pressing this.

**Comment by Selindek** [comment]
I believe it IS an issue. I want to handle the possible initialization errors during startup, but I cannot. I think socialAuthService.initState onError should be called if an error occurs during initialization.

**Comment by jaibatrik** [comment]
> I believe it IS an issue. I want to handle the possible initialization errors during startup, but I cannot. I think socialAuthService.initState onError should be called if an error occurs during initialization.

Yeah, the `onError` callback should get invoked. That's the desired behavior. Is it not happening?

**Comment by IceBjerg** [comment]
Any update on this? 

To reproduce this, open the page from another dns, which is not registered under the google client id. 
For example: localhost --> local IP
My local IP is not a valid origin for the client (not registered in google console), so the social login does not work. However, I would like to show that error on the login page. Right now, there is absolutely no chance of catching the error through this library. 
If I open the console, I see there the error message, but there is no event given anywhere with the socialAuthService. 
![image](https://user-images.githubusercontent.com/26023511/124268735-3349e900-db3a-11eb-8c30-d3b3a86a619e.png)


I think the only way to do that at the moment is to rewrite the console.error function, and try to catch the error when outputted, but I don't think that's a good idea, and I prefer not to implement it that way. 

Can you please reopen this issue?

**Comment by jaibatrik** [comment]
Just to be clear, there is an `onError` callback that one can pass as part of `SocialAuthConfig` object. That function should get invoked for this error. Try setting it and see if you are able to catch the error.
