### ISSUE TITLE
Even with following suggested workaround, while building IONIC3 App with --aot getting AuthServiceConfig related error 

### ISSUE THREAD

**Issue by haresh333** [abacritt/angularx-social-login#208]
I am using abacritt/angularx-social-login in my IONIC 3 app. While building IONIC App debug mode, it builds without any issue.

If built with --prod it throws following error.
**src\app\app.module.ts(26,18): Error during template compile of 'AppModule' Function calls are not supported decorators but 'AuthServiceConfig' was called.**

**Below are versions of various npm modules I am using.** 
    "@angular/core": "5.2.11",
@ionic/cli-utils  : 1.19.3
    ionic (Ionic CLI) : 3.20.1
@ionic/app-scripts : 3.2.4
    Ionic Framework    : ionic-angular 3.9.2
    Node              : v8.11.1
    npm               : 6.0.0
    OS                : Windows 10

I have exactly same app.module.js as suggested in below workaround for AOT issue.
https://github.com/abacritt/angularx-social-login/blob/master/README-AOT.md

Please advice.

**Comment by jaibatrik** [comment]
Try the same code from the [demo app](https://github.com/jaibatrik/angularx-social-login-demo).

**Comment by b0lle** [comment]
same problem here

**Comment by b0lle** [comment]
i had the same problem. check if the import of the module is correct.
this was wrong in app.module.ts:
`imports: [SocialLoginModule.forRoot(), ...]`
it has to be:
`imports: [SocialLoginModule, ...]`
