### ISSUE TITLE
Issue in safari

### ISSUE THREAD

**Issue by shaharyar-shamshi** [abacritt/angularx-social-login#210]
I have build an webapp in which user is login using the social login but there is some issue with safari . let me describe you to reproduce
1) go to any website using this modules for social using safari browser
2) login using google then  close the tab and safari browser
3) again open safari browser and open that particular you will find you are logout from the app

I am looking for solution of it as it does not happen in chrome or any other browser . I will be highly thankful if anyone could help me out

**Comment by shaharyar-shamshi** [comment]
@jaibatrik  can you kindly help me out I will be highly thankful to you

**Comment by shaharyar-shamshi** [comment]
@jaibatrik kindly have a look

**Comment by jaibatrik** [comment]
Not at all, in my Mac Safari, it remembers the login perfectly. Try checking the "Remember me" option when logging in to Google.

**Comment by shaharyar-shamshi** [comment]
@jaibatrik in mobile safari it is causing error

**Comment by jaibatrik** [comment]
I don't have an iPhone / emulator to debug this. You can try debugging / searching for this type of issue. If it's a problem with the library, you can always send a pull request.
