### ISSUE TITLE
Facebook provider using deprecated API version

### ISSUE THREAD

**Issue by stefanjanjic90** [abacritt/angularx-social-login#211]
As you can see on Facebooks official change log webpage version 2.9 
has been deprecated on 22nd of July 2019.
Link: https://developers.facebook.com/docs/graph-api/changelog/archive#version2-9
From the source code in Facebook provider it seems that the library is still using the deprecated version.
Are there any plans for upgrade?

**Comment by jaibatrik** [comment]
Updated and published with SDK v4.0.
