### ISSUE TITLE
Possible issue with attribute `SameSite` 

### ISSUE THREAD

**Issue by BruneXX** [abacritt/angularx-social-login#215]
Hi Guys, I saw this issue days ago, someone found a workaround to fix this?

A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.

Also I've found a similar issue here: https://stackoverflow.com/questions/58226192/hi-how-can-i-fix-this-warning-from-google-chrome-cookie-samesite-none-but 
but with no response yet.

Thanks!

**Comment by somcoder** [comment]
I think this is related to the underlying libraries, as this library doesn't store any cookies, AFAIK.
https://github.com/google/google-api-javascript-client/issues/561

**Comment by jaibatrik** [comment]
Do we need to do any version upgrade of any of the SDKs?

**Comment by bkarv** [comment]
Hi everyone, did you find a solution in the end?

**Comment by digovc** [comment]
Up.

**Comment by BetoShiver** [comment]
I have this issue when trying to implement google authentication from firebase, anyone actually found a way to solve this?

**Comment by orenab1** [comment]
Same issue. Using angular app, following [this ](https://www.positronx.io/angular-google-social-login-tutorial-with-example/) tutorial.
