### ISSUE TITLE
New version 2.1.0 doesn't work

### ISSUE THREAD

**Issue by elementalPRESS** [abacritt/angularx-social-login#216]
Hi,

I installed the latest release angularx-social-login@2.1.0. As far as I could see no API changes were necessary, right? It compiles fine, but when pressing "Login to Google" nothing happens. I would expect to see the window with the Google confirmation. There is no error or any other output to the console, so I have no idea how to handle...

Where is the error? Is it on my side or something wrong with the new build?

Best regards,
Lars

**Comment by jaibatrik** [comment]
Yeah. Some bug crept in. Fixed and published 2.1.1. Please update and check.

**Comment by elementalPRESS** [comment]
Thx for your fast response and fix. Now it works!
