### ISSUE TITLE
How to Handle user Auth?

### ISSUE THREAD

**Issue by Scylin232** [abacritt/angularx-social-login#220]
Greetings to all! I need help using this library - I encountered a problem that I need to perform routing when a user has successfully logged in, how can this be done?

**Comment by xErik** [comment]
Setup a listener to the authentication service. See the methods below, especially `ngOnInit()`.

```javascript
import { Router } from '@angular/router';
import { AuthService, SocialUser } from 'angularx-social-login';

...

constructor(
    private authService: AuthService,
    private router: Router
  ) {}

...

ngOnInit() {
    this.authService.authState.subscribe(user => {
      this.user = user;
      this.loggedIn = user != null;
      if (this.loggedIn) {
        this.router.navigate(['/user-detail']);
      }
    });
  }

  signInWithGoogle(): void {
    this.authService
      .signIn(GoogleLoginProvider.PROVIDER_ID)
      .then(result => {
        console.log('signInWithGoogle', result);     
      })
      .catch(err => {
        console.log('signInWithGoogle', err);
      });
  }

  signInWithFB(): void {
    this.authService.signIn(FacebookLoginProvider.PROVIDER_ID);
  }

  signOut(): void {
    this.authService.signOut();
  }
```

**Comment by Scylin232** [comment]
> 
> 
> Setup a listener to the authentication service. See the methods below, especially `ngOnInit()`.
> 
> ```js
> import { Router } from '@angular/router';
> import { AuthService, SocialUser } from 'angularx-social-login';
> 
> ...
> 
> constructor(
>     private authService: AuthService,
>     private router: Router
>   ) {}
> 
> ...
> 
> ngOnInit() {
>     this.authService.authState.subscribe(user => {
>       this.user = user;
>       this.loggedIn = user != null;
>       if (this.loggedIn) {
>         this.router.navigate(['/user-detail']);
>       }
>     });
>   }
> 
>   signInWithGoogle(): void {
>     this.authService
>       .signIn(GoogleLoginProvider.PROVIDER_ID)
>       .then(result => {
>         console.log('signInWithGoogle', result);     
>       })
>       .catch(err => {
>         console.log('signInWithGoogle', err);
>       });
>   }
> 
>   signInWithFB(): void {
>     this.authService.signIn(FacebookLoginProvider.PROVIDER_ID);
>   }
> 
>   signOut(): void {
>     this.authService.signOut();
>   }
> ```

Thank's you very-much!
