### ISSUE TITLE
why there is no facebook login dialog to confirm the user

### ISSUE THREAD

**Issue by henryyue2010** [abacritt/angularx-social-login#221]
When I login as facebook user, there is no facebook dialog popup to confirm the user. The user is directly authorized. 
Anyone knows what caused the problem? Thank you very much in advance for your help.

**Comment by xErik** [comment]
The user is already logged in. To make the popup appear again, the user needs to logout manually.

Force a logout in the browser by clearing the browser cache and do a [hard reload](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.XbGB6pr7TIU).

**Comment by henryyue2010** [comment]
> The user is already logged in. To make the popup appear again, the user needs to logout manually.
> 
> Alternatively, usually during development, force a logout in the browser by clearing the browser cache and do a [hard reload](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.XbGB6pr7TIU).

I don't have the issue for signing in other websites (like Airbnb, Etsy, etc) using my Facebook account.  Same browser without logging out Facebook.  All other websites displayed the Facebook confirmation page to ask me for authorization.

**Comment by xErik** [comment]
Something like this?

```javascript 
signInOptions: [
    {
      customParameters: {
        auth_type: 'reauthenticate',
        prompt: 'select_account'
      },
      provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID
    },
    {
      customParameters: {
        auth_type: 'reauthenticate',
        prompt: 'select_account'
      },
      provider: firebase.auth.FacebookAuthProvider.PROVIDER_ID
    }
]
```

**Comment by henryyue2010** [comment]
> Something like this?
> 
> ```js
> signInOptions: [
>     {
>       customParameters: {
>         auth_type: 'reauthenticate',
>         prompt: 'select_account'
>       },
>       provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID
>     },
>     {
>       customParameters: {
>         auth_type: 'reauthenticate',
>         prompt: 'select_account'
>       },
>       provider: firebase.auth.FacebookAuthProvider.PROVIDER_ID
>     }
> ]
> ```

I tried to use the custom scope 
```
const fbLoginOptions: LoginOpt = {
  scope: 'pages_messaging,pages_messaging_subscriptions,email,pages_show_list,manage_pages',
  return_scopes: true,
  enable_profile_selector: true
}; 
```
but the popup is different than the normal facebook popup. It has several steps to confirm, not one click to finish the authorization. if I change the scope to "email" only, no popup again. Anything wrong?

**Comment by jaibatrik** [comment]
Try to call sign out at the init function of your component.

**Comment by sachinsoliya975** [comment]
@jaibatrik facing similar issue with google login.
When there are multiple google accounts, dialog popup to confirm the user, but in case if there is only a single google account, the user is directly authorized.

I tried to call sign out at the init, still facing same issue.

@henryyue2010, did _facebook login dialog to confirm the user_ issue resolved?

**Comment by henryyue2010** [comment]
> @jaibatrik facing similar issue with google login.
> When there are multiple google accounts, dialog popup to confirm the user, but in case if there is only a single google account, the user is directly authorized.
> 
> I tried to call sign out at the init, still facing same issue.
> 
> @henryyue2010, did _facebook login dialog to confirm the user_ issue resolved?

No, not yet

**Comment by jaibatrik** [comment]
If there is a sample, I could try looking at it. Also, please let us know if you guys already figured it out.

**Comment by bodinaren** [comment]
Isn't this just when you have not previously allowed the app? If in Facebook you remove the permissions for your app then I believe you will get the popup asking for permission next time.

**Comment by fatihyildizhan** [comment]
@henryyue2010 Could you solve the asking custom scope issue? I am facing the same issue now.

**Comment by jaibatrik** [comment]
I think we will disable the auto-login feature by default. Anyone requesting auto-login will need to manually call `authService.getLoginStatus(providerId)` (to be introduced) or pass a flag with `AuthServiceConfig` to enable auto-login. This behavior has been a constant stream of issues so far.

I'll create a PR this weekend.

**Comment by chiranshu14** [comment]
@henryyue2010  were you able to get it working? Can you please suggest a solution to get the popup for user selection while logging into Facebook?
Thanks!
