### ISSUE TITLE
I can´t get the email

### ISSUE THREAD

**Issue by alambertt** [abacritt/angularx-social-login#223]
When I get the data from loggued user the email is undefined, but I has defined previoulsy that way

```
const fbLoginOptions: LoginOpt = {
    scope: 'email',
    return_scopes: true,
    enable_profile_selector: true
};

const config = new AuthServiceConfig([
    {
        id: FacebookLoginProvider.PROVIDER_ID,
        provider: new FacebookLoginProvider('2236457316462801', fbLoginOptions)
    }
]);
```

![Captura de pantalla (37)](https://user-images.githubusercontent.com/6148597/67619233-fc4cfd00-f7c6-11e9-9b74-b4bb74390c09.png)

**Comment by jaibatrik** [comment]
Might be an issue with the FB SDK. Do you have a sample where we can see the issue?

**Comment by jaibatrik** [comment]
Closing; please reopen with a sample.

**Comment by marcellobarile** [comment]
@alambertt might be that Facebook doesn't expose the email if the user set it to private in the privacy settings.
