### ISSUE TITLE
Refused to display 'https://www.facebook.com/home.php' in a frame because it set 'X-Frame-Options' to 'deny'

### ISSUE THREAD

**Issue by Pratikshakhandagale** [abacritt/angularx-social-login#225]
Facing this issue while logout from facebook login. Did not found any solution for this.

**Comment by somcoder** [comment]
Possible duplicate of #151.
Probably not a problem with this library, [this](https://stackoverflow.com/questions/22331373/facebook-js-api-cant-logout) may help.

**Comment by Pratikshakhandagale** [comment]
> Possible duplicate of #151.
> Probably not a problem with this library, [this](https://stackoverflow.com/questions/22331373/facebook-js-api-cant-logout) may help.

@somcoder - Thanks for reply.
Above solution work for me.
