### ISSUE TITLE
Cookie warning for Google

### ISSUE THREAD

**Issue by Ahmed3laa** [abacritt/angularx-social-login#227]
A warning in the debugging console tool of Chrome 

A cookie associated with a resource at http://google.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.

Chrome version :
Version 78.0.3904.87 (Official Build) (64-bit)

**Comment by jaibatrik** [comment]
#215 is opened to track it.
