### ISSUE TITLE
Login with google does not redirect

### ISSUE THREAD

**Issue by lambojon-rowegie** [abacritt/angularx-social-login#230]
After a successful selection of google account, nothing happens.
version: 1.1.9 (also tried the latest version)

**Comment by vovabrenych** [comment]
Same for me, any solutions?

**Comment by jaibatrik** [comment]
Can you provide a sample where we can see the issue?

**Comment by singhjolly** [comment]
Kindly help me for the attached issue,
![Capture](https://user-images.githubusercontent.com/24824223/69715207-e3b96500-112d-11ea-88e7-2453863eaede.PNG)

**Comment by mickster04** [comment]
https://console.developers.google.com/apis/credentials

Sounds like you either haven't set up creedentials, or you haven't added localhost:4200 to the list if Authorised redirect URIs

**Comment by jaibatrik** [comment]
Closing this; please reopen with a sample.
