### ISSUE TITLE
How to trigger authentication renew

### ISSUE THREAD

**Issue by SetV** [abacritt/angularx-social-login#233]
Does plugin supports Google/Facebook authentication renew?

When the site is revisited after 1 hr, say for Google login, the authentication token seems expired.

How to trigger authentication renew from a page where user is currently accessing?

**Comment by jaibatrik** [comment]
The library provides simple sign in and sign out methods. Check the documentation of the relevant login provider and if needed add the feature to the library. I don't think we provide any explicit renew method.
