### ISSUE TITLE
How do I access signed in user's calendar data

### ISSUE THREAD

**Issue by ghinminesuyog** [abacritt/angularx-social-login#238]
I have provided the necessary scopes for user to permit as:

```
loginOpt : LoginOpt = {
    scope : 'https://www.googleapis.com/auth/calendar',
    redirect_uri : 'dashboard' ,
  };

  signInWithGoogle(): void {
    this.authService.signIn(GoogleLoginProvider.PROVIDER_ID, this.loginOpt).then(x => console.log(x));
  }

```
And when logging in, it prompts the user if they want to let the app access the specified data. My question is, how do I retrieve the calendar data? Is the data returned back on some variable like the email id is available at user.email?

**Comment by ghinminesuyog** [comment]
Another question that I have is whether I should provide the redirect uri here or in some other place because I am not redirected to the specified path.

**Comment by jaibatrik** [comment]
You get the auth token in the `SocialUser` object. You can use that token to request further information.
