### ISSUE TITLE
Please help error ERR_BLOCKED_BY_CLIENT!

### ISSUE THREAD

**Issue by thuctd** [abacritt/angularx-social-login#239]
GET https://apis.google.com/js/platform.js net::ERR_BLOCKED_BY_CLIENT 
angularx-social-login.js:277
i used 2.2.1

**Comment by jaibatrik** [comment]
Kindly provide more information, a sample if possible.

**Comment by nickmorton** [comment]
I recently had the exact same issue and it was my ad blocker.

**Comment by jhenrich** [comment]
Got same, was blocked by uBlock. Origin. Check your browser extensions if anyone blocks your requests, its clearly on the client side

**Comment by jaibatrik** [comment]
Closing this; appears to be not related to the library.
