### ISSUE TITLE
Hi I am unable to signout for Google with this code....... Ca n any one give suggestions???

### ISSUE THREAD

**Issue by madhaviJakkam** [abacritt/angularx-social-login#24]
Hi I am unable to signout for Google with this code....... Ca n any one give suggestions???

I implemented as it is in angular4 social login example..................
AuthService.prototype.signOut = function () {
var _this = this;
return new Promise(function (resolve, reject) {
//if (providerObject) {
if (_this._user && _this._user.provider) {
var /** @type {?} / providerId = _this._user.provider;
var /* @type {?} */ providerObject = _this.providers.get(providerId);
providerObject.signOut().then(function () {
_this._user = null;
_this._authState.next(null);
resolve();
// });
}).catch((err) => {
this._authState.next(null);
});
}
else {
reject(AuthService.LOGIN_PROVIDER_NOT_FOUND);
}
});
};
return AuthService;

GoogleLoginProvider.prototype.signOut = function () {
var _this = this;
return new Promise(function (resolve, reject) {
_this.auth2.signOut().then(function (response) {
resolve();
//_this.auth2.signIn(false);
});

**Comment by madhaviJakkam** [comment]
AuthService.prototype.signOut = function () {
        var _this = this;
        return new Promise(function (resolve, reject) {
            //if (providerObject) {
                if (_this._user && _this._user.provider) {
                    var /** @type {?} */ providerId = _this._user.provider;
                    var /** @type {?} */ providerObject = _this.providers.get(providerId);
                providerObject.signOut().then(function () {
                    _this._user = null;
                    _this._authState.next(null);
                    resolve();
                // });
            }).catch((err) => {
                this._authState.next(null);
              });
            }
            else {
                reject(AuthService.LOGIN_PROVIDER_NOT_FOUND);
            }
        });
    };
    return AuthService;

-------------------------------------------------------------
GoogleLoginProvider.prototype.signOut = function () {
        var _this = this;
        return new Promise(function (resolve, reject) {
            _this.auth2.signOut().then(function (response) {
                resolve();
                //_this.auth2.signIn(false);
        });

**Comment by madhaviJakkam** [comment]
Hi I am unable to signout for Google with this code....... Ca n any one give suggestions???
I implemented as it is in angular4 social login example..................
AuthService.prototype.signOut = function () {
var _this = this;
return new Promise(function (resolve, reject) {
//if (providerObject) {
if (_this._user && _this._user.provider) {
var /** @type {?} / providerId = _this._user.provider;
var /* @type {?} */ providerObject = _this.providers.get(providerId);
providerObject.signOut().then(function () {
_this._user = null;
_this._authState.next(null);
resolve();
// });
}).catch((err) => {
this._authState.next(null);
});
}
else {
reject(AuthService.LOGIN_PROVIDER_NOT_FOUND);
}
});
};
return AuthService;

GoogleLoginProvider.prototype.signOut = function () {
var _this = this;
return new Promise(function (resolve, reject) {
_this.auth2.signOut().then(function (response) {
resolve();
//_this.auth2.signIn(false);
});

**Comment by jaibatrik** [comment]
Are you getting any error somewhere? Check JS console probably.

**Comment by deanstephens** [comment]
I am also having an issue with logging out. No errors are displayed and the logout function works correctly initially, but when the page is refreshed the user is logged in again using the same token they just logged out with.

**Comment by rajivpopat** [comment]
The live demo posted on the Git Website has the same issue and even the one you have hosted live has the same issue.

**Comment by nugiwicaksono** [comment]
Any updates on this issue?

**Comment by fernandosanchez1128** [comment]
when you refresh the page,  cookies get lost and you can't logout.

**Comment by jaibatrik** [comment]
Looks like this is happening only for some users. I checked the hosted site and it appears to work for me. I am really clueless here. I'd request people getting the issue to debug a bit and help us.

**Comment by fernandosanchez1128** [comment]
I subscribe to the authentication state again in my logout component with this all the cookies are reload and the logout  is succesfull.

**Comment by ddarthp** [comment]
in Google the SocialUser.authToken property get the access_token but this must be the token_id
```
{
  "token_type": "Bearer",
  "access_token": "<access_token>",
  "scope": "<your scope>",
  "login_hint": "<login_hint>",
  "expires_in": 3600,
  "id_token": "<id_token>",
  "session_state": {
    "extraQueryParams": {
      "authuser": "1"
    }
  }
}
```

**Comment by rahulswimmer** [comment]
I used Google authentication using [npm-6-social-login](https://www.npmjs.com/package/angular-6-social-login) Sign in working as expcted and it is generating a token as well. Using the same instance, i called the signOut method, but it doesn't logs you out of google. Please refer the link and let me know of any possibilities for logout.

**Comment by fernandosanchez1128** [comment]
@rahulswimmer  when you sign in with google if you google account is open, logout only log you out of your application but if when you sign in with google your account is closed , logout log you out the both aplicacion and google.

**Comment by rahulswimmer** [comment]
I want to log out of google even when my account is open. What should i do?

**Comment by ANKITKSANIL** [comment]
@rahulswimmer  ,facing the same issue here. Did you get to any solution ?

**Comment by rahulswimmer** [comment]
@ANKITKSANIL not yet brother!

**Comment by ddarthp** [comment]
destroy the observers when sings out and remove all signup data

**Comment by rahulswimmer** [comment]
@ddarthp:  I clear the session variables i've set while signing up using 'sessionStorage.clear()'. How do I delete observers?

**Comment by ddarthp** [comment]
I suppose that you subscribe to the auth status right? So just unsubscribe
to them,
https://brianflove.com/2016/12/11/anguar-2-unsubscribe-observables/

**Comment by rahulswimmer** [comment]
Following is the code for signOut:

    import { AuthService } from 'angular-social-login'

    constructor( private autuService: AuthService) {}

    signOut(){
      this.authService.signOut();
    }


That's it, that's all mentioned in docs for this  package.

For login I do 


     this.authservice.authstate.subscribe((user:any) => {

    console.log(user);

});

I sure, subscribe while logging in, but when I use authService.authState, there is no unsubscribe method.

**Comment by ddarthp** [comment]
Just do in the signout method

 this.authservice.authstate.unsubscribe()

**Comment by rahulswimmer** [comment]
I tried doing that, I get the following error:

[ts] Property 'unsubscribe' does not exist on type 'Observable<SocialUser>'. Did you mean 'subscribe'?

**Comment by ddarthp** [comment]
const simpleObservable = new Observable((observer) => {
// observable execution your auth code
observer.next("bla bla bla")
observer.complete()
})
// subscribe to the observable
simpleObservable.subscribe()
// dispose the observable
simpleObservable.unsubscribe()

**Comment by rahulswimmer** [comment]
Sorry brother, could not understand why to use observers. Following is my code, can you suggest changes in the same?

app.module.ts:

    import { SocialLoginModule, AuthServiceConfig, GoogleLoginProvider } from 'angularx-social-login';
    const config = new AuthServiceConfig([
     {
       id: GoogleLoginProvider.PROVIDER_ID,
       provider: new 
       GoogleLoginProvider(required client id after configuring a project in google.
       apps.googleusercontent.com')
      }
     ]);

     export function provideConfig() {
     return config;
     }
     @ngModule({
         imports: [
      SocialLoginModule,
       ],
      providers: [
         GoogleauthService,
         {
           provide: AuthServiceConfig,
           useFactory: provideConfig
         }
      ],
       bootstrap: [AppComponent],
      })

      export class AppModule { }

google-login.component.ts:

     import { AuthService } from 'angularx-social-login';
     import { SocialUser } from 'angularx-social-login';
     import { GoogleLoginProvider } from 'angularx-social-login';

     export class GoogleLoginComponent {
          constructor(private authService: AuthService) {
            this.title = 'Digital Labels!';
            this.showLoader = false;
            }
         }

        signInWithGoogle() {
          this.authService.signIn(GoogleLoginProvider.PROVIDER_ID).then(
              (user) => {
             console.log(user);
          });

header.component.ts:

     signOut() {
        this.router.navigate(['']);
        this.authService.signOut();
        sessionStorage.clear();
        sessionStorage.setItem('isLoggedIn', 'false');
        this.sidenav.close();
        this.showHeader = false;
        this.dialogRef.close();
      }

How should i induce observers in above scenario. I have created 2 components, one for login and one for signout which is in header.

**Comment by fly2099** [comment]
I am having the same issue that I can not sign out.

**Comment by ibtissambth** [comment]
1. https://developers.facebook.com/apps/xxxxxxxxxx/settings/basic/
2. App Domains must be Empty
3. Privacy Policy URL must be Empty
4. Site URL is http://localhost:4200

**Comment by BruneXX** [comment]
Hey guys, did you find a good way to signOut? I'm having the same problem here..

**Comment by ask444** [comment]
Hello,
Use this iframe with URL in your login component

<iframe style="display: none" src="https://accounts.google.com/Logout?"></iframe>

**Comment by BruneXX** [comment]
Is there a way to signOut from all social networks? this is not working ok right now..
