### ISSUE TITLE
Sign in with Apple

### ISSUE THREAD

**Issue by stsness** [abacritt/angularx-social-login#240]
Can there be login with Apple as well ? Apple is saying April 2020 will be the deadline to support “Sign in with Apple ID". All apps with third party login will have this kind of login.

**Comment by acanewby** [comment]
Yes - I've been thinking about this too.  In fact, I'm in a position where I could work on it.  

Ideally, I'd like to write my own implementation first, by extending `BaseLoginProvider`.  Once I have something working, I'd be happy to contribute it back to the code base.  However, `BaseLoginProvider` isn't exported so I get the following error when I build:

`Module not found: Error: Can't resolve 'angularx-social-login/src/entities/base-login-provider' `

Any advice on an "Angular friendly" approach I could take?

**Comment by fundenys** [comment]
Hi,
You can do it but there are a problem: apple Callback the response with redirect_url.
You must have another Endpoint.
if you want try yourself some tips:
it was just to  test
copy googleLogin Provider and replace
declare let AppleID: any;

export class AppleLoginProvider extends BaseLoginProvider
.......
this.loadScript(AppleLoginProvider.PROVIDER_ID,
                'https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js',
                () => {
                        this.auth2 = AppleID.auth.init({
                             clientId : '[YOUR_CLIENT_ID],
                            scope : 'name email',
                            redirectURI: '[YOUR_NEW_ENDPOINT_CALLBACK]
                        });
                });
.........
 signIn(opt?: LoginOpt): Promise<SocialUser> {
        console.log("AppleCall Signin");
        return new Promise((resolve, reject) => {
                let promise = AppleID.auth.signIn();
.......



It s not optimized, it s just to test, it s working but you cant really use.


Just put the code from apple.js exemple and make the new endpoint

Sorry fot my English, i m  french

**Comment by jaibatrik** [comment]
Will close this when I release it to npm.

**Comment by jaibatrik** [comment]
Well I checked the documentation for Apple sign in and it appears to need a server component; hence things like `getLoginStatus` will not work here. The Apple sign in will be beyond the scope of this library.

**Comment by fundenys** [comment]
@jaibatrik 
I m agree with you.
i said "You must have another Endpoint."
I do it only to help @stsness and @acanewby , for me, Apple signin isnt fully compatible with this component. No Thanks Apple.
For my case, it s ok cause, i send Google, FaceBook, Apple response to another Oauth service (uaa)
Have a Good Day
