### ISSUE TITLE
problem of displaying login dialog to confirm the user in demo

### ISSUE THREAD

**Issue by henryyue2010** [abacritt/angularx-social-login#243]
I tried the demo (https://abacritt.github.io/angularx-social-login/) and found a problem. After signing out and trying to re-sign in, there is no login dialog to confirm the user any more. It goes directly to the page after login. That's for both google and facebook signin. Is there a way to always display the login dialog to confirm the user?

**Comment by jaibatrik** [comment]
Try `signOut(true)` in your code and see if you are getting desired behavior.
