### ISSUE TITLE
Remove the strict peerDependencies on @angular/core lib and RxJS

### ISSUE THREAD

**Issue by romelgomez** [abacritt/angularx-social-login#250]
**angularx-social-login** project set a strict peerDependencies on @angular/core lib and do not make use of nothing fancy that will hard change on the future, please remove this check because it's a common request and lock to update.  

Uses of **@angular/core**: 

`import { NgModule, ModuleWithProviders } from '@angular/core';` 
https://github.com/abacritt/angularx-social-login/blob/master/src/lib/sociallogin.module.ts#L1

`import { Injectable } from '@angular/core';`
https://github.com/abacritt/angularx-social-login/blob/master/src/lib/auth.service.ts#L1

Uses of **RxJS**:

`import { Observable, BehaviorSubject, ReplaySubject } from 'rxjs';`
https://github.com/abacritt/angularx-social-login/blob/master/src/lib/auth.service.ts#L3

`import { BehaviorSubject } from 'rxjs';`
https://github.com/abacritt/angularx-social-login/blob/master/src/lib/entities/base-login-provider.ts#L3

What that is better I think is add a note that list the versions that are officially supported.

**Comment by jamisonroberts** [comment]
I believe this is why I cannot use with Angular 9 project.

**Comment by jaibatrik** [comment]
If I understand correctly, it is the version mentioned in the peer dependency which you guys are pointing to; isn't it?

**Comment by romelgomez** [comment]
Hi @jaibatrik 

Yes, 

https://github.com/abacritt/angularx-social-login/blob/master/package.json#L58

removing peerDependencies declaration resolve the issue. 

https://nodejs.org/es/blog/npm/peer-dependencies/

>"I only work when plugged in to version 1.2.x of my host package, so if you install me, be sure that it's alongside a compatible host." We call this relationship a peer dependency.

```
 "peerDependencies": {




   "@angular/core": "^8.2.10",


   "rxjs": "^6.5.3"


 },
```

The methods that are being used by this project are the same code from the old versions and it will not change with an decrepation note set for a long time in future versions.

**Comment by romelgomez** [comment]
Also I wanna reference other project that had the same issue, and solved it in this way:

https://github.com/livechat/angular-livechat/issues/25

https://github.com/livechat/angular-livechat/blob/master/package.json#L20

```
{
  "name": "angularx-social-login",
  "version": "1.2.7",
  "description": "Social login and authentication module for Angular 4 / 5. Supports authentication with Google and Facebook. Can be extended to other providers also.",
  "repository": {
    "type": "git",
    "url": "https://github.com/abacritt/angularx-social-login"
  },
  "author": {
    "name": "Jaibatrik Dutta",
    "email": "jaibatrik@gmail.com"
  },
  "keywords": [
    "angular",
    "angular4",
    "angular-social-login",
    "social-authentication",
    "social-login",
    "google-authentication",
    "facebook-authentication"
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/abacritt/angularx-social-login/issues"
  },
  "main": "./bundles/angularx-social-login.umd.js",
  "module": "./angularx-social-login.es5.js",
  "es2015": "./angularx-social-login.js",
  "typings": "./angularx-social-login.d.ts",
  "engines": {
    "node": ">= 6.9.0",
    "npm": ">= 3.0.0"
  },
  "scripts": {
    "clean": "rimraf out-tsc dist/*",
    "prebuild": "npm run clean",
    "build": "node build.js",
    "build-demo": "tsc -p src/demo/",
    "build-demo:watch": "tsc -p src/demo/ -w",
    "serve": "lite-server -c=bs-config.json",
    "prestart": "npm run build-demo",
    "start": "concurrently \"npm run build-demo:watch\" \"npm run serve\"",
    "build-test": "tsc -p src/lib/tsconfig.spec.json",
    "build-test:watch": "tsc -p src/lib/tsconfig.spec.json -w",
    "pretest": "npm run build-test",
    "test": "concurrently \"npm run build-test:watch\" \"karma start karma.conf.js\"",
    "coverage": "karma start karma-coverage.conf.js --single-run",
    "pretest:once": "npm run build-test",
    "test:once": "karma start karma.conf.js --single-run",
    "preintegration": "npm run build && cd integration && npm run clean && npm install",
    "integration": "npm run integration:aot && npm run integration:jit",
    "integration:jit": "cd integration && npm run e2e",
    "integration:aot": "cd integration && npm run e2e:aot",
    "lint": "tslint ./src/**/*.ts -t verbose",
    "release": "standard-version"
  },
  "peerDependencies": {
    "@angular/core": "^7.2.15",
    "rxjs": "^6.5.2",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular/common": "^7.2.15",
    "@angular/compiler": "^7.2.15",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/core": "^7.2.15",
    "@angular/platform-browser": "^7.2.15",
    "@angular/platform-browser-dynamic": "^7.2.15",
    "@types/jasmine": "3.3.12",
    "@types/node": "^12.0.1",
    "camelcase": "^5.3.1",
    "concurrently": "4.1.0",
    "core-js": "^3.0.1",
    "glob": "^7.1.4",
    "lite-server": "^2.4.0",
    "rimraf": "^2.6.3",
    "rollup": "^1.11.3",
    "rollup-plugin-commonjs": "^9.3.4",
    "rollup-plugin-node-resolve": "^4.2.4",
    "rollup-plugin-sourcemaps": "^0.4.2",
    "rollup-plugin-uglify": "^6.0.2",
    "rxjs": "^6.5.2",
    "standard-version": "^6.0.1",
    "systemjs": "^3.1.6",
    "tsickle": "^0.35.0",
    "tslint": "^5.16.0",
    "typescript": "^3.2.4",
    "zone.js": "^0.8.29"
  },
  "dependencies": {}
}

```

runing `ng update @angular/core @angular/cli`  raise this errros: 

```
Package "angularx-social-login" has an incompatible peer dependency to "@angular/core" (requires "^7.2.15" (extended), would install "9.0.1").
Package "angularx-social-login" has an incompatible peer dependency to "zone.js" (requires "^0.8.29", would install "0.10.2").
````

As I mention in the other issue:  

> Meaning that only theses version has the methods that need to correctly run the plugin. And this plugin use core not experimental stuff that are old as the v2 of angular.

Is not required mention peer dependency that a least you or we know that these methods or functions will have breaking changes in future versions.

**Comment by jaibatrik** [comment]
Decided to keep the peer dependencies. Peer dependencies just show an warning. They have nothing to do with actual code or the compatibility of the library with Angular versions. I have recently updated the library to be supported for Angular 9; it also uses Angular official docs recommended project structure now.

That being said, I still think that a compatibility table showing the compatibility between the library versions and Angular versions will still be helpful. Keeping this open for now to have the table added to the README.

**Comment by jaibatrik** [comment]
Updated the README.
