### ISSUE TITLE
Facebook sign-in

### ISSUE THREAD

**Issue by IhorVimmi** [abacritt/angularx-social-login#252]
Doesnt work facebook login

http://joxi.ru/DmBl0VyuJZ0O1A

**Comment by jaibatrik** [comment]
Kindly share a simple sample.

**Comment by IhorVimmi** [comment]
@jaibatrik try it in Opera Browser

**Comment by jaibatrik** [comment]
Opera desktop or Opera mobile? If mobile, which OS?

**Comment by jaibatrik** [comment]
Okay, Opera Windows looks like from your screenshot.

**Comment by jaibatrik** [comment]
Worked quite well for me - [screenshot](https://ibb.co/tzf70j2).
