### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by davidHaunschmied** [abacritt/angularx-social-login#255]
Hello!
angularx-social-login is an useful and easy-to-use tool! Thanks for maintaining this great OS project.
Unfortunately, it seems Angular 9 is not supported yet. Would be great if you guys could do that!
> npm WARN angularx-social-login@2.2.1 requires a peer of @angular/core@^8.2.10 but none is installed. You must install peer dependencies yourself.

Thanks,
David

**Comment by jaibatrik** [comment]
On it.

**Comment by jaibatrik** [comment]
Facing some problem related to Ivy. Not sure if this can be readily be updated.

**Comment by jasmeetappinventiv** [comment]
@jaibatrik any update on this?

**Comment by gianlucainnocente** [comment]
Same problem here

**Comment by tcd** [comment]
@jaibatrik What seems to be the issue?

**Comment by jaibatrik** [comment]
I am actually trying to follow the official guide to create libraries at https://angular.io/guide/creating-libraries which means many things have to be changed now. Also, not getting time from all the chores we have to do currently. Hoping to migrate the structure this week though.

**Comment by jaibatrik** [comment]
I am actually trying to follow the official guide to create libraries at https://angular.io/guide/creating-libraries which means many things have to be changed now. Also, not getting time from all the chores we have to do currently. Hoping to migrate the structure this week though.

**Comment by jaibatrik** [comment]
Update: I followed the library guide and was able to make it work. I just have to test it a bit a more and publish to npm. Hoping to do it in 2-3 days.

**Comment by jaibatrik** [comment]
I just published the changes to npm. Can you guys please check. It worked okay in local, and also appears to work on the demo site.

**Comment by jaibatrik** [comment]
The table for compatibility is still not addressed though :(
