### ISSUE TITLE
Google Scopes

### ISSUE THREAD

**Issue by AbdulYKI** [abacritt/angularx-social-login#257]
Hi guys,
I know you guys worked hard on this package and it is much appreciated, but I want to use it for google logins, and I specified a scope for birthdate and some others maybe in the future in the LogOpt object I have,just like you put it in the example, but the SocialUser object that returns doesn't have that extra info I wanted by adding the scope, could you please tell me how to get to that info, it is birthdate in my case.
again, much appreciated :D

**Comment by jaibatrik** [comment]
Closing this, will track the issue via #259
