### ISSUE TITLE
Receive null for user on the authState subscribe after refresh browser

### ISSUE THREAD

**Issue by faosl** [abacritt/angularx-social-login#258]
Hi, I'm receive null for user on the authState subscribe after signIn successfully and then refresh browser. I believe that it not suposed to be happend because the user don't request signOut.

**Comment by dontsu** [comment]
It is your application that has to handle the token and store it in cookies or somehow. This module just does the communication between your app and FB, nothing more.

**Comment by faosl** [comment]
Thanks @dontsu
