### ISSUE TITLE
How to getting birthday from method SignIn of GoogleLoginProvider?

### ISSUE THREAD

**Issue by faosl** [abacritt/angularx-social-login#259]
Hi, I'm currently passing https://www.googleapis.com/auth/user.birthday.read into the scope property of LoginOpt but I didn't find a way to recorvery birthday even user acept it, how could I do that?

**Comment by jaibatrik** [comment]
Feature not available in the library. Consider submitting a PR to add this.

**Comment by jaibatrik** [comment]
Let's keep this open; will dump rest of the properties in some other object.

**Comment by jaibatrik** [comment]
Added the response object in `SocialUser`. Use that to directly access the required property by checking the provider documentation.
