### ISSUE TITLE
I am unable to signout for facebook.... 

### ISSUE THREAD

**Issue by madhaviJakkam** [abacritt/angularx-social-login#26]
FacebookLoginProvider.prototype.signOut = function () {
        return new Promise(function (resolve, reject) {
            FB.logout(function (response) {
                resolve();
            });
        });
    };

**Comment by jaibatrik** [comment]
Are you seeing any error in the JS console?

**Comment by hutysta** [comment]
I have similar error. I see this `Refused to display 'https://www.facebook.com/home.php' in a frame because it set 'X-Frame-Options' to 'deny'.` error, when I try to log out. I am calling this.authService.signOut() method.

**Comment by jaibatrik** [comment]
Try to see if you have [these settings](https://stackoverflow.com/a/25577384/1086930) properly configured.

**Comment by hutysta** [comment]
This 
`Go to your facebook app console
Go to Settings -> Basic. In Site URL type your url, even if localhost. For example: http://localhost:3000`
has solved it. Now I am facing problem with callback to server. Should I callback server there? 
`
this.authService.authState.subscribe((user) => {
      if(user != null){
             //callback the server / login
      }
      else{
            //logout
     }
    });
`

or it should somehow be included in `AuthServiceConfig` object, which I pass to `socialloginmodule.initialize()` ?

Thanks for answer.

**Comment by jaibatrik** [comment]
What do you want to do in callback to server?

**Comment by hutysta** [comment]
I want to keep user info on the server. Or how do I know if the user is logged in? I need to send facebook authToken to the server, so I can get valid access token, which I will use for future requests. Or am I going with a wrong approach?

**Comment by deanstephens** [comment]
I am also having an issue with logging out. No errors are displayed and the logout function works correctly initially, but when the page is refreshed the user is logged in again using the same token they just logged out with.

**Comment by jaibatrik** [comment]
The solution is:

1. Go to your facebook app console
2. Go to Settings -> Basic. In Site URL type your url, even if localhost. For example: http://localhost:3000
3. Go to Settings -> Advanced. In Valid OAuth redirect URIs type your url, even if localhost. For example: http://localhost:3000

**Comment by vladyslavua** [comment]
Hi, I've done everything proposed above. However, when I call signout for my fb auth,
socialAuthService.authState gets null
But when I refresh browser, it still gets all user information.
What can be a reason?

**Comment by jaibatrik** [comment]
Seeing any error in console?

**Comment by vladyslavua** [comment]
@jaibatrik thanks for getting back to me. No errors at all. When I click "this.authService.signOut();", the listener
`this.authService.authState.subscribe((user) => {
      console.log(user);
    });`
outputs null, however if I refresh page, it starts outputting SocialUser, even though I didn't try to log in and there is nothing in the app which may cause automatic login after page refresh.

**Comment by yehia123** [comment]
Having issues testing Signout on localhost also.

**Comment by zawars** [comment]
Any lead on this issue?

**Comment by xErik** [comment]
**Solution Update 2019 with Angular 8**

Console errors and warnings, be gone:

- _cannot display FACEBOOK-BLA in hidden frame_
- _FB.login does not exist ..._
- _HTTP is not supported, use HTTPS ..._

Steps:

0. If installed, **pause** or **uninstall** Ghostery. Setting Ghostery to `trust localhost` will **not** work.
1. Run local app with `ng serve --ssl`
2. Go to your facebook app console
3. Go to _Settings -> Basic_ 
3.1. In _App Domains_ **only** enter `localhost`
3.2. In _Site URL_ **only** enter `https://localhost/`
4. Do **not** go the _Products-> Facebook Login -> Settings_ and do **not** change `Valid OAuth Redirect URIs` to `localhost`
