### ISSUE TITLE
Slow network & fast user problem: Cannot read property 'signIn' of undefined

### ISSUE THREAD

**Issue by grudus** [abacritt/angularx-social-login#260]
Hi!
I've found an error: when `AuthService.signIn` is called, but the login provider script is not loaded yet (e.g. slow network), the TypeError is thrown (because `_this.auth2` is not initialized at the moment):
![obraz](https://user-images.githubusercontent.com/18220458/77744911-a94bd000-701a-11ea-9385-786aaa2d9146.png)

The possible solution is to add some kind of `isReady()` function to check if the provider code is loaded

Angular version: ^6.0.2
angular4-social-login: ^1.1.1

**Comment by jaibatrik** [comment]
Hi, angular4-social-login is deprecated. Could you try using [angularx-social-login](https://www.npmjs.com/package/angularx-social-login) and check?
