### ISSUE TITLE
Facebook + gmail popup is blocked on mobile browser safari

### ISSUE THREAD

**Issue by logicappsource** [abacritt/angularx-social-login#261]
Desktop browser the user can enable the popup to be displayed. But on mobile safari

**Comment by gitalvininfo** [comment]
Any updates with this? I'm having the same issue. When I try to click the link of the app in fb browser, the fb dialog login is block. 
I already tried to debug it using chrome developer tools remote device however no error is shown.

**Comment by gitalvininfo** [comment]
@logicappsource does it only block in mobile safari browser? Other browsers does work in you ? Mine all browsers blocks the popup dialog of fb login

**Comment by NishanAdelanka** [comment]
If the popup blocker turned on It blocks on both iOS and Android browsers.

**Comment by jaibatrik** [comment]
Let's track this with #248
