### ISSUE TITLE
Angular 9: "ng build --prod" ERROR

### ISSUE THREAD

**Issue by petermarikit3QDigital** [abacritt/angularx-social-login#262]
It seems like on Angular v9.0.7, running `ng build --prod` with **angularx-social-login v2.2.1** produces the following error:

> Compiling angularx-social-login : es2015 as esm2015
92% chunk asset optimization LicenseWebpackPluginAn unhandled exception occurred: EISDIR: illegal operation on a directory, read

A temporary fix for this problem was to downgrade angular to **v8.2.14**, which required some parts of the angular application to be regressed back to a previous version. Hope this gets resolved soon and helps anyone trying to use this package with a new angular application.

**Comment by meghansh36** [comment]
Does disabling Ivy help? I was able to make my project work by disabling Ivy, I don't know if it will work during build mode or not but you can try

**Comment by petermarikit3QDigital** [comment]
@meghansh36 I havent tried disabling Ivy to fix the issue. I will keep this in mind and try it out when I have time, thanks!
