### ISSUE TITLE
Facebook login is blocked in FB mobile browser

### ISSUE THREAD

**Issue by gitalvininfo** [abacritt/angularx-social-login#263]
I've been experiencing a weird bug wherein the Facebook login dialog is block every time I click on the facebook login button using the fb mobile browser. 

The scenario is, I open facebook app in mobile then click on the app link then it redirects me to the login page and I click on the facebook login button the dialog loads for a while then it closes. However, if I use desktop browser there is no issue with facebook login it works. 

Here is my code for facebook login which is triggered by the user event which is button click

`signInwithFB() {
           this.authService.signIn(FacebookLoginProvider.PROVIDER_ID).then(res => {
			this._fbData = {
				firstname: res.firstName,
				lastname: res.lastName,
				email: res.email,
				fb_id: res.id,
				username: res.firstName + Math.floor(Math.random() * 9999999),
				type: 'fb'
			}
             });
}`

I've already debug the fb mobile browser using chrome remote device but the console displays no error at all.

Please let me know if I miss something. Thanks in advance. please reply

**Comment by gitalvininfo** [comment]
Anyone experiencing with this kind of issue same as mine ?

**Comment by NishanAdelanka** [comment]
make sure the mobile browser's popup blocker is turned off

**Comment by gitalvininfo** [comment]
im not using the browser like chrome firefox or edge in mobile. im using the in-app  facebook mobile browser to open my app.

**Comment by jaibatrik** [comment]
Please check how Facebook suggests handling it. This library just delegates the login functionality to Facebook's authentication JS library.

**Comment by josee666** [comment]
Maybe same problem here... FB auth doesn't work but only on some iphone. The user clic and i does nothing... It work fine on chrome (PC and mobile) but doens't work on iphone. I am not able to see the debug message on the iphone, i don't have a mac...
here the code: 
 ngOnInit() {
    this.authService.authState.subscribe(
      (user) => {
      this.user = user;
      this.loggedIn = (user != null);
      if (this.user !== null && typeof this.user.name !== 'undefined') {
        this.loginService.setUser(this.user, this.loggedIn);
        this.loginService.setLogFb(true);
        this.evLogin.emit('logOk');
      }
    },
    err => console.log('erreur init FB authentification!!:  ', err));

  }
  signInWithFB(): void {
    if (this.loginService.loggedAsAdmin) {
      this.onCheckLogOutAsAdmin();
    }
    try {
      this.authService.signIn(FacebookLoginProvider.PROVIDER_ID);
    }catch (err) {
        alert(err.message);
      }
    console.log('auth FB termine');
  }



The app is here: 
https://hammersystem.github.io/preferenceClient/

thank for help

**Comment by jaibatrik** [comment]
Let's track this with #248.

**Comment by gitalvininfo** [comment]
Hi. finally solved the problem.

Here is the my code for facebook login

`constructor() {
      this.authService.authState.subscribe((res) => {
			this.loggedIn = (res != null);
      });
}`

`signInWithFB() {
		if (this.loggedIn) {
			this.authService.authState.subscribe((res) => {
				this.loginUserFBMethod(res);
				return false;
			});

		} else {
			this.authService.signIn(FacebookLoginProvider.PROVIDER_ID).then(res => {
				console.log("res ", res);
				this.loginUserFBMethod(res);
			});
		}
	}
`

To repeat, the issue for me is that Facebook login dialog is blocked when I open my app through Facebook In-App browser (i.e the browser which Facebook app uses every time you open a link). 

So since I am already in the Facebook In-App browser, it is understood that I am already loggedIn.

So in the constructor, it checks if I am truly loggedin through the the authstate api of the library, if yes then set the `this.loggedIn` flag to `true.`

When I click the button Sign In with Facebook with a function `signInWithFB()` it checks for the boolean flag `this.loggedIn`. If so, I'll grab the info for that user then it needs to return `false` so that it will not continue execute to the else statement which in my case, solved the issue which blocks the dialog and do not redirect my app to dashboard.

The else statement here grab the user info when a successful login is established.

**Comment by jaibatrik** [comment]
@gitalvininfo Thanks for sharing the solution! Will share this in the active issue.

**Comment by mbvb1223** [comment]
humm, don't know why 
```
constructor() { this.authService.authState.subscribe((res) => { this.loggedIn = (res != null); }); }
```
this.loggedIn => return false 

even ` autoLogin: true,`
```
{
      provide: 'SocialAuthServiceConfig',
      useValue: {
        autoLogin: true,
        providers: [
          {
            id: GoogleLoginProvider.PROVIDER_ID,
            provider: new GoogleLoginProvider(environment.googleClientId),
          },
          {
            id: FacebookLoginProvider.PROVIDER_ID,
            provider: new FacebookLoginProvider(environment.facebookClientId),
          },
        ],
      } as SocialAuthServiceConfig,
    },
    ```
