### ISSUE TITLE
Problem with redirect_uti, spring boot

### ISSUE THREAD

**Issue by piotrsikorski6** [abacritt/angularx-social-login#265]
Hi,

I have the question regarding to redirect uri.

I added it to angular configuration file:

```
const googleLoginOptions: LoginOpt = {
    redirect_uri: 'http://localhost:3000/oauth2/redirect'
}

const config = new AuthServiceConfig([
    {
        id: GoogleLoginProvider.PROVIDER_ID,
        provider: new GoogleLoginProvider('XXX_Key', googleLoginOptions)
    },
]);
```

And that same redirect uri I put into yaml file on backend. With another library - f.e. react social login - it is working properly. With angular - I have positive feedback from google but redirect is not working. 

Anybody has a similar issue?

Kind regards

**Comment by jaibatrik** [comment]
@piotrsikorski6 This library does not handle OAuth for now. But I'll have a look.

**Comment by jaibatrik** [comment]
The problem is with popups I think, and we need to find a way to use the redirect method of authentication. Let's track this with #248.

**Comment by kamalkech** [comment]
@jaibatrik there is no way to callback on server side ??
