### ISSUE TITLE
 An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by Harikabzw** [abacritt/angularx-social-login#266]
I am trying to use angularx-social login in my angular7 project .I am using lazy loading . while running server I am getting the below error.

ERROR in node_modules/angularx-social-login/auth.service.d.ts(52,9): error TS108
6: An accessor cannot be declared in an ambient context.
node_modules/angularx-social-login/auth.service.d.ts(54,9): error TS1086: An acc
essor cannot be declared in an ambient context.

Here is my code

import { SocialLoginModule, AuthServiceConfig } from "angularx-social-login";
import { GoogleLoginProvider, FacebookLoginProvider } from "angularx-social-login";
export function getAuthServiceConfigs() {
  let config = new AuthServiceConfig(
      [
        {
          id: FacebookLoginProvider.PROVIDER_ID,
          provider: new FacebookLoginProvider("257537552322155")
        },
        {
          id: GoogleLoginProvider.PROVIDER_ID,
          provider: new GoogleLoginProvider("981626015364-s0otofiv4r6sf55dqker27o4cfeqs8ij.apps.googleusercontent.com")
        },
      ]
  );
  return config;
}
@NgModule({
  imports: [
    CommonModule,
    BasicLoginRoutingModule,
    SharedModule,
    SocialLoginModule
   
  ],
  declarations: [BasicLoginComponent],
  providers: [
    {
        provide: AuthServiceConfig,
        useFactory: getAuthServiceConfigs
      }

**Comment by ursedaniel** [comment]
i also have this issue...

**Comment by Dsantacruz** [comment]
I've

**Comment by ImFranQ** [comment]
Your module is imported in the app.module.ts?

Remove your Facebook ID and Google ID. Is not necesary.

**Comment by FatManiac** [comment]
I imported AuthService in app.module.ts, the error persist

**Comment by bkarv** [comment]
Same problem here in my Angular 8 project.

**Comment by ImFranQ** [comment]
upgrade to angular 9 
`ng update @angular/cli @angular/core`
or downgrade a version. it's work for me.

**Comment by razinj** [comment]
@ImFranQ what version did you downgrade to ?
Thanks in advance.

**Comment by jaibatrik** [comment]
Need to create a version compatibility table.

**Comment by singhaishwarya** [comment]
> @ImFranQ what version did you downgrade to ?
> Thanks in advance.

I downgraded it to @2.2.1...it worked for me.

**Comment by yashpalsingh11** [comment]
I also downgraded it to @2.2.1. It also worked for me. Thanks

**Comment by rajibhalder** [comment]
I also downgraded it to @2.2.1 for Angular 8 (npm install --save angularx-social-login@2.2.1) . It also worked for me. Thanks

**Comment by jaibatrik** [comment]
Added the information in CHANGELOG.
