### ISSUE TITLE
Reset Facebook auth_type Option

### ISSUE THREAD

**Issue by ewwwgiddings** [abacritt/angularx-social-login#270]
Does anyone know how to change the auth_type after it's initialized in the app.module?

I need to be able to set this option dynamically based on certain responses from the server.

Any help?

**Comment by ewwwgiddings** [comment]
I've tried passing in the right options to make it happen like this:
`this.socialAuthService.signIn(FacebookLoginProvider.PROVIDER_ID, this.fbLoginOptions)`

But the auth_state option has no effect on what happens.

**Comment by ewwwgiddings** [comment]
I'm attempting to re-ask for permissions as mentioned here:
https://developers.facebook.com/docs/facebook-login/web/permissions/#re-asking-declined-permissions

**Comment by ewwwgiddings** [comment]
Of note is that it does work if I initialize it with this value in the app.module but not if I reset it dynamically or in the component I need it in.

**Comment by jaibatrik** [comment]
Try passing the parameters as part of the `FacebookLoginProvider` constructor. There might be a bug with `signIn` function.

**Comment by jaibatrik** [comment]
Yeah, will fix it shortly.

**Comment by ewwwgiddings** [comment]
Yea, I had to do some rather complicated function to change it.

    for (const [index, element] of this.config.providers.entries()) {
      console.log(index, element);
      if (index === 'FACEBOOK') {
        // tslint:disable-next-line:no-string-literal
        element['opt']['auth_type'] = 'reauthorize';
      }
    }

So you will be allowing this to be passed into the `signIn` function soon?

**Comment by jaibatrik** [comment]
Yeah, the new version is almost ready. I'll probably be releasing it to npm today itself. But version 3.0.0 will actually not be backward compatible. The `AuthService` class is totally refactored and renamed. I don't think I'll keep maintaining 2.x versions in separate branch. Migrating will probably not be too much of work though.

**Comment by ewwwgiddings** [comment]
By backward compatible you mean it'll only work with Angular 9? Makes sense. Ivy as a default has done that to a lot of libraries it seems.

That's a good decision to rename it. That way it doesn't conflict with the common AuthService name people use for the app's auth service.

Thanks for fixing it and the library :)

**Comment by jaibatrik** [comment]
Just published the new version in npm. Closing this issue. Thanks for reporting!
