### ISSUE TITLE
How can I know if I a user is logged in? Is there access to FB.getLoginStatus()

### ISSUE THREAD

**Issue by xtianus79** [abacritt/angularx-social-login#271]
What is the mechanism I already know the user is logged into the service? What can I acquire like the FB.getLoginStatus() to know this. Can you give an example?

**Comment by jaibatrik** [comment]
When the library initializes, it calls `FB.getLoginStatus()` for you. If an user is returned from the `FB` API, it does a `next` to the `authState` with the user data; so, if you have subscribed to `authState`, you get the user information in your subscriber. There is no way of manually triggering this though at this moment. Does this answer you question?

PS - I am currently in the process of refactoring the library. I'll give it a thought.

**Comment by xtianus79** [comment]
Thanks for the reply.  I think I can get what I need from the cookie. I will start another post which should help me better.

**Comment by jaibatrik** [comment]
Keeping this open; providing a `getLoginStatus()` to manually get the login status might be useful if we disable auto-login by default.

**Comment by JGMAGNO** [comment]
Hello how was it? is getLoginStatus() available now?

**Comment by jaibatrik** [comment]
Sorry, haven't been able to decide on the signature of the method till now. Will work on it.
