### ISSUE TITLE
Add expiration to User entity

### ISSUE THREAD

**Issue by afgonzal** [abacritt/angularx-social-login#274]
Need to retrieve expiration attribute and store it inside the User to validate when the token has expired.

**Comment by afgonzal** [comment]
Already have change for this, just 3 lines of code

**Comment by jaibatrik** [comment]
You can raise a PR, we can discuss if the changes fit this library there.

**Comment by afgonzal** [comment]
don't have permissions to push, how to I get contributor role?

**Comment by jaibatrik** [comment]
May be you can post the change here in the issue.

**Comment by afgonzal** [comment]
Hi

in the google-login-provider.ts
I add this line twice (at getLoginStatus and signIn methods)
**let expiration = this.auth2.currentUser.get().getAuthResponse(true).expires_at;**

and in user.ts, I added a property to SocialUser, 
**expiration: number;**

I can checkout the fb login, to see if has expiration, and keep consitency.

regards

**Comment by jaibatrik** [comment]
I think the changes look good. You can submit a PR. Check if FB supports it. The expiration field in `SocialUser` will probably need to be optional.

**Comment by jaibatrik** [comment]
Also, there is an object called `google` in `SocialUser`. Check if the birthday comes up inside that object.

**Comment by afgonzal** [comment]
still no permissions to push branch.
I checked FB and :
at facebook-login-provider.ts add these lines to  getLoginStatus and signIn methods
**user.expiration = Date.now() + authResponse.expiresIn;**

**Comment by jaibatrik** [comment]
I'll take care of it then. Meanwhile you can fork the repository and build the library and use temporarily.

**Comment by vishal8802** [comment]
I can't find any google-login-provider.ts file ( have google-login-provider.d.ts or google-login-provider.js ) .
Can anyone please help where to make changes

**Comment by vishal8802** [comment]
i can't find these files. can anybody help

**Comment by jaibatrik** [comment]
Added the response object in `SocialUser`. Use that to directly access the required property by checking the provider documentation.
