### ISSUE TITLE
Is response type able to handle settings to activate code and token. Upon login I notice something weird. 

### ISSUE THREAD

**Issue by xtianus79** [abacritt/angularx-social-login#275]
I included the documentation from facebook below. 

So the problem right now I am relying on Facebook's cookie to give me response of the user login. I can very whether they are logged in or not by that cookie. 

The problem with the initial response is that it doesn't have the access token, not at first anyway.  If I refresh it comes right away and i've let my computer go to sleep overtime and I notice when I come back without refresh it has a different cookie that has a new token. I don't know what the time limit is on that refresh token. 

There are 2 ways to mitigate this.  

1. I could always exchange the code for an access token (not sure which is more desirable). If I did end up going this route I would never way the access token to be included in the cookie as I would  just always exchange it. <<< could be the best solution. But the question begs How do i prevent the access token from every coming back? 

2. I could use the parameter below for code%20token and always assure that both are returned. Then it doesn't matter if access token is returned because it will always be returned. 

The question is, am I able to control the type of response with the auth fb parameters? eventually the same would be needed for google too. 

[https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/#checktoken](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/#checktoken)
> Exchanging Code for an Access Token
> To get an access token, make an HTTP GET request to the following OAuth endpoint:

> response_type. Determines whether the response data included when the redirect back to the app occurs is in URL parameters or fragments. See the Confirming Identity section to choose which type your app should use. This can be one of:
> code. Response data is included as URL parameters and contains code parameter (an encrypted string unique to each login request). This is the default behavior if this parameter is not specified. It's most useful when your server will be handling the token.
> token. Response data is included as a URL fragment and contains an access token. Desktop apps must use this setting for response_type. This is most useful when the client will be handling the token.
> code%20token. Response data is included as a URL fragment and contains both an access token and the code parameter.
> granted_scopes. Returns a comma-separated list of all Permissions granted to the app by the user at the time of login. Can be combined with other response_type values. When combined with token, response data is included as a URL fragment, otherwise included as a URL parameter.

**Comment by jaibatrik** [comment]
This library is a wrapper around Facebook's JS authentication library - https://developers.facebook.com/docs/facebook-login/web/

You can check their documentation to see if passing any parameter solves your problem.

As of now, I am closing this issue because I feel there's nothing this library can do apart from passing parameters you pass to us to Facebook. Feel free to reopen if that is not the case.
