### ISSUE TITLE
Is there any other providers? Like Instagram, LinkedIn...?

### ISSUE THREAD

**Issue by wellingtonfoz** [abacritt/angularx-social-login#277]
Hi,

Is there any other providers? Like Instagram, LinkedIn...?

**Comment by anushreenk** [comment]
Same question from me what are the different logins we can accomplish with this component other than google and facebook?

**Comment by jaibatrik** [comment]
There will be an provider for Amazon shortly. You can also create your own provider and plugin to the library. Since LinkedIn moved to OAuth, we dropped support for them; but we are now considering if some OAuth based libraries can be supported. Not sure if it will need any major design change.
