### ISSUE TITLE
Facebook: caching of email/phone

### ISSUE THREAD

**Issue by mletynski** [abacritt/angularx-social-login#278]
1. Go to https://abacritt.github.io/angularx-social-login/
2. Login with your fb email/password
3. Click sign out
4. Login but this time make typo in email and put proper password
5. You are successfully logged in

This dialog is somehow caching proper email/phone. Any hint how to fix this ?

**Comment by jaibatrik** [comment]
This appears to be how Facebook login behaves, not an issue with the library.

https://security.stackexchange.com/questions/214814/why-can-i-log-in-to-my-facebook-account-with-a-misspelled-email-password
https://www.howtogeek.com/402761/facebook-fudges-your-password-for-your-convenience/
