### ISSUE TITLE
The method FB.login can no longer be called from http pages.

### ISSUE THREAD

**Issue by mgonzaga1990** [abacritt/angularx-social-login#281]
I'm getting the error 

**The method FB.login can no longer be called from http pages. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/**

I just follow the basic implementation of the library.

![image](https://user-images.githubusercontent.com/21145779/85951279-b7e8b100-b994-11ea-85a4-9573052a153d.png)

![image](https://user-images.githubusercontent.com/21145779/85951299-dcdd2400-b994-11ea-83b0-5c6c50e0a92f.png)
![image](https://user-images.githubusercontent.com/21145779/85951308-ef575d80-b994-11ea-8b2c-96281b12b078.png)

I have the latest version of the library.

Thanks

**Comment by jaibatrik** [comment]
I think you should be able to resolve the issue by following this - https://stackoverflow.com/a/55938978/1086930

**Comment by kamalkech** [comment]
@jaibatrik but i get same error if have switch app facebook to dev mode !!

**Comment by Steven-zion** [comment]
Am getting same err when using react-facebook. here is what fixed my issue - on the meta for developers dashboard i clicked the top left corner dropdown and created a test up version of my app and then i replaced my appId with the one of a test app, it worked i got an accessToken. it seems the it wont work with the production app unless you create a test app
