### ISSUE TITLE
AuthServiceConfig module is not there in angularx-social-login

### ISSUE THREAD

**Issue by ktezi** [abacritt/angularx-social-login#282]
import { SocialLoginModule, SocialAuthServiceConfig , AuthServiceConfig
![Screenshot (39)](https://user-images.githubusercontent.com/56465626/86259548-c7a50700-bbd9-11ea-8ec9-3856e8ac508b.png)
 } from 'angularx-social-login';
import {
  GoogleLoginProvider,
  FacebookLoginProvider,
  AmazonLoginProvider,
} from 'angularx-social-login';

const config = new AuthServiceConfig([
  {
    id: GoogleLoginProvider.PROVIDER_ID,
    provider: new GoogleLoginProvider('Id')
  },
  // {
  //   id: FacebookLoginProvider.PROVIDER_ID,
  //   provider: new FacebookLoginProvider('561602290896109')
  // },
  // {
  //   id: LinkedInLoginProvider.PROVIDER_ID,
  //   provider: new LinkedInLoginProvider("78iqy5cu2e1fgr")
  // }
]);

export function provideConfig() {
  return config;
}
@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    SocialLoginComponent,
    AdminComponent,
    ManagePassengerComponent,
    AncillaryServicesComponent,
    FlightListComponent,
    routingComponents,
    ListAllPassengersComponent
  ],
  imports: [
    SocialLoginModule,
    MaterialModule,
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    BrowserAnimationsModule,
    StoreModule.forRoot({}, {})
  ],
  providers: [
    {
      provide: 'SocialAuthServiceConfig',
      useValue: {
        autoLogin: false,
        providers: [
          {
            id: GoogleLoginProvider.PROVIDER_ID,
            provider: new GoogleLoginProvider(
             'client-Id'
            ),
          },
          {
            id: FacebookLoginProvider.PROVIDER_ID,
            provider: new FacebookLoginProvider(
             'client-Id'),
          },
          {
            id: AmazonLoginProvider.PROVIDER_ID,
            provider: new AmazonLoginProvider(
              'client-Id'
            ),
          },
        ],
      } as SocialAuthServiceConfig,
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
 }

**Comment by jaibatrik** [comment]
With the release of v3.0.0, we changed the names of some classes and interfaces, and slightly changed how the library is initialized. Please refer to the [README](https://github.com/abacritt/angularx-social-login).

**Comment by ktezi** [comment]
@jaibatrik this will support angular 10.0.2 latest version ?

**Comment by jaibatrik** [comment]
Oh, version 10 just released, right? Haven't yet added support for that.

**Comment by jaibatrik** [comment]
The changes for v10 are merged in the repository. Yet to publish in npm.

**Comment by sahdev007** [comment]
AuthServiceConfig has been replaced with SocialAuthServiceConfig in the new version.
