### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by UrchitaK** [abacritt/angularx-social-login#283]
I get the following error when trying to run the project
![image](https://user-images.githubusercontent.com/67736735/86343099-215b0f00-bc76-11ea-922e-eb046a13a782.png)
Angular Version 8
"angularx-social-login": "^3.1.1"

**Comment by jaibatrik** [comment]
Check this - https://github.com/abacritt/angularx-social-login/issues/266#issuecomment-626594538. Reopen if it does not resolve the problem. Note that the class / interface names and the code to initialize the library was a bit different in v2. Refer to the old [README](https://github.com/abacritt/angularx-social-login/blob/728bb892b4fbfafe1e349483874772e20de91342/README.MD).
