### ISSUE TITLE
if autoLogin and user not logged in, authState never ticks

### ISSUE THREAD

**Issue by mokipedia** [abacritt/angularx-social-login#284]
Hi,
previous to 3.x, after initialization the authState would tick with eigher a user obj (if logged in) or null of no provider finds a valid login.
Since 3.x if autoLogin is enabled and the user is not logged in on applicatication start, authState never ticks.
This is a problem for authGuards, that need to check if a user is loggedin or not - as the authState never ticks, the navigation currently never finishes.
Is there a way to find out if all providers are done initializing but no valid login was found?

**Comment by jaibatrik** [comment]
Right, makes sense; will make changes to send out null if `autoLogin` is `true` and no user found.

**Comment by jaibatrik** [comment]
Thanks for the PR, checking!

**Comment by mokipedia** [comment]
found a bug in my code, fixed it
