### ISSUE TITLE
invalid version specified during Fb login

### ISSUE THREAD

**Issue by abhiaat** [abacritt/angularx-social-login#289]
"init not called with valid version" message is received during facebook login.
Everything was working well when I was using Angular 8.x and angularx-social-login 1.2.7.

After ugrading to angular 9.x
I am using "angularx-social-login": "^3.2.0"
and I have started receiving this error.

**Comment by jaibatrik** [comment]
Check the [`FacebookLoginProvider`](https://github.com/abacritt/angularx-social-login/blob/master/projects/lib/src/providers/facebook-login-provider.ts) constructor. Try putting different values for the version as discussed in answers like [this one](https://stackoverflow.com/questions/46348105/facebook-api-invalid-version-specified).

**Comment by abhiaat** [comment]
Thanks. It did work. I had to add version to the `initOptions` in constructor. Sample code is given below for anyone else who faces the issue.

```
const fbLoginOptions = {
  scope: 'pages_messaging,pages_messaging_subscriptions,email,pages_show_list,manage_pages',
  return_scopes: true,
  enable_profile_selector: true,
  version: "v2.11" // this line added.
}
```
