### ISSUE TITLE
How can i get token expiry date?

### ISSUE THREAD

**Issue by vishal8802** [abacritt/angularx-social-login#293]

**Comment by jaibatrik** [comment]
I guess, we have to enhance the `SocialUser` class a bit to address these issue. I'll try to take care of this shortly.

**Comment by afgonzal** [comment]
there´s already another thread here
[https://github.com/abacritt/angularx-social-login/issues/274](https://github.com/abacritt/angularx-social-login/issues/274)
with the solution

**Comment by jaibatrik** [comment]
duplicate of #274

**Comment by jaibatrik** [comment]
Duplicate of #274
