### ISSUE TITLE
Not having support for ivy

### ISSUE THREAD

**Issue by Metagogy** [abacritt/angularx-social-login#294]
Hi 

 i am getting an error while integrating this plugin with my application.

 This likely means that the library (angularx-social-login) which declares SocialLoginModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking 
with the library's authors to see if the library is expected to be compatible with Ivy.

can anyone resolve this issue.

i am using angular 9 and 3.2.0 of plugin version

**Comment by jaibatrik** [comment]
This is expected as per guidelines from Angular, check https://angular.io/guide/creating-libraries#publishing-your-library

If you want to use this with Ivy, you probably have to manually clone the repo, build and copy dist files. Not sure if there's a better way.

**Comment by Rolandisimo** [comment]
Why would the library be made not compatible with Ivy?

**Comment by jaibatrik** [comment]
Keeping alive for now. This can probably serve as a periodic reminder to check if anything changed from Angular and if we need to update anything from our side.

**Comment by drdreo** [comment]
Is this still a thing?

**Comment by jaibatrik** [comment]
Yeah, just checked the documentation. It still is.

**Comment by lookMyCode** [comment]
I have this problem too. Angular 9.0.5, angularx-social-login 3.5.4
angularx-social-login 3.5.5 tried too

**Comment by jaibatrik** [comment]
Looks like Angular has published some new guidelines. It'd be great if somebody can check them and suggest a fix. Otherwise, I'll get back to it when I get some time.

**Comment by sateesh9417** [comment]
This likely means that the library (ng4-social-login) which declares SocialLoginModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

@@@     i am getting error msg like this can any one know pls respond me!!!!!!!!!!!

**Comment by Heatmanofurioso** [comment]
Closing this, as the project is currently running Angular V13
