### ISSUE TITLE
No exported member

### ISSUE THREAD

**Issue by robertrandallphillips** [abacritt/angularx-social-login#295]
I'm testing ng 10.0.3 with "angularx-social-login": "^3.2.0". It seems to be working but IntelliJ is giving me these warnings:

TS2305: Module '"../../../node_modules/angularx-social-login/angularx-social-login"' has no exported member 'SocialAuthService'.

TS2305: Module '"../../node_modules/angularx-social-login/angularx-social-login"' has no exported member 'SocialAuthServiceConfig'.

**Comment by jaibatrik** [comment]
Probably not an issue with the library itself. We are following the official guide for creating libraries in Angular and the build process is completely from Angular (along with the structure of distribution files). Not sure what is going on with Idea.

**Comment by webcat12345** [comment]
I am having the same issue. Here goes the screenshot.

![image](https://user-images.githubusercontent.com/19761422/91156232-e54e9400-e691-11ea-8bec-f36076815154.png)

**Comment by webcat12345** [comment]
No lint error and AOT compilation error. Not sure if it is IDE problem or not...

**Comment by mr-perfectcoder** [comment]
Module '"../../../node_modules/angularx-social-login/angularx-social-login"' has no exported member 'SocialAuthService'.Module '"../../../node_modules/angularx-social-login/angularx-social-login"' has no exported member 'SocialAuthServiceConfig'.

![image](https://user-images.githubusercontent.com/53580566/93991773-47420c80-fdaa-11ea-8e1f-d6c8f3374b04.png)
