### ISSUE TITLE
Social login library not working for my angular 8

### ISSUE THREAD

**Issue by xxholyChalicexx** [abacritt/angularx-social-login#296]
So it was working fine in my angular 7 but after i upgraded to angular 8 its not compiling and showing me error. Here is the error i get when i do "ng serve":
`ERROR in node_modules/angularx-social-login/auth.service.d.ts(52,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angularx-social-login/auth.service.d.ts(54,9): error TS1086: An accessor cannot be declared in an ambient context.`

### package.json file

> {
  "name": "myproj",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/material": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/platform-server": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@r3droger/windowref": "0.0.1",
    "@types/selectize": "^0.12.34",
    "angular-bootstrap-md": "^7.5.3",
    "angular-google-charts": "^1.1.4",
    "angular-plotly.js": "^2.0.0",
    "angularx-social-login": "^2.2.1",
    "bulma": "^0.8.0",
    "chart.js": "^2.9.2",
    "core-js": "^3.1.3",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "highcharts": "^8.1.2",
    "highcharts-angular": "^2.4.0",
    "lightweight-charts": "^3.1.2",
    "ng-selectize": "^1.1.3",
    "ng2-charts": "^2.3.0",
    "ng2-search-filter": "^0.5.1",
    "plotly.js": "^1.54.6",
    "rxjs": "^6.5.0",
    "rxjs-compat": "^6.0.0",
    "sweetalert2": "^8.13.0",
    "tslib": "^1.9.0",
    "window": "^4.2.6",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^9.2.0",
    "@angular-devkit/build-angular": "^0.800.0",
    "@angular/cli": "^8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@types/jasmine": "^3.5.11",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.31",
    "@types/node": "^14.0.23",
    "brotli-webpack-plugin": "^1.1.0",
    "codelyzer": "^6.0.0",
    "compression-webpack-plugin": "^4.0.0",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^5.0.2",
    "karma": "^5.1.0",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "^3.3.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "^7.0.0",
    "rxjs-tslint": "^0.1.8",
    "sass-loader": "^7.1.0",
    "ts-node": "~7.0.0",
    "tslint": "^6.1.2",
    "typescript": "~3.4.5"
  }
}

**Comment by jaibatrik** [comment]
What's your TypeScript version? Does it fall under the Angular recommended version range?

**Comment by xxholyChalicexx** [comment]
yeap it falls under the recommended version range.

**Comment by jaibatrik** [comment]
Can you check #266 to see if any of the suggestions help you?

**Comment by SHUBHAMDAVE001** [comment]
Is there any chance to see what iframe do when auto login call.
because of which google login button is not working in some scenario.

Working fine when not loggedIn.
