### ISSUE TITLE
how to avoid sso login after logout

### ISSUE THREAD

**Issue by LSzelecsenyi** [abacritt/angularx-social-login#300]
After logging out with
`this.socialAuthService.signOut();`
the starting page is loaded and the ssoLogin functionality signs the user back again. I've read somewhere if I call the signOut() method with paramter true
`this.socialAuthService.signOut(true);`
then the sso login won't happen.. but it does.
my sso login code, which runs in oninit:

>      socialSSOLogin() {
>            this.socialAuthStateSubscription = this.socialAuthService.authState.subscribe((socialUser: SocialUser) => {
>                  if (!this.pendingSocialLogin) {   // to avoid double social media connect when user clicks join with fb/google
>                        if (socialUser) {
>                              let registrationRequest: RegistrationRequest;
>                              if (socialUser.provider === 'GOOGLE') {
>                                    registrationRequest = this.setGoogleLoginData(socialUser);
>                              }
>                              else if (socialUser.provider === 'FACEBOOK') {
>                                    registrationRequest = this.setFbLoginData(socialUser);
>                              }
>                              this.socialLogin(registrationRequest).subscribe(response => {
>                                    this.socialUser = socialUser;
>                                    this.loginCallback(response, true, true);
>                              });
>                        }
>                 }
>            });
>      }

How can I avoid this? tia

**Comment by jaibatrik** [comment]
Have you checked the `autoLogin` parameter in `SocialAuthServiceConfig`? Does that help?

**Comment by LSzelecsenyi** [comment]
@jaibatrik thank you for your answer! Solved it, something stupid was the cause.. 
`this.socialAuthService.signOut(true);` works well

**Comment by mkariti** [comment]
@LSzelecsenyi Im facing the same issue. Any idea on why this might happen?
Thanks

**Comment by LSzelecsenyi** [comment]
@mkariti in my case calling the signOut() method was inside an if clause which's condition did not met, so the call did not happen... I don't even have to call it with parameter true it works well, and the sso login does not happen after logout. Actually calling it with parameter true removes the application from the user's social account. 
 I suggest check everything around the signOut() call.

**Comment by mkariti** [comment]
@LSzelecsenyi Thanks for the quick reply. Will have a second look.
