### ISSUE TITLE
Lost on how to persist between page loads

### ISSUE THREAD

**Issue by shamusschubert** [abacritt/angularx-social-login#302]
This all seems to work great.  However hitting a page refresh in Angular 10 app I seem to immediately lose my login.

I build the call to Google login from my navbar/toolbar and that works, but as soon as I hit refresh the login is gone.

How are you persisting in Angular?

**Comment by jaibatrik** [comment]
Try using the `autoLogin` property in `SocialAuthServiceConfig`. Re-open if that does not work.

**Comment by gyancarlodasilva** [comment]
Similar situation here, i'm using autoLogin:  true
![image](https://user-images.githubusercontent.com/6933051/89225491-a9ec0880-d5b0-11ea-8f2d-11405f18b8e4.png)

I have a singIn button on my header.
![image](https://user-images.githubusercontent.com/6933051/89225525-b6706100-d5b0-11ea-9f22-5c6916e44adb.png)
![image](https://user-images.githubusercontent.com/6933051/89225645-ecade080-d5b0-11ea-87ba-f559dcdea711.png)
Shows my user info after login, if I refresh the page, my connection persists.
![image](https://user-images.githubusercontent.com/6933051/89225668-f6cfdf00-d5b0-11ea-99a9-fbc77c8e3cc8.png)

But when I click in a iten menu to go to another page, I lose my user info.
![image](https://user-images.githubusercontent.com/6933051/89225745-1c5ce880-d5b1-11ea-9722-5021fc96d9ae.png)

![image](https://user-images.githubusercontent.com/6933051/89226953-38618980-d5b3-11ea-9236-72174ac90d89.png)

I'm monitoring the user info every 1500 ms to see it state.
![image](https://user-images.githubusercontent.com/6933051/89226046-a442f280-d5b1-11ea-9364-e7e3bb89606a.png)
In red my infos, in blue, moments later when I clicked in menu iten returns null value.
![image](https://user-images.githubusercontent.com/6933051/89225931-7493ea80-d5b1-11ea-999f-b8f3d01ca61a.png)

Can you help me?

**Comment by degroundshaker** [comment]
Same problem here. On page refresh, login state is lost, in-spite of `autoLogin` value set to true.
