### ISSUE TITLE
LoginOpt lost in newest version

### ISSUE THREAD

**Issue by piotrsikorski6** [abacritt/angularx-social-login#305]
Hi,

In the newest version of Your package (3.2.1) I can't fin LoginOpt object...

**Comment by jaibatrik** [comment]
Yeah, pass a simple JS object. We have removed the interface.

**Comment by webcat12345** [comment]
Could you please let us know what's the reason for removing that interface?

**Comment by webcat12345** [comment]
And document says that interface and same to another class as well.

![image](https://user-images.githubusercontent.com/19761422/91156680-6c037100-e692-11ea-8a57-a3d028df6c60.png)

It's just confusing. The document is obviously not up-to-dated.

**Comment by jaibatrik** [comment]
> Could you please let us know what's the reason for removing that interface?

Because the options are so varied across providers, I did not think they made a logical grouping. They keep on changing, and the interface needed update whenever a new provider is added or removed. That is not the point of this library.

**Comment by jaibatrik** [comment]
Reopened to update the docs.

**Comment by libertyjayne** [comment]
@jaibatrik, are you all looking for contributors? I'm looking for an open-source project and this issue seems like a good 'first issue'.

**Comment by jaibatrik** [comment]
Updated the docs.

**Comment by jaibatrik** [comment]
@libertyjayne Thanks for your interest! You can pick up any of the open issues where a PR is welcome. Check for the "help wanted" label or a comment indicating so.
