### ISSUE TITLE
In which file in angular should the scopes be initialized?

### ISSUE THREAD

**Issue by merinann01** [abacritt/angularx-social-login#312]
const googleLoginOptions: LoginOpt = {
  scope: 'profile email'
}; // https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauth2clientconfig
 
let config = new AuthServiceConfig([
  {
    id: GoogleLoginProvider.PROVIDER_ID,
    provider: new GoogleLoginProvider("Google-OAuth-Client-Id", googleLoginOptions)
  },
  {
    id: FacebookLoginProvider.PROVIDER_ID,
    provider: new FacebookLoginProvider("Facebook-App-Id", fbLoginOptions)
  }
]);

**Comment by alexp25** [comment]
I have the same question. Where do I create the login providers with "Google-OAuth-Client-Id"/"Facebook-App-Id"? Also, I cannot create them as in the example (in the app module) as in my case, these ids are loaded from the server.
