### ISSUE TITLE
Please make "providers" in SocialAuthService readable

### ISSUE THREAD

**Issue by elementalPRESS** [abacritt/angularx-social-login#313]
I need to know which or how many providers have been registered. Here I found `providers` in `SocialAuthService`. Unfortunately this property is read-only. So please can you make it public or how can I get a list of providers?

Thx in advance,
Lars

**Comment by jaibatrik** [comment]
Can you please let us know your use case for better understanding?

**Comment by elementalPRESS** [comment]
> Can you please let us know your use case for better understanding?

Typically, I use always Facebook and Google providers. But depending on some environment variables, e.g. hostname etc. sometimes the Google provider is used, only. Now later in my UI I need to know how many providers have been activated. In previous versions I simply used `this.socialAuthServiceConfig.providers.size`. But now this is not a public var anymore :-(

Of course I could implement my own service which returns me the size but this is would be a big overhead for just one value. So it would be great if you could make it public.

**Comment by jaibatrik** [comment]
You can depend on the `SocialAuthServiceConfig` object that you are initializing the `SocialLoginModule` with. Put the object in a reusable module or global variable or something similar. Wouldn't that work?

**Comment by elementalPRESS** [comment]
> You can depend on the `SocialAuthServiceConfig` object that you are initializing the `SocialLoginModule` with. Put the object in a reusable module or global variable or something similar. Wouldn't that work?

Well, there are several more or less complicated work-arounds that would work, but I'm asking myself (from a programmers perspective) why the content of the `SocialLoginModule` is not readable anymore. So, why is it necessary to protect an object that is created by myself?

**Comment by jaibatrik** [comment]
Okay, I don't really see anything against it. A getter would be fine probably. Would you care to submit a PR?

**Comment by elementalPRESS** [comment]
> Okay, I don't really see anything against it. A getter would be fine probably. Would you care to submit a PR?

I would do it if I knew how to do... I never did it before
