### ISSUE TITLE
Account select window not opened in Electron

### ISSUE THREAD

**Issue by Rob195-ux** [abacritt/angularx-social-login#315]
I'm trying to use this package in a Angular + Electron hybrid application. The problem is when the this.googleAuthService.signIn(GoogleLoginProvider.PROVIDER_ID).then(() => {...} function is called the execution stops and it does not do anything.

I'm presuming that this is because it cannot open an Electron window? Can i configure it to work with Electron as well?
What have i tried so far:
- app.userAgentFallback = 'Chrome';
- and mainWindow.loadURL(indexURL, {userAgent: 'Chrome'});

but it did not help my case.

Any help would be appreciated!

**Comment by jaibatrik** [comment]
Yeah, this is most likely because we don't use the OAuth flow. This is why there is problem with making it work with PWAs as well. I think the solution would be to make this library work with OAuth flow; but I am not really getting time to work on such fundamental changes.

**Comment by Rob195-ux** [comment]
I understand, thank you.
Then i will use a separate OAuth flow for this.
