### ISSUE TITLE
Adding additional Linkedin Login provider issue

### ISSUE THREAD

**Issue by jitangupta** [abacritt/angularx-social-login#317]
I am trying to add [LinkedinLoginProvider](https://github.com/abacritt/angularx-social-login/blob/33860917e1/src/lib/src/providers/linkedIn-login-provider.ts) to my angular app but it's throwing error
![image](https://user-images.githubusercontent.com/11292363/93663323-b951e300-fa84-11ea-9f2e-34cf18da9a7a.png)

Environment Details:
Angular: 8.2.14
angularx-social-login: 2.2.1

I have created a wrapper module for adding LinkedProviderDetails
![image](https://user-images.githubusercontent.com/11292363/93663361-046bf600-fa85-11ea-96cd-1f3e1883bd1e.png)

have used the same code provided [here](https://github.com/abacritt/angularx-social-login/blob/33860917e1/src/lib/src/providers/linkedIn-login-provider.ts).
and here are other details:
`SocialLoginWrapperModule `
```
@NgModule({
  declarations: [],
  imports: [
    CommonModule
  ]
})
export class SocialLoginWrapperModule {

  public static initialize(config: AuthServiceConfig): ModuleWithProviders {
    return {
      ngModule: SocialLoginWrapperModule,
      providers: [
        { provide: AuthServiceConfig, useFactory: provideConfig }
      ]
    };
  }
}
```
`AppModule`
```
import { provideConfig } from './shared/modules/social-login-wrapper/social-login-config';
import { SocialLoginWrapperModule } from './shared/modules/social-login-wrapper/social-login-wrapper.module';

@NgModule({
  declarations: [
   ...
  ],
  imports: [
    ..., SocialLoginModule, SocialLoginWrapperModule,
  ],
  exports: [...],
  providers: [
   ...,
    { provide: AuthServiceConfig, useFactory: provideConfig }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
is this possible to add more login providers by extending `BaseLoginProvider` class?

**Comment by jaibatrik** [comment]
The code you are trying to use won't work now. LinkedIn stopped supporting client-based auth library. That's why we removed the LinkedIn provider in first place.
