### ISSUE TITLE
Facebook custom scope on login not working

### ISSUE THREAD

**Issue by renang** [abacritt/angularx-social-login#321]
I'm specifying scopes on login, but login ignores it. It only works when specified in app.module.

loginFacebook() {
    this.socialAuthService.signIn(FacebookLoginProvider.PROVIDER_ID, {
      scope: 'pages_read_engagement',
      return_scopes: true,
      enable_profile_selector: true
    }).catch(ex => console.log(ex));
  }

**Comment by jaibatrik** [comment]
Check the code at https://github.com/abacritt/angularx-social-login/blob/61b9a854e1ba4b33dd152379e7943f3868a466f2/projects/lib/src/providers/facebook-login-provider.ts#L75

It should take into account the options passed. If you feel there's a bug, you are welcome to suggest a fix / raise a pull request.
