### ISSUE TITLE
Locale for facebook login

### ISSUE THREAD

**Issue by d-borys** [abacritt/angularx-social-login#323]
Hi, is there a way to set locale for facebook login dialog? I need Polish language, but anytime I press login button it shows me English version of the dialog.

**Comment by jaibatrik** [comment]
![image](https://user-images.githubusercontent.com/1858403/94367278-4b985d80-00fb-11eb-84d7-97d5d7b31b4f.png)

Pass the locale as part of the `initOptions`.
