### ISSUE TITLE
VK login provider

### ISSUE THREAD

**Issue by petrovich2k** [abacritt/angularx-social-login#325]
Hi! I have implemented VK login provider and tested it locally. [vk.com](https://vk.com/) is the most popular social media in Russia. If you don't mind, I would like to push my branch to your repository and create a pull request.

**Comment by jaibatrik** [comment]
Sure, please raise a PR!

**Comment by petrovich2k** [comment]
@jaibatrik  Could you give me the permission to push my branch?

**Comment by petrovich2k** [comment]
@jaibatrik ?

**Comment by jaibatrik** [comment]
Hi @petrovich2k, you need to fork this repository and push the branch there. You can create PR from the fork then.

https://opensource.com/article/19/7/create-pull-request-github

**Comment by petrovich2k** [comment]
@jaibatrik could you review the PR?
https://github.com/abacritt/angularx-social-login/pull/326

**Comment by jaibatrik** [comment]
Thanks! Let me do it over the weekend.
