### ISSUE TITLE
Google sign-in is stop working after  useHash: false

### ISSUE THREAD

**Issue by kilghar** [abacritt/angularx-social-login#327]
Google Sign-in was working well but stopped working after removing hash in URL by setting useHash: false in app.routing.ts

basically getting null from authState (below), but I didn't see any noticeable error in the log.

this.authService.authState.subscribe((user) => {

}

Anyone has clue on what is going on?

**Comment by jaibatrik** [comment]
Ideally there should not be any effect of hashes on this library. Try comparing your code to the demo app in this repository.

**Comment by jaibatrik** [comment]
Reopening for time being. Appears to be a legitimate issue. I'll check if I get some time.

**Comment by jaibatrik** [comment]
Please reopen if the issue persists. Need help in debugging.
