### ISSUE TITLE
Angular web working fine but Not working with nativescript 

### ISSUE THREAD

**Issue by javatutorials2016** [abacritt/angularx-social-login#328]
JS: ERROR Error: Uncaught (in promise): Login providers not ready yet. Are there errors on you
r console?

any thoughts for nativescript compatibility?

**Comment by javatutorials2016** [comment]
looks like irrelevant, found a different plugin for nativescript

**Comment by jaibatrik** [comment]
@javatutorials2016 Would you mind pointing us to the plugin? This has been a highly requested feature.
