### ISSUE TITLE
Qst: How to use authToken in my backend?

### ISSUE THREAD

**Issue by adarshkhatri** [abacritt/angularx-social-login#330]
Can anyone point me out in the right direction?

I am developing my backend in `laminas API tool` framework. 

How do I use `authToken` in my backend? 

Should I re-call to google within the backend to check if the user has been authorized? I believe I shouldn't be doing this since the backend will be calling to google API for every backend API call.

What is the best approach?

**Comment by jaibatrik** [comment]
Yes, hit Google API from back-end to validate. Check their documentation. They have docs on how you can validate in server.

**Comment by jaibatrik** [comment]
Sorry, to have closed. Re-opening for others' participation. Will be closed automatically in case of no participation.
