### ISSUE TITLE
GitHub authentication

### ISSUE THREAD

**Issue by sergey-morenets** [abacritt/angularx-social-login#331]
Hi

Do you have any plans to add GitHub as authentication provider?

Thanks.

**Comment by jaibatrik** [comment]
Currently don't have support for OAuth based login flows.

**Comment by sergey-morenets** [comment]
> 
> 
> Currently don't have support for OAuth based login flows.

Do you mean that Github doesn't support OAuth-based authentication?
But its documentation states about this support: https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/

**Comment by jaibatrik** [comment]
No, we are not supporting authentication that requires configuring a OAuth redirect URLs.

**Comment by traviscollins** [comment]
> No, we are not supporting authentication that requires configuring a OAuth redirect URLs.

OAuth based login flows, specifically for GitHub, is a requirement for my current project. Are you choosing not to support OAuth because it involves a backend service? Or is there some other reason?

**Comment by jaibatrik** [comment]
> > No, we are not supporting authentication that requires configuring a OAuth redirect URLs.
> 
> OAuth based login flows, specifically for GitHub, is a requirement for my current project. Are you choosing not to support OAuth because it involves a backend service? Or is there some other reason?

Yeah, it's because of the involvement with back-end services.
