### ISSUE TITLE
Q: Does this support LinkedIn login ?

### ISSUE THREAD

**Issue by SagarVirpara** [abacritt/angularx-social-login#332]
Hi,

If this support linkedin login then it would be great.

I have gone through codes but not able to find out ant code related to linkedin.

**Comment by carbon-wpa** [comment]
I have never used Linkedin api for login, but if it is possible I can implement it once I have some free time. Does anybody else need it?

**Comment by jaibatrik** [comment]
LinkedIn currently supports only OAuth for authentication; we have so far shunned that because of the server-side component of the OAuth flow. If we have a good strategy to factor that in, we can think about supporting LinkedIn and other providers like Twitter, Github, etc.
