### ISSUE TITLE
[feature] Can add 'width' and 'height' as the query string?

### ISSUE THREAD

**Issue by chunwing** [abacritt/angularx-social-login#336]
https://github.com/abacritt/angularx-social-login/blob/4e839eab9fb2364926e679c89ded3f2814cfcf5b/projects/lib/src/providers/facebook-login-provider.ts#L90

**Comment by jaibatrik** [comment]
I guess we can accept those as arguments in the `signInOptions` and use them while constructing the request.

PR will be welcome on this!
