### ISSUE TITLE
Not able to sign in with mobile device, while in web browser its working properly

### ISSUE THREAD

**Issue by developerdesigner18** [abacritt/angularx-social-login#337]
The version of angularx-social-login is 2.2.1 and the angular CLI version is 8. It is working properly on the web browser but when try to do on any mobile device it is not working.

Please help me out.

**Comment by jaibatrik** [comment]
Check if there's a popup blocker.

**Comment by developerdesigner18** [comment]
@jaibatrik Thank you for the reply. But I removed the ad-blocker from the browser and re-run the project. it is not opening!!!

**Comment by developerdesigner18** [comment]
@jaibatrik Is there any browser version issue? I mean working in the old version browser but not in the latest version of the browser.

**Comment by Marax** [comment]
Not sure if related, but I experienced some issues on Firefox mobile browser, restarting browser usually helped - so I would blame the browser.

**Comment by rdtandel** [comment]
Same issue here. Working fine in android. But not working iPhone 5, Working in iPhone 6 Pro and iPhone 7. Can anybody fix this?

**Comment by hetrafi** [comment]
Yes this implementation does not work in-app browser for Facebook.

**Comment by jaibatrik** [comment]
I need to work on non-popup version of this. But many issues are dependent on it. 

Since it will be relatively bigger effort, I keep deferring it.

**Comment by jonathanlal** [comment]
Also experiencing this issue. It's a big problem for us because it means we can't run Facebook ads or share any links on Facebook. Most of our traffic comes from Facebook

**Comment by jaibatrik** [comment]
Let's track this in #248.

**Comment by SilvaEngComp** [comment]
When I access by smartphone only works in google chrome and I need allow desktop mode
