### ISSUE TITLE
angularx-social-login 3.4.1 with Angular 10: ERROR Error: Uncaught (in promise): Login providers not ready yet. Are there errors on your console?

### ISSUE THREAD

**Issue by bhaskarbommedi** [abacritt/angularx-social-login#339]
I am integrating Google and Facebook login using angularx-social-login 3.4.1 with Angular 10. 
I am getting below error: 
ERROR Error: Uncaught (in promise): Login providers not ready yet. Are there errors on your console?

![image](https://user-images.githubusercontent.com/52466858/99611581-f7ff0d80-29e1-11eb-968d-19c7046bb593.png)

**Comment by Marax** [comment]
This usually happens when you try to call something (signOut in your example) before the service is initialized - e.g. you didn't yet get the token from some http call. I guess you would need to provide more code here like where you initialize SocialLoginModule.

**Comment by WhiteLord** [comment]
I've come across the same issue using Angular 9.1.12.
My example project is minimialistic - I've created a bare bones Angular app, and a login component.
My app.module.ts is the same as the one provided in the example, I've included it in the imports section of app.module.ts.
Below is my login component.
Could it be a regression on Angular's side?

```
import {Component} from '@angular/core';
import {FacebookLoginProvider, SocialAuthService} from 'angularx-social-login';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {

  constructor(private socialAuthService: SocialAuthService) {}

  loginWithFacebook() {
    this.socialAuthService.signIn(FacebookLoginProvider.PROVIDER_ID).then(data => {
      console.log(data);
    });
  }
}
```

**Comment by WhiteLord** [comment]
One thing is for sure - Facebook SDK does not support [`autoLogAppEvents` ](https://github.com/abacritt/angularx-social-login/blob/8b52afe33f2f2119c8b1e585645269fef4cf543b/projects/lib/src/providers/facebook-login-provider.ts#L30) as evident by their latest provided code:
```
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{your-app-id}',
      cookie     : true,
      xfbml      : true,
      version    : '{api-version}'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
```

**Comment by bhaskarbommedi** [comment]
Thank you Marax, After removing the logout call it solved my issue.

But, My Observer method is not calling after social (Google) login successful. Here is the code.
In my Controller: 
ngOnInit(): void{
this.socialAuthService.authState.subscribe((user) => {
        this.user = user;
});
}
signInWithGoogle(): void {
    this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID);
  }

In app.module

@NgModule({
.
.
.
providers: [
    AuthenticationService,
    ProfessionDataService,
    UserService,
    {
      provide: 'SocialAuthServiceConfig',
      useValue: {
        autoLogin: false,
        providers: [
          {
            id: GoogleLoginProvider.PROVIDER_ID,
            provider: new GoogleLoginProvider(
              GOOGLE_LOGIN_CLIENT_ID
            )
          },
          {
            id: FacebookLoginProvider.PROVIDER_ID,
            provider: new FacebookLoginProvider(FACEBOOK_LOGIN_CLIENT_ID)
          }
        ]
      } as SocialAuthServiceConfig,
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

Please let me if I missed anything. 
Thank you.

**Comment by Marax** [comment]
@bhaskarbommedi Does your controller implements OnInit?

eg:
`export class LoginComponent implements OnInit`

**Comment by bhaskarbommedi** [comment]
@Marax Yes, It is initializing while opening the Login page. But it is not executing the code which was written inside after the google login.

export class LoginComponent implements OnInit {
.
.
}

**Comment by Marax** [comment]
Put a console.log("something") in that subscribe, to check, that it's actually firing or not, sometimes I had problems with ui just not refreshing when it gets some input from outside the framework.

**Comment by ahmed14java** [comment]
I get the same issue if I added google provider, if I only put facebook provider, it works fine, can anyone help, please.

**Comment by Champ4618** [comment]
in chorme im getting this issue login providers are not yet ready but in firefox its working fine

**Comment by bhaskarbommedi** [comment]
Thanks @Marax 
I got the issue, it is in my code. On the Google icon link, I kept <a href="">, so that it is reloading my initial controller instead of the login controller.  So that my LoginController is not on focus at the time of Google Login happened.

Thanks All for your suggestions to find the issue.

**Comment by BruneXX** [comment]
Hi, just wondering, is this updated in the README.md? since what version was this updated? thanks

**Comment by BruneXX** [comment]
Also I can't get this working in Firefox 78.10.0esr (64-bit) I'm receiving same error and when I'm implementing thte initState nothing happens it's never initialized.. any suggestions?

**Comment by BruneXX** [comment]
but... in Windows with firefox 84.0.2 works just fine

**Comment by jaibatrik** [comment]
That's strange. Generally this error appears when one of the providers fails to initialize (or you try to use one of the providers before it is initialized).
