### ISSUE TITLE
Unable to signOut from google login

### ISSUE THREAD

**Issue by bushrayasmin24** [abacritt/angularx-social-login#341]
SIgnOut is working well when I don't refresh the page. But if I refresh the page after signOut It is showing this error.

**core.js:4352 ERROR Error: Uncaught (in promise): Not logged in**
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27474)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484)
    at invokeTask (zone-evergreen.js:1621)

**Comment by Marax** [comment]
That's because signing in will actually only provide you with user information. If you refresh the page, all locally stored information in social-login will disappear so there is no need for signOut. If you are still signed in after refresh, it's because your login information is stored by you somewhere else, like local storage.

**Comment by bushrayasmin24** [comment]
If I follow your solution. It is a good way to go through.? But If google provides the signOut method so behind it must be a specific reason. So we must have signOut from google first then we call our SignOut.

**Comment by Marax** [comment]
Depends on your use case. For example I use social login only for authentification with my server. Google provides token, I validate it on the backend, then I use my own auth between server and client. So I don't need social/google auth anymore. I actually implemented it in a way, that after login with my backend is sucessful, I signOut from google login, but keep my own auth stored in localStorage.

If you still want to have signOut there you have to at least first check that you're signedIn probably by checking `this.socialAuth.authState.subscibe(data=> if(data!=null){...signOut()})`

This is my use-case login component:
```typescript
ngOnInit() {
	this.authSubscription = this.socialAuthService.authState.subscribe((user) => {
		if (user) {
			this.login(user.idToken); //call api on my server with google token and validate and then redirect to other page
		}
	});
}

ngOnDestroy() { //when login page is being destroyed (moving to other page), signOut from google
	this.socialAuthService.signOut();
	this.authSubscription.unsubscribe();
}

async signInWithGoogle() { //called when you click on Google Login button
	this.loading = true;
	try {
		await this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID);
	} catch (e) {
		console.log(`Failed to login using google. ${e.error ? e.error : e}`);
		this.loading = false;
	}
}
```

**Comment by bushrayasmin24** [comment]
Thank you for your response, I'm trying to find an appropriate answer to this, you clear my all doubts. The problem resolved thanks a lot.
