### ISSUE TITLE
Add code flow authentication for Facebook

### ISSUE THREAD

**Issue by penfold** [abacritt/angularx-social-login#342]
Facebook offers a more secure option for authentication where the response on the web client only received a simple code instead of the access_token. Then on the backend, we can exchange the code for an access_token  that can be secured using the app secret via the proof token.

https://developers.facebook.com/docs/facebook-login/security/#codeflow

I think this addition (via a boolean config switch) should not be much more than tweaking the auth call to FB. 

Is this something that you would consider?

Thanks,
Paul

**Comment by jaibatrik** [comment]
Sure, as long as this is useful to the user base of the library, it can be added. Feel free to raise a PR!
