### ISSUE TITLE
Question: Can be the PROVIDE_ID added / updated later in component, not in .module?

### ISSUE THREAD

**Issue by 4i-helpynet** [abacritt/angularx-social-login#343]
I use the angularx-social-login in a lazy loaded library where the provider informations coming from config parameter outside of library. I try to find a solution with example, where the provider information not set in the module, but later in the .component constructor, or init.

Can you give some tip or example code for that?

**Comment by jaibatrik** [comment]
The provider configurations can be a provided with a Promise; which can resolve at a later point of time. Check if that can help you with your use case.
