### ISSUE TITLE
Property 'refreshAuthToken' does not exist on type 'SocialAuthService'.

### ISSUE THREAD

**Issue by javatutorials2016** [abacritt/angularx-social-login#344]
I was using angularx-social-login@3.2.1, now did a clean install of angularx-social-login@3.4.1, however I get this error?
import { SocialAuthService } from "angularx-social-login";

constructor(
    private tokenExtractor: HttpXsrfTokenExtractor,
    private secureLSService: SecureLSService,
    private router: Router,
    private authService: SocialAuthService
  )

 this.authService.refreshAuthToken(GoogleLoginProvider.PROVIDER_ID);

just followed the same steps as mentioned on the GITHUB home page and encounter this error at this.authService.refreshAuthToken. any suggestion will be helpful.

**Comment by javatutorials2016** [comment]
please ignore, "npm i abacritt/angularx-social-login"  resolved this issue

**Comment by zrelja** [comment]
@carbon-wpa any help please? :) typings?

**Comment by carbon-wpa** [comment]
@javatutorials2016 , @zrelja I guess new version is not yet published in npm. Please take a look that last commit was merged to master two days ago. Lastest version on NPM is 3.4.1 which was published about 22 days ago.

@jaibatrik can you publish new version to npm?

**Comment by jaibatrik** [comment]
Hey sorry, doing it in couple of hours.

**Comment by jaibatrik** [comment]
Couldn't get to it today. Will publish tomorrow.

**Comment by jaibatrik** [comment]
Just published to npm, thanks!
