### ISSUE TITLE
Auth token and id token undefined after google token refresh

### ISSUE THREAD

**Issue by zrelja** [abacritt/angularx-social-login#345]
![refresh](https://user-images.githubusercontent.com/33201237/100794383-c93f5900-341d-11eb-89a2-04b5b7f310a9.png)

Hey @carbon-wpa ,
I am refreshing the token, and it seems to work fine, but I have a weird behavior where the auth token and id token are undefined.

Do you know how could I retrieve id_token after token refresh?

Thanks!

**Comment by carbon-wpa** [comment]
@zrelja I have checked it on my local env with new version of lib. It is defenetiely an issuse - sorry. I have created PR to fix it

**Comment by zrelja** [comment]
Nice thanks!
