### ISSUE TITLE
angularx-social-login 3.5.1 SSR issue 

### ISSUE THREAD

**Issue by manduriomane** [abacritt/angularx-social-login#346]
Hi,

I have updated angularx-social-login to 3.5.1 version, but when I compile with angular universal I get this error:

```
 redirect_uri: location.origin,
                  ^
ReferenceError: location is not defined
```

the problem is on this function:

```
var ProtocolMode;
(function (ProtocolMode) {
    ProtocolMode["AAD"] = "AAD";
    ProtocolMode["OIDC"] = "OIDC";
})(ProtocolMode || (ProtocolMode = {}));
const COMMON_AUTHORITY = 'https://login.microsoftonline.com/common/';
const defaultOptions = {
    redirect_uri: location.origin,
    authority: COMMON_AUTHORITY,
    scopes: ['openid', 'profile', 'User.Read'],
    knownAuthorities: [],
    protocolMode: ProtocolMode.AAD,
    clientCapabilities: [],
    cacheLocation: 'sessionStorage'
};
```

How I can fix it?

Thanks

Marco

**Comment by jaibatrik** [comment]
Looks like a bug with Microsoft provider. Does it occur when you don't have configured one? What command are you running?

**Comment by manduriomane** [comment]
Hi jaibatrik,

yes I don't have any Microsoft provider configured.

The error occurs when I run this command in angular cli:

`npm run dev:ssr`

**Comment by dpkswn4** [comment]
Same issue. Any update?

**Comment by jaibatrik** [comment]
Yeah, will check this over the weekend.

**Comment by duhamaher** [comment]
i have faced the same error as well when running npm run dev:ssr
any updates?

**Comment by jaibatrik** [comment]
Relased v3.5.3 in npm. I did not test this with SSR though as the demo app is not setup for that. Could you guys test it and report?

**Comment by manduriomane** [comment]
Ok now SSR works. Thanks a lot
