### ISSUE TITLE
Not able to initialize GoogleLoginProvider with custom config options

### ISSUE THREAD

**Issue by RTechEFolks** [abacritt/angularx-social-login#349]
I have added the init config in the app.module.ts file as shown below
![image](https://user-images.githubusercontent.com/67382921/101281145-7e458d00-37f3-11eb-92fa-3f353be12e09.png)

Even though I supply the arguments
{
              scope: "email",
              response_type: "code"
            }
for initialization. The call for the token is still going as 

![image](https://user-images.githubusercontent.com/67382921/101281171-a9c87780-37f3-11eb-8300-375eeca06408.png)

Please let me know if the custom config is possible or not for google.

Thanks in advance

**Comment by jaibatrik** [comment]
Not sure why this is happening. Could you please try debugging the `GoogleLoginProvider#initialize` method?

**Comment by RTechEFolks** [comment]
I tried it but values are not updating. Can I expect this to be resolved in some time?

**Comment by jaibatrik** [comment]
Have to check what is the behavior outside this library. Would help if you provided a sample as well. Thanks!

**Comment by foreinger** [comment]
Hi, I have the same problem. I found that in the loaded library code, data is reassigned to "permission", "id_token", which is used in the form. Maybe this will help solve the problem.
![image](https://user-images.githubusercontent.com/44264209/112767890-d19d4e80-9021-11eb-97fb-73f8ee8e9be0.png)
![image](https://user-images.githubusercontent.com/44264209/112767909-eed21d00-9021-11eb-8c37-20dd8bf6a23f.png)
