### ISSUE TITLE
Signing API calls?

### ISSUE THREAD

**Issue by gdeward** [abacritt/angularx-social-login#35]
I've been using Satellizer with AngularJS forever, which took care of all of this, so I'm sorry for the noob question.

Once I'm authenticated with Facebook or Google, how can I pass something to the back end to generate a JWT and validate the Facebook or Google session?  I've checked the Local Storage and Session Storage and I don't see anything like a JWT "token."  Is there any mechanism to sign an API request and validate it on the back end?

**Comment by filosssof** [comment]
You can see my example https://github.com/filosssof/kotlin-rest-spring-boot This one is written on kotlin, but the Spring is used on the same way as in Java.

**Comment by jaibatrik** [comment]
Closing this for now due to inactivity.
