### ISSUE TITLE
Only initialise Google on condition

### ISSUE THREAD

**Issue by jpike88** [abacritt/angularx-social-login#350]
I have a Cordova app, and want to disable the Google Provider, but there doesn't seem a way to do it. Otherwise I am getting spammed with the error 'gapi.auth2.ExternallyVisibleError' as the Cordova apps use the file:// protocol

**Comment by jaibatrik** [comment]
You can obtain the value you provide for `SocialAuthServiceConfig` from a function and return different objects based on condition. Check https://angular.io/api/core/FactoryProvider.
