### ISSUE TITLE
angularx-social-login is not working on cordova run browser.

### ISSUE THREAD

**Issue by LDHo** [abacritt/angularx-social-login#351]
Hi, I am using Ionic 4 with angular 7. So currently my project will be a hybrid application where a single code based will support 3 kinds of platform which is iOS, android, and browser. However, while I compiled my ionic angular project as cordova browser, I found out that AuthService.signIn got error which is as below. My question is that does the angularx-social-login supports cordova browser? I am currently using angularx-social-login (1.2.7). 

vendor.js:76811 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'signIn' of undefined
TypeError: Cannot read property 'signIn' of undefined
    at vendor.js:215778
    at new ZoneAwarePromise (polyfills.js:5355)
    at GoogleLoginProvider.push../node_modules/angularx-social-login/angularx-social-login.es5.js.GoogleLoginProvider.signIn (vendor.js:215777)
    at vendor.js:210645
    at new ZoneAwarePromise (polyfills.js:5355)
    at AuthService.push../node_modules/angularx-social-login/angularx-social-login.es5.js.AuthService.signIn (vendor.js:210642)

Hope someone could lend me a hand.

Thanks

**Comment by jaibatrik** [comment]
I think we have seen issues earlier with this where the library is incompatible with PWAs and the cross-platform libraries. I don't think we have a solution for this as of now. It'd be great if someone can research and point out the cause / submit a fix.

**Comment by jaibatrik** [comment]
#248 is related to this.

**Comment by JaimeTruman** [comment]
someone fix that pls
