### ISSUE TITLE
Provide: SocialAuthServiceConfig shows the error 'SocialAuthServiceConfig' only refers to a type, but is being used as a value here.'

### ISSUE THREAD

**Issue by alexedwalvarado** [abacritt/angularx-social-login#352]
Here is my code
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { SocialLoginModule, SocialAuthServiceConfig } from 'angularx-social-login';
import { GoogleLoginProvider, FacebookLoginProvider } from 'angularx-social-login';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [SocialLoginModule],
  providers: [
    { provide: SocialAuthServiceConfig, useValue: {
        autoLogin: false,
          providers: [
            {
              id: GoogleLoginProvider.PROVIDER_ID,
              provider: new GoogleLoginProvider(
                'clientId'
              )
            },
            {
              id: FacebookLoginProvider.PROVIDER_ID,
              provider: new FacebookLoginProvider('clientId')
            }
          ]

      } as SocialAuthServiceConfig  
    },
  ],

  bootstrap: [AppComponent]
})
export class AppModule {}

**Comment by lperezp** [comment]
Follow the problem with version 12 of Angular.

**Comment by SheikhmohideenM** [comment]
import { SocialAuthServiceConfig, SocialLoginModule } from 'angularx-social-login';

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    SocialLoginModule
  ],
  providers: [
    {
      provide: 'SocialAuthServiceConfig',
      useValue: {
        autoLogin: false,
      } as SocialAuthServiceConfig,
    }    
  ],
  bootstrap: [AppComponent]
})

I hope its works. Thank you
