### ISSUE TITLE
While closing popup instead of sign in, it logs error in console

### ISSUE THREAD

**Issue by Surendar-Kuppusamy** [abacritt/angularx-social-login#353]
When user click the google sign in button, then it shows popup. Instead of sign in, closing the popup it logs error on console
![Error](https://user-images.githubusercontent.com/74266599/102256445-6d9ec080-3f31-11eb-8ebd-3107a65ad27f.PNG)
![error1](https://user-images.githubusercontent.com/74266599/102256602-98891480-3f31-11eb-9d18-099586e3bf72.PNG)
.

**Comment by jaibatrik** [comment]
The solution is to catch the error in the `Promise` rejection and handle gracefully.
