### ISSUE TITLE
Support for other providers

### ISSUE THREAD

**Issue by kbk1303** [abacritt/angularx-social-login#356]
Hi,

Your documentation says it is possible to use this API for other providers too like Discord, Twitch-tv, Twitter etc, but it does not provide any examples of doing so. 

Is it supposed to be an option to support other providers by extending your "BaseClassProvider" or something? (if that is the case, please provide an example), or does it merely suggest that you can add more providers to the API if there is a demand for it? 

Thanks

**Comment by jaibatrik** [comment]
Hi, the library would support any custom provider you implement based the `LoginProvider` interface or `BaseLoginProvider` class. You can pass any such custom provider to the provider value (the `SocialAuthServiceConfig`) in the module initialization. Look at the existing providers for example.
