### ISSUE TITLE
How to use refresh token properly?

### ISSUE THREAD

**Issue by thangaraja** [abacritt/angularx-social-login#357]
I just integrated the package and its working with Google authentication. The Id token is returned by the method

`this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID);`

The token received expires in one hour. So I used the below method to refresh

`this.socialAuthService.refreshAuthToken(GoogleLoginProvider.PROVIDER_ID);`

Now how to get the new token? it looks like the authState subscription is working only when signIn & SignOut not for refresh token.

**Comment by jaibatrik** [comment]
The `refreshAuthToken` method has code to send value to `authState` subscription. Check - https://github.com/abacritt/angularx-social-login/blob/9bcbb147081cd4cd53a4cb0d6fa946baa0f4a955/projects/lib/src/socialauth.service.ts#L118

Can you debug and try to see what might be happening?
