### ISSUE TITLE
Failed to load resource file://apis.google.com/js/platform.js

### ISSUE THREAD

**Issue by adidamty** [abacritt/angularx-social-login#36]
i am getting this error with android emulator :
file://apis.google.com/js/platform.js Failed to load resource: net::ERR_FILE_NOT_FOUND

After i investigate i found out in files index.js and angular4-social-login.umd.js :

need to change :
//apis.google.com/js/platform.js
to : 
https://apis.google.com/js/platform.js

**Comment by jaibatrik** [comment]
Looks like you are not running a server and clicking an HTML file to open it in browser. That use case is not supported.
