### ISSUE TITLE
Using page redirect instead of pop up

### ISSUE THREAD

**Issue by zwjohn** [abacritt/angularx-social-login#363]
Hi,

This is a more question rather than an issue. I don't want to use a pop up for social sign in as there are many issues in using a pop up.

If I use ux_mode: "redirect" for Google sign in, the application page will be redirected to Google sign in page and redirect back to the application with many parameters. How do I get user info in this case? 
BTW, autoLogin is set to false.

Thanks!

**Comment by jaibatrik** [comment]
Can you check what happens if you set `autoLogin` to true? This is one of the most requested feature we are being asked about. Tracking this with #248.

**Comment by zwjohn** [comment]
Thanks for your reply, I will try it out setting autoLogin to true to see the behavior

**Comment by jaibatrik** [comment]
Let's track this with #248.
