### ISSUE TITLE
authState returns different value when in different component

### ISSUE THREAD

**Issue by terryjiang2020** [abacritt/angularx-social-login#367]
I am using Angular 8 with version 2.2.1

I load authService.authState.subscription() in two components: one inside the panel and one in login page. 

The inside one will check if user log in though social account; if so (authState return user data), run authService.signOut(true) and send user to log in page;

The outside one will check if user has signed in with social account; if so (authState return user data), sign in the user. 

Now the strange thing happens. I sign in user with social account and then sign out. The inside one's authService return null and send user to outside directly; then the outside authService return user data in my authState. 

Those suppose to be the same but it turns out to be different.

**Comment by terryjiang2020** [comment]
Hmmmm, so do I need to come back monthly to keep this issue alive?

**Comment by jaibatrik** [comment]
Ideally, there should only be one instance of `AuthService` be running. Is it not the case for you? The same `AuthService` instance should not return different user information.
