### ISSUE TITLE
The service stop working after PC goes back from sleep

### ISSUE THREAD

**Issue by Dimanoid** [abacritt/angularx-social-login#368]
After sleep and back calling signin starts to give the error "Login providers not ready yet. Are there errors on your console?". No errors in console, I think something should be reinitialized...

**Comment by Dimanoid** [comment]
Is the project abandoned?

**Comment by jaibatrik** [comment]
You can handle the error with the `onError` callback and show a message to the user / reload the page. Not sure if I can think of any other solution at this moment.
