### ISSUE TITLE
Failed to load resource : file://connect.facebook.net/en_US/sdk.js

### ISSUE THREAD

**Issue by adidamty** [abacritt/angularx-social-login#37]
i am getting this error with android emulator :
file://connect.facebook.net/en_US/sdk.js Failed to load resource: net::ERR_FILE_NOT_FOUND

After i investigate i found out in files index.js and angular4-social-login.umd.js :

need to change :
//connect.facebook.net/en_US/sdk.js
to : 
https://connect.facebook.net/en_US/sdk.js

**Comment by jaibatrik** [comment]
Looks like you are not running a server and clicking an HTML file to open it in browser. That use case is not supported.

**Comment by Hamidcreative** [comment]
Thanks jaibatrik
