### ISSUE TITLE
Google login ux_mode:redirect not working

### ISSUE THREAD

**Issue by justinthomas0789** [abacritt/angularx-social-login#375]
```
this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID, {ux_mode: 'redirect'}).then((userData) => {
        this.googlebMethod(userData)
})
```

this is making the call and returning data, but not going inside `then`

**Comment by jaibatrik** [comment]
I don't think it was designed to return the data in `Promise`. Rather, you'll get the user data in the `Observable`. But will check the code. It might be convenient to return the data with `Promise` as well.

**Comment by justinthomas0789** [comment]
I have tried it too, but somehow it is also not working. I don't know what is anything wrong with my implementation, subscription is not working
```
this.socialAuthService.authState.subscribe((user) => { 
      console.log(user)
      this.loggedUser = user
    });
```

**Comment by jaibatrik** [comment]
That should work ideally. Check if there are any errors in console. You can try comparing your implementation against the demo site we have.

**Comment by jaibatrik** [comment]
Oh, I think I missed the main issue. The ux_mode redirect is probably the main problem. Check #248.

**Comment by justinthomas0789** [comment]
Yes, I have trouble login using popup mode in private window. That's why used redirect mode. its redirecting to the page, but subscribing to authState not seems working in my code

**Comment by justinthomas0789** [comment]
Actually I want to login with google in incognito mode without allowing 3rd party cookies, facebook login is working fine but not google login

**Comment by justinthomas0789** [comment]
Well, subscribing authState is working. The problem was, I haven't set `autoLogin: true` in the configuration.

**Comment by jaibatrik** [comment]
Great! Would you be able to paste the relevant snippets so that others facing the problem can see?

Apart from that, I think it makes sense to set the `autoLogin` value to `true` by default.

**Comment by justinthomas0789** [comment]
Sure, I'll do that. Now I have another concern. if we use redirect mode, How do we preserve query parameters used in the URL

**Comment by jaibatrik** [comment]
I have not tried the redirect mode and am not familiar with the configs. Need to check it.
