### ISSUE TITLE
New release scheduled?

### ISSUE THREAD

**Issue by mtinnes** [abacritt/angularx-social-login#377]
Is there a new release scheduled? I need access to some fields added to the Microsoft provider which are not available in the current release.

**Comment by jaibatrik** [comment]
Send a PR. If the changes are trivial and not backward incompatible, we can push a release.

**Comment by mtinnes** [comment]
It looks like the changes I need are already in place, just needs to be
built and a new release pushed to npm.

**Comment by jaibatrik** [comment]
Please bear with me for the day, I'll release it tomorrow.

**Comment by jaibatrik** [comment]
Published v3.5.5.
