### ISSUE TITLE
Google login error 

### ISSUE THREAD

**Issue by AliArmas** [abacritt/angularx-social-login#379]
> function

`
signInWithGoogle(): void {

    this.authService.signIn(GoogleLoginProvider.PROVIDER_ID).then(data =>{
      console.log("Datos google: "+data);
    });
  }
`

>Error

`ERROR Error: Uncaught (in promise): Login providers not ready yet. Are there errors on your console?`

> Project

[https://github.com/AliArmas/E-COMMERCE-04.21-V01.git](url)

**Comment by RatFou** [comment]
If you have adblock extension, have you tried to deactivate it?

**Comment by jaibatrik** [comment]
Are you trying to do this on load? It will not work that way. Check #280. Use the `initState` `Observable` to observe when the providers are ready.
