### ISSUE TITLE
SocialAuthService.GetState not returning value

### ISSUE THREAD

**Issue by MMieszko** [abacritt/angularx-social-login#380]
Hi!

I have just started using the library. Works lovely but I have found the issue.

There is my bootstrap component:
```
<div class="p-grid root">
  <div class="p-col-12">
    <app-top-bar></app-top-bar>
  </div>
  <div class="p-col-2">
    <app-left-menu></app-left-menu>
  </div>
  <div class="p-shadow-2 p-col-8">
    <app-recipes></app-recipes>
  </div>
  <div class="p-shadow-2 p-col-2">
    <app-shopping-list></app-shopping-list>
  </div>
</div>

```

In the top-bar component I am using the facebook login option. When I login with Facebook using 
`this.authService.signIn(FacebookLoginProvider.PROVIDER_ID);`
it works well - refresh the page and hit into ngOnInit() function where I have:

 ```
ngOnInit(): void {
    debugger;
    this.authService.authState.subscribe(
      (user) => {
        debugger;
        this.user = user;
        this.loggedIn = user != null;
      },
      (error) => {
        debugger;
      },
      () => {
        debugger;
      }
    );
  }
```
However the same function ngOnInit() when page is getting loaded before login asks the authState  this.authService.authState.subscribe(...) but the value is never bring back and no callback fucntions are fired - no success, no error and not even complete callback.

**Comment by jaibatrik** [comment]
There's a `autoLogin` parameter in the config that you need to set to `true` for this to work.
