### ISSUE TITLE
Facebook login, need to click login twice

### ISSUE THREAD

**Issue by davlasry** [abacritt/angularx-social-login#381]
Tried with v3.5.5

If there is no user currently connected to facebook in the browser
When I click on the login with facebook icon, the login popup is displayed
I enter my email and password and then click on the Login button
The popup is closed as expected

**Result**: I receive the following error
"User cancelled login or did not fully authorize."

When I click on the login with facebook icon once again, everything works fine and I am logged in to the application.

**Expected behavior**:
 I should be logged in to the app after clicking the Login button in the facebook popup

Can be reproduced on https://app.reali.com after clicking on SIGN IN in the header.

I am using a retry trick but it is not very smooth and should not need it

```typescript
async signInFacebook() {
    let facebookLoginCount = 0;
    try {
        const user = await this.socialAuthService
            .signIn(SocialAuthService.FacebookLoginProvider.PROVIDER_ID);
        this.type === 'LOGIN' ? this.login(user.id) : this.signUp(user);
    } catch (error) {
        setTimeout(() => {
            if (facebookLoginCount < 2) {
                this.signInFacebook();
            }
            facebookLoginCount++;
        }, 5000);
    }
}
```

**Comment by jaibatrik** [comment]
Tried at your URL, it appeared to work at the first try. Did you debug and find anything?

**Comment by davlasry** [comment]
@jaibatrik Yes it now works thanks 👍
