### ISSUE TITLE
Demo website not working. Seeing "Login providers not ready yet. Are there errors on your console?" in console

### ISSUE THREAD

**Issue by j-a-h-i-r** [abacritt/angularx-social-login#382]
I was checking the demo website (https://abacritt.github.io/angularx-social-login/). But I could not get any of the login providers to work. When I looked into the console, I saw `Login providers not ready yet. Are there errors on your console?` message printed in the dev console.

Here is the error,
```
ERROR Error: Uncaught (in promise): Login providers not ready yet. Are there errors on your console?
    at T (polyfills-es2015.95bb65e853d2781ac3bd.js:1)
    at polyfills-es2015.95bb65e853d2781ac3bd.js:1
    at main-es2015.a8af1102894e427d2143.js:1
    at new D (polyfills-es2015.95bb65e853d2781ac3bd.js:1)
    at e.signIn (main-es2015.a8af1102894e427d2143.js:1)
    at e.signInWithFB (main-es2015.a8af1102894e427d2143.js:1)
    at main-es2015.a8af1102894e427d2143.js:1
    at Xs (main-es2015.a8af1102894e427d2143.js:1)
    at s (main-es2015.a8af1102894e427d2143.js:1)
    at HTMLButtonElement.<anonymous> (main-es2015.a8af1102894e427d2143.js:1)
```

I was on the latest version (89.0.4389.114) of Google Chrome when I encountered the error.

**Comment by michafrometa** [comment]
Facing the same here

**Comment by jaibatrik** [comment]
Does work for me... Do you folks have some kind of tracking protection on?

**Comment by michafrometa** [comment]
Angular version? I found they support up to Angular 10 only, I was using
Angular 11.

**Comment by ubihacks** [comment]
any update on it ?

**Comment by ubihacks** [comment]
Uncaught (in promise): Login providers not ready yet. Are there errors on your console?

**Comment by WagdySamih** [comment]
same error on angular 12
![image](https://user-images.githubusercontent.com/45714046/127315438-8a29bc59-363e-421c-912d-a467eb707d04.png)
