### ISSUE TITLE
Error Facebook Provider

### ISSUE THREAD

**Issue by mustafa05deniz** [abacritt/angularx-social-login#384]
Hi, When I try to sign in with facebook, it does nothing. It seems it doesn't get into then, error or finally blocks.

**Comment by kungfucsiga** [comment]
The same thing happens to me

**Comment by gedkul** [comment]
Same... I think its Facebook related problem...

**Comment by giannicic** [comment]
Same

**Comment by firzshkh** [comment]
same here. Should we wait ?

**Comment by aks7665** [comment]
I am also facing the same issue.

**Comment by frankps** [comment]
Same here! Was already looking 2 hours into this problem, but apparently a general problem.

**Comment by gedkul** [comment]
Yes its major bug on Facebook side. https://developers.facebook.com/status/issues/492652922187445/

**Comment by gedkul** [comment]
Resolved and working again.

**Comment by jaibatrik** [comment]
Thanks everyone. Closing this.
