### ISSUE TITLE
The Microsoft provider doesn't allow selecting an account

### ISSUE THREAD

**Issue by vladimir-kazakov** [abacritt/angularx-social-login#390]
When a user has multiple accounts, the Microsoft provider silently uses the currently logged in account, which is not always correct. The user may need to use another account, but currently there is no way to do it.

By default, the Google provider behaves the same way, but it can be changed by providing options to `signIn()` with `prompt: select_account`. Unfortunately, this doesn't work when using the Microsoft provider. As far as I understand, the MSAL library is being used under the hood by this provider, and it seems like MSAL [does support this feature](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior). Could it be exposed through this library as well?

**Comment by jaibatrik** [comment]
It'd be great if you could check the `MicrosoftLoginProvider` code and suggest how we can modify it. We can then have a PR to add the feature.
