### ISSUE TITLE
Uncaught SyntaxError: Identifier 'i' has already been declared

### ISSUE THREAD

**Issue by coperfield86** [abacritt/angularx-social-login#394]
I include your package in my project and when use this private authService: SocialAuthService the console show this error:
sdk.js?hash=c496acda8bb290322cf2711c8dd070f2&ua=modern_es6:1 Uncaught SyntaxError: Identifier 'i' has already been declared
    at sdk.js?hash=c496acda8bb290322cf2711c8dd070f2&ua=modern_es6:1
(anonymous) @ sdk.js?hash=c496acda8bb290322cf2711c8dd070f2&ua=modern_es6:1

any idea?

**Comment by jaibatrik** [comment]
No. Try running the code in dev mode to see which part of the code is breaking.
