### ISSUE TITLE
It's not Compatible with Angular 12

### ISSUE THREAD

**Issue by dittuxdev** [abacritt/angularx-social-login#400]
The installation fails for an angular 12 project 
![screenLibrary](https://user-images.githubusercontent.com/54783343/120241345-2af34b00-c228-11eb-828b-d472be0dd2f8.png)

**Comment by TylerBrinks** [comment]
I have the same issue.  I force the installation which compiles, but is missing the gapi variable at runtime.  The initialization fails.  I plan to try different build targets to see if it fixes the issue.

**Comment by TylerBrinks** [comment]
> I have the same issue. I force the installation which compiles, but is missing the gapi variable at runtime. The initialization fails. I plan to try different build targets to see if it fixes the issue.

Scratch my last reply.  The gapi variable is present, but the object does not appear to have a "load" function after the https://apis.google.com/js/platform.js script finishes loading.

**Comment by TylerBrinks** [comment]
Run `npm i angularx-social-login --force` or `npm i angularx-social-login --legacy-peer-deps` and you should be able to install and run the library.

**Comment by amitbarik167** [comment]
Any update on this ? Although --force or --legacy-peer-deps helps to install, google oAuth iFrame is not loading in chrome or edge.

I am using Angular 12.0.5, Angular CLI 12.0.5, typescript   4.2.4, Node: 14.17.0, npm 7.17.0

**Comment by anuragpal1989** [comment]
![image](https://user-images.githubusercontent.com/11556411/122782273-34734e80-d2ce-11eb-92b1-496c4668becf.png)
Showing error for Angular 12.
Any fixes? or work around?

**Comment by sepatel** [comment]
I'm looking for an update/fix for this as well as it prevents the CI/CD pipeline from working (which is done inside of a fresh docker container so you can't really go and do a --force by hand on each commit. Just need this updated to say it also supports angular 12.

**Comment by jaibatrik** [comment]
A PR is raised for this at #424. Hoping to merge this by tomorrow.

**Comment by amitbarik167** [comment]
@jaibatrik Looking at the PR comments, do we need to wait for a major release to get the package updated to be compatible with angular 12 ?

**Comment by jaibatrik** [comment]
Hey, really sorry people. I am kind of swamped with work. 

It's generally me who creates the releases. Tomorrow is a holiday for me and I'll create the release and publish it.

**Comment by jaibatrik** [comment]
Just published v4.0.0 to npm. Please report any issues you see.
