### ISSUE TITLE
Microsoft provider uses unminified JS lib

### ISSUE THREAD

**Issue by milen-yordanov** [abacritt/angularx-social-login#404]
See: https://github.com/abacritt/angularx-social-login/blob/master/projects/lib/src/providers/microsoft-login-provider.ts#L124
It uses:
https://alcdn.msauth.net/browser/2.13.1/js/msal-browser.js

But it should use the minified version:
https://alcdn.msauth.net/browser/2.13.1/js/msal-browser.min.js

See: 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/cdn-usage.md

**Comment by jaibatrik** [comment]
Would it be possible for you to open a PR? I can merge and release today itself. It's a holiday here!
