### ISSUE TITLE
MicroSoft Provider for retrieving authorization code  and sending code to backend services.

### ISSUE THREAD

**Issue by taalhach** [abacritt/angularx-social-login#407]
I am working on an application and we are integrating several social logins we intergrated google and works fine when it comes to retirieving authorization code and sending it to out backend service which retrieves access, refresh and id token by itself. for google provider we have an option to set offline access but in case of microsoft we don't have such option my question is that is there any way to hack it using this library while i am writing i am thinking about redirecting to backend endpoint where code is extracted and service retrieves all tokens using authorization code. is  possible to do such thing using this lib or we will have to integrate msal ?

Thanks in advance :)

**Comment by IKENMouad** [comment]
@taalhach  i'm facing the same issue , did y find any solution plz??
