### ISSUE TITLE
Demo Let Me In After "Sign out"

### ISSUE THREAD

**Issue by TLKG** [abacritt/angularx-social-login#414]
Testing [demo Google sign-in/out ](https://abacritt.github.io/angularx-social-login/) using Chrome and Edge.

### Chrome
It let me in without asking for password. Guess because I have already signed into Google on other tab of Chrome. Clicked on the big `Sign out` button, redirected back to "Not signed in"
![image](https://user-images.githubusercontent.com/22269729/122098850-32892700-cdc6-11eb-8578-97d22b171098.png)

**Same screen, clicked on the red G, it let me in without asking for anything.** 

### Edge
The first visit to demo, it asked for username and password. Clicked on "Sign out" button, went back to the above screen, good. 

**Same screen, clicked on the red G, it let me in without asking for anything.**

Cleared browsing data, and confirmed not to remember password in Edge, closed all Edge instances, opened a new and only Edge. Still I'm in without being asked for anything.

I also checked other issues of this repository, status opened and closed, found some similar reporting sign out not log out completely for FB and G. Seems two possible params recommended by the team:

1. `app.module.ts` set `autoLogin` to `false`. For example
2. pass in `true` for 
`signOut(): void {    this.authService.signOut(true);  }`

### I build a small local project
As I have no write access to the demo site to tweak them. Local project implemented 1 & 2. Repeating the same aforementioned test on Chrome and Edge. I'm prompted for username, then no password needed, I'm in. So, slightly better than the demo. My local environment:
OS: Windows_NT x64 10.0.19041
VSC: 1.57.0 (Date: 2021-06-09T17:18:42.354Z, Electron: 12.0.9)
Chrome: 91.0.4472.101 (Official Build) (64-bit)
Node.js: 14.16.0
Angular CLI: 10.1.1

**Is this the expected behavior? How to sign-out completely so user is prompted for password?**
Really appreciate it someone can drop an answer.

**Comment by jaibatrik** [comment]
Did `signOut(true)` not help in this case?

**Comment by TLKG** [comment]
@jaibatrik Combination of `autoLogin: false` and `signOut(true)` did bring up the username page, but not the password page. Finally here is the [solution](https://groups.google.com/g/google-api-javascript-client/c/PCs8xXV4wxk/m/HDa-_xWgXe4J), look for comment from **Nick Fenwick**.

**Comment by jaibatrik** [comment]
I was wondering what is the use case for signing someone out from, say, Google itself? Shouldn't just signing out from your site be enough? A user might be logged in to many sites with Google, and if you force them to sign out of Google, they'll be signed out of all those other sites as well. Is that what you want?

**Comment by TLKG** [comment]
Same. But from end user point of view, sign out means sign out. I would be very concerned if the app is data-sensitive, how would I trust this app?
Google's view, they thought they've already validated a person, rest is yours. 
This is what I thought, Google ought to utilize their "Client ID" for each app to sign in/out users for app bases, rather than as a whole. 

On June 19, 2021 at 9:35 PM, Jaibatrik Dutta ***@***.***> wrote:






I was wondering what is the use case for signing someone out from, say, Google itself? Shouldn't just signing out from your site be enough? A user might be logged in to many sites with Google, and if you force them to sign out of Google, they'll be signed out of all those other sites as well. Is that what you want?

**Comment by TLKG** [comment]
It was a little bit of inconsistent yesterday. 

Converted the sign-out into 2 buttons: Convenient signout, and _Secure signout_.
Implemented as 

```
logOut(ifSecure): void 
{
	...
        this.socialAuthService.signOut(true).then(
        () =>
        {
            if (ifSecure) window.location.assign('https://accounts.google.com/Logout');
        }
        );
}

```
Tested _Secure signout_ with and without call to my own API, plus with and without standalone (non-app) Chrome to Gmail and SO as the same user:

    - Always prompts with ID, then requires a password.
    - standalone non-app Gmail is not impacted at all.
