### ISSUE TITLE
Google Sign is not working

### ISSUE THREAD

**Issue by grishabh1992** [abacritt/angularx-social-login#426]
Facebook  login working fine but having issue with google.

I followed lots of resource already cross check everything seems correct to me.

**When I am using implementation mentioned here(https://developers.google.com/identity/sign-in/web/sign-in?refresh=1) using 'angularx-social-login' then working fine but with this module not working.**

My Reference: 
https://developers.google.com/identity/sign-in/web/sign-in?refresh=1
https://github.com/abacritt/angularx-social-login/issues/170

**Comment by AlexTsimbalyuk** [comment]
I got the same issue which I solved by downgrading to 3.5.7 version.
