### ISSUE TITLE
4.0.0 version bug

### ISSUE THREAD

**Issue by blueiceprj** [abacritt/angularx-social-login#428]
After update to new version I get this error on compile.
Angular 11.X

Error: node_modules/angularx-social-login/socialauth.service.d.ts:59:21 - error TS2694: Namespace '"...../node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

59     static ɵfac: i0.ɵɵFactoryDeclaration<SocialAuthService, never>;
                       ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/angularx-social-login/socialauth.service.d.ts:60:22 - error TS2694: Namespace '"...../node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

60     static ɵprov: i0.ɵɵInjectableDeclaration<SocialAuthService>;
                        ~~~~~~~~~~~~~~~~~~~~~~~

Error: node_modules/angularx-social-login/sociallogin.module.d.ts:11:21 - error TS2694: Namespace '"......../node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

11     static ɵfac: i0.ɵɵFactoryDeclaration<SocialLoginModule, [{ optional: true; skipSelf: true; }]>;
                       ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/angularx-social-login/sociallogin.module.d.ts:12:21 - error TS2694: Namespace '"...../node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

12     static ɵmod: i0.ɵɵNgModuleDeclaration<SocialLoginModule, never, [typeof i1.CommonModule], never>;
                       ~~~~~~~~~~~~~~~~~~~~~

Error: node_modules/angularx-social-login/sociallogin.module.d.ts:13:21 - error TS2694: Namespace '"......../node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

13     static ɵinj: i0.ɵɵInjectorDeclaration<SocialLoginModule>;
                       ~~~~~~~~~~~~~~~~~~~~~


Error: ./node_modules/angularx-social-login/fesm2015/angularx-social-login.js 327:183-201
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/angularx-social-login/fesm2015/angularx-social-login.js 358:207-225
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/angularx-social-login/fesm2015/angularx-social-login.js 329:0-27
"export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/angularx-social-login/fesm2015/angularx-social-login.js 365:0-27
"export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/angularx-social-login/fesm2015/angularx-social-login.js 327:25-46
"export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/angularx-social-login/fesm2015/angularx-social-login.js 358:25-46
"export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/angularx-social-login/fesm2015/angularx-social-login.js 328:26-50
"export 'ɵɵngDeclareInjectable' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/angularx-social-login/fesm2015/angularx-social-login.js 360:25-47
"export 'ɵɵngDeclareInjector' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/angularx-social-login/fesm2015/angularx-social-login.js 359:25-47
"export 'ɵɵngDeclareNgModule' (imported as 'i0') was not found in '@angular/core'

**Comment by jaibatrik** [comment]
Hey, could you please use the last stable version before 4 (I think 3.5.7)?

**Comment by blueiceprj** [comment]
I have changed to old version 3.5.7 for now.

**Comment by jaibatrik** [comment]
Updated the peer dependency list and readme files. Closing this now.

**Comment by cheffNFT** [comment]
holy crap this is happening to me now.

**Comment by guliv3r** [comment]
hello any updates?

**Comment by TristanGrayCC** [comment]
Same happened here as well

**Comment by jaibatrik** [comment]
The solution is to use version 3.5.7 with Angular 11.

**Comment by rajesh-emagic** [comment]
> 3.5.7

right

**Comment by pablooliveira01** [comment]
> The solution is to use version 3.5.7 with Angular 11.

thx u

**Comment by timothyuijiatalor** [comment]
After downgrading to version 3.5.7 I'm still having this error 

Error: node_modules/angularx-social-login/sociallogin.module.d.ts:13:21 - error TS2694: Namespace '"C:/Users/Great Timo/Projects/RCCG/customers/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

 static ɵinj: i0.ɵɵInjectorDeclaration<SocialLoginModule>;
