### ISSUE TITLE
The package gives me alot of error on Angular 11.2.13

### ISSUE THREAD

**Issue by prosper1** [abacritt/angularx-social-login#429]
export 'ɵɵngDeclareInjectable' (imported as 'i0') was not found.

**Comment by jaibatrik** [comment]
Which version of the package are you using? You should be using version 3 with Angular 11.

**Comment by prosper1** [comment]
Amazing, Worked, Thank you .

So where is this written on the documentation, wouldnt something as important as this be bold and clear?

**Comment by jaibatrik** [comment]
Yeah. It was an omission. Fixed it now.
