### ISSUE TITLE
Specifying Scopes for Google

### ISSUE THREAD

**Issue by vgogov** [abacritt/angularx-social-login#43]
Hello,

Thanks for the work so far on this project! I'm trying to add more scopes to my access token. I'm guessing the default is:  "scope": "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/plus.me".

How would i go about adding more scopes? 

Cheers!

**Comment by kangw3n** [comment]
I've been adding this to pr #42 , please check there or fork it

**Comment by jaibatrik** [comment]
#42 is merged now, but not yet released in npm.

**Comment by jaibatrik** [comment]
Released to npm now. Kindly check and provide feedback.
