### ISSUE TITLE
No refresh token returned on signin

### ISSUE THREAD

**Issue by TristanGrayCC** [abacritt/angularx-social-login#438]
I need to save the google authToken and refreshToken in order to enable offline access when someone has signed in using their google credentials. I've been looking everywhere for a way to return the refreshToken as part of the signin request (or following the request) and come up short.

One place suggested using the accessType and approvalPrompt but despite adding these the response object doesn't have the refresh token.

Code:
this.authService
        .signIn(GoogleLoginProvider.PROVIDER_ID, {
          accessType: 'offline',
          approvalPrompt: 'force',
        })
        .then((x: any) => console.log(x);
        );
  
How can I get hold of the refresh token using this service?

**Comment by jaibatrik** [comment]
They are not returned in that `Promise`. You should subscribe to `authState` `Observable` to get the tokens.

**Comment by IKENMouad** [comment]
i'm facing the same issue and there's no refresh token in authState Observable , is there any solution for this ?

**Comment by TristanGrayCC** [comment]
Refresh tokens are not designed for front-end usage. Instead get the authToken, pass it to the server, and use it to exchange for an access-token and refresh-token there for offline use.

This can be closed.
