### ISSUE TITLE
Login providers not ready yet. Are there errors on your console?

### ISSUE THREAD

**Issue by maravondra** [abacritt/angularx-social-login#439]
I am integrating Facebook login using 
 - angularx-social-login 4.0.1 
 - Angular CLI: 12.1.4
 - Node: 14.17.3
I am getting the below error:
**ERROR Error: Uncaught (in promise): Login providers not ready yet. Are there errors on your console?**

```
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  constructor(
    public auth: AuthService,
    private authService: SocialAuthService,
    protected router: Router,
    private forme: FormeService) {
  }

  ngOnInit(): void {
    if (this.auth.isLoggedIn()) {
      this.router.navigate(['/mystudy'])
    }
  }

  signInWithFB(): void {
    console.log('log with fb')
    this.authService.signIn(FacebookLoginProvider.PROVIDER_ID).then((_) => {
      this.forme.getFacebookBearToken().subscribe((status: { 'token': string }) => {
        this.auth.saveBearerToken(status.token.split(' ', 2)[1])
        console.log('facebook login with token ' + status.token)
      })
    })
  }


}
```

**Comment by jaibatrik** [comment]
This is likely because you are trying to access the library functionality in `onInit` and the library is not ready by then. There is an `Observable` called `initState` which you can subscribe to watch when the library is initialized and ready.

**Comment by maravondra** [comment]
It is help
` this.authService.initState.subscribe(next => {
      console.log('authService observer')
      console.log(next)
      this.authLibraryReady = next
    })
`
