### ISSUE TITLE
FB.login() called before FB.init()

### ISSUE THREAD

**Issue by Mody-Napester** [abacritt/angularx-social-login#44]
Hi, i am facing a problem after package integration say's that FB.login() called before FB.init()
So what is the problem,
Any Help!!

**Comment by jaibatrik** [comment]
Can you please provide a sample for us to see the issue?

**Comment by yank07** [comment]
I have the same issue, it was because I was not putting a valid  Client ID.

```
let config = new AuthServiceConfig([
  {
    id: GoogleLoginProvider.PROVIDER_ID,
    provider: new GoogleLoginProvider('Google-OAuth-Client-Id')
  },
  {
    id: FacebookLoginProvider.PROVIDER_ID,
    provider: new FacebookLoginProvider('<PUT YOUR CLIENT ID>')
  }
]);
```

**Comment by Mody-Napester** [comment]
Thank you, it solved by correcting the Client ID
