### ISSUE TITLE
We should Migrate to the new Google Identity Services library

### ISSUE THREAD

**Issue by hiepxanh** [abacritt/angularx-social-login#442]
Yeah, they keep yelling, bla bla .... but we have time to 2023.
> [Action Required] Migrate to the new Google Identity Services library as soon as possible
> Hello Google Developer,
> 
> As announced earlier this month, the legacy Google Sign-In web solution will no longer be supported after March 31, 2023
> 

![image](https://user-images.githubusercontent.com/16970990/129129960-29d2fde5-10a7-4281-8217-fbd9559248c8.png)
https://developers.google.com/identity/gsi/web/guides/migration

**Comment by jaibatrik** [comment]
I'll try to incorporate this if I get time. Meanwhile, PRs are welcome!

**Comment by hiepxanh** [comment]
I'll look into it haha
