### ISSUE TITLE
google authorizationCode

### ISSUE THREAD

**Issue by utkarsh-jain13** [abacritt/angularx-social-login#447]
### Discussed in https://github.com/abacritt/angularx-social-login/discussions/421

<div type='discussions-op-text'>

<sup>Originally posted by **havart** June 25, 2021</sup>
Hello, 
Could you please help me understand where I can get the authorization code.
It is not in the response singIn.
![image](https://user-images.githubusercontent.com/12501647/123391084-50177700-d5a4-11eb-8999-bc7756a9f8cf.png)

My config: 
`googleLoginOptions = {
    scope: 'profile https://www.googleapis.com/auth/content',
    response_type: 'id_token permission code',
};`</div>

**Comment by ashish-developers** [comment]
Use onclick event and redirect to this url with your credential 

 `https://accounts.google.com/o/oauth2/v2/auth?scope=https://www.googleapis.com/auth/drive&access_type=offline&redirect_uri=http://localhost:4200&response_type=code&client_id=${this.youtubeClientId}`

**Comment by FatManiac** [comment]
I got the same issue, tried to put response_type in Options in module setting and on signIn function too, but the response type never change

Here someone talked about the same problem: https://github.com/abacritt/angularx-social-login/issues/349
