### ISSUE TITLE
Login by Facebook not working

### ISSUE THREAD

**Issue by thuctd** [abacritt/angularx-social-login#452]
Error: 
JSSDK Option is Not Toggled: Please toggle the "Login with Javascript SDK" Option to Yes in developers.facebook.com to use the JSSDK for Login.

**Comment by NyaGarcia** [comment]
This error isn't related to angularx-social-login, you just need to adjust the settings in your Facebook for Developers console:

To fix this, you need to enable the "Login with the JavaScript SDK" option in your Facebook App. To be able to do so, you will also need to add an allowed domain for the JavaScript SDK. You will find these settings in the Facebook Login > Settings tab. 

Here's a screenshot:

![image](https://user-images.githubusercontent.com/37065748/135879667-9df286be-fa49-48ec-b1a6-0c79ecb8d32c.png)

**Comment by Conzo427** [comment]
I am seeing the same problem on the Xbox site.  How do I find the developer page on FB?
