### ISSUE TITLE
Handle Social Provider load error

### ISSUE THREAD

**Issue by arnoldsi-vii** [abacritt/angularx-social-login#453]
Hi,
Facebook, as you probably know is down. If you use multiple providers and Facebook one of them, the socialAuthService.authState will never publish an event.
I would like to know if there is an ability to handle social provider load errors.
Thanks

**Comment by beldenge** [comment]
The problem as far as I can tell is in https://github.com/abacritt/angularx-social-login/blob/master/projects/lib/src/socialauth.service.ts on line 98.  That `.catch(console.debug);` just needs to be removed as it prevents the next catch which sends null into the authState.

**Comment by beldenge** [comment]
I went ahead and created a PR although I'm not a contributor on this project and have done super minimal testing of the fix.  https://github.com/abacritt/angularx-social-login/pull/454

**Comment by arnoldsi-vii** [comment]
@beldenge 
I think it's already failing here:
```
Promise.all(
      Array.from(this.providers.values()).map((provider) =>
        provider.initialize()
      )
    )
```

When javascript sdk is down, this promise is never get resolved. Just tested it by blocking js call
