### ISSUE TITLE
Change Angular 13 Peer Dependencies

### ISSUE THREAD

**Issue by BruneXX** [abacritt/angularx-social-login#463]
Please add support for angular 13

**Comment by shanmugapriyak1788** [comment]
Please add support for angular 13.

**Comment by dortegaoh** [comment]
Please add support for angular 13.

**Comment by anvouk** [comment]
Tested google login in angular 13 and it works (for now).

Force install with: `npm i --save --force angularx-social-login`.

**Comment by prashantchoudhary** [comment]
Surprisingly, version `3.5.4` installs without a warning.

**Comment by jpike88** [comment]
@jaibatrik looks like he went off the radar last July. I think this library might be abandoned.

**Comment by cacalo** [comment]
Tested both Facebook and Google login working with Angular 13.1.3

**Comment by jurgenru** [comment]
@cacalo i get errors everytime i try to install even with 13.1.3
![Screenshot from 2022-01-15 23-40-32](https://user-images.githubusercontent.com/37807383/149707969-dc0e54a1-32c5-4555-b1e0-c987de19b423.png)

**Comment by cacalo** [comment]
> @cacalo i get errors everytime i try to install even with 13.1.3 ![Screenshot from 2022-01-15 23-40-32](https://user-images.githubusercontent.com/37807383/149707969-dc0e54a1-32c5-4555-b1e0-c987de19b423.png)

Just add the "-f" flag to force the instalation. The library works just fine after you force install it.
I thought about bumping up the requirements of this repo and making a pull request, but I'm not sure that updating that would break it for some other people and I'm not expert enough to make a clean commit.

For the rest of the people with this issue, just force the install in angular 13.1.2

**Comment by jurgenru** [comment]
@cacalo thank you so much yo saved my life

**Comment by Heatmanofurioso** [comment]
Anyone know if the owner is still off the radar?

I'm heavily considering forking & maintaining this lib, the same way as I've done with another heavily used but abandoned lib.
But I only wanna do it as a last resort

**Comment by jurgenru** [comment]
> Anyone know if the owner is still off the radar?
> 
> I'm heavily considering forking & maintaining this lib, the same way as I've done with another heavily used but abandoned lib. But I only wanna do it as a last resort

I think something might happened because he doesn't appear since last year

**Comment by azack** [comment]
Try https://twitter.com/jaibatrik or email

**Comment by Heatmanofurioso** [comment]
I've tried contacting him on a few of the existing networks.

Will give feedback once I get an answer from him

**Comment by malachibazar** [comment]
@Heatmanofurioso I'd cone that fork

**Comment by Heatmanofurioso** [comment]
Cone? @malachibazar 
Sorry for not finishing the PR, but I've been a bit busy. Just need to fix an issue with testing, and it's ready I think

**Comment by ranma42** [comment]
@cenkerkumlucali are you using the latest version (i.e. https://www.npmjs.com/package/@abacritt/angularx-social-login )?
In my projects I have been successfully using it with Angular 13.

**Comment by Heatmanofurioso** [comment]
V13 support has been added.
As ranma42 well mentioned, the project is under a new org on NPM, so you'll have to change your dependency name to use the newer V13 versions

**Comment by 123NeNaD** [comment]
I tired the new version and it does not work for me:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: flatfee@1.9.3
npm ERR! Found: @angular/common@13.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.1.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.2.6" from @abacritt/angularx-social-login@1.1.0
npm ERR! node_modules/@abacritt/angularx-social-login
npm ERR!   @abacritt/angularx-social-login@"1.1.0" from the root project
```

**Comment by 123NeNaD** [comment]
I tried the new version and it does not work for me:
```
npm ERR! ERESOLVE unable to resolve dependency tree
...
npm ERR! Found: @angular/common@13.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.1.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.2.6" from @abacritt/angularx-social-login@1.1.0
npm ERR! node_modules/@abacritt/angularx-social-login
npm ERR!   @abacritt/angularx-social-login@"1.1.0" from the root project
```

**Comment by 123NeNaD** [comment]
Hi @ranma42,

Yeah, it would be great if you can create a PR and fix it.

I know I can upgrade Angular, but it's a big app so it can potentially break other things.

**Comment by Heatmanofurioso** [comment]
Hi @ranma42 
It'd be great if you could do a PR with that, for all Angular peer dependencies

**Comment by 123NeNaD** [comment]
Hi @Heatmanofurioso,

Can you also update the package in NPM? It still throws the same error after the merge.
