### ISSUE TITLE
Getting errors when trying to install in an angular project

### ISSUE THREAD

**Issue by jurgenru** [abacritt/angularx-social-login#472]
Everytime i try to install the library i get this error and when i force it is unable to use the project 
![Screenshot from 2022-01-17 01-12-58](https://user-images.githubusercontent.com/37807383/149711863-82578ac3-52f8-4307-b70c-c57008c31358.png)
![Screenshot from 2022-01-17 01-13-11](https://user-images.githubusercontent.com/37807383/149711873-3acbb4ae-189f-41fe-b453-0c8fbf53bc95.png)

**Comment by cacalo** [comment]
If you check the requirements of this library, it is specified that it officially supports up to angular 12 and you are trying yo use it in angular 13.
Nevertheless, it still works if you force install it. At least with Facebook and Google.

**Comment by jurgenru** [comment]
@cacalo yep sorry i didnt read it, but thank you a lot <3
