### ISSUE TITLE
403: access_denied / Invalid client for this origin

### ISSUE THREAD

**Issue by TLKG** [abacritt/angularx-social-login#475]
Angular v12 using `angularx-social-login` (v4.0.1) for Google Authentication, works out OK at local. Deploy to Azure as App Service, copy the URL paste into Google Cloud's `Authorized JavaScript origins` and `Authorized redirect URIs` in addition to existing `localhost:4200`.

Client ID is hardcoded into app.module.ts below, also and verified system variable `GOOGLE_APPLICATION_CREDENTIALS` is not matter.
```
providers: 
  [
    {
        provide: 'SocialAuthServiceConfig',
        useValue:
        {
            autoLogin: false,
            providers: 
            [
                {
                    id: GoogleLoginProvider.PROVIDER_ID,
                    provider: new GoogleLoginProvider('xyz123.apps.googleusercontent.com') 
                }
            ]
        } as SocialAuthServiceConfig,
    },
    ...
  ],  

``` 
           

After entering account and password get 403

    {
      "error" : "access_denied",
      "error_description" : "Invalid client for this origin."
    }

**Comment by XclaimR** [comment]
You need to add http://localhost without the port number to your `Authorized JavaScript origins` and `Authorized redirect URIs` as well
