### ISSUE TITLE
Blocked by privacy badger

### ISSUE THREAD

**Issue by zachsteffens** [abacritt/angularx-social-login#477]
Callbacks never get executed when privacy badger is installed. It must be disabled to work properly.

Anyone find a workaround for this issue?

**Comment by azack** [comment]
I see this behavior too with uBlock Origin.  When facebook domains are blocked, the FB api cannot be loaded when this plugin is loading, and it breaks all forms of social login (i.e. google login is broken even though only facebook was blocked).

**Comment by Heatmanofurioso** [comment]
Hey @zachsteffens 
Really seems to be part of the privacy badger's functionalities.

I think it makes a lot more sense to open an issue with them?

For possible workarounds, maybe try asking in https://github.com/abacritt/angularx-social-login/discussions

Makes a bit more sense than to open an issue for asking for workarounds
