### ISSUE TITLE
Push dist files

### ISSUE THREAD

**Issue by Boboss74** [abacritt/angularx-social-login#48]
Maybe you should push dist files we can find in the package.json like:

```
  "main": "./bundles/angularx-social-login.umd.js",
  "module": "./angularx-social-login.es5.js",
  "es2015": "./angularx-social-login.js",
  "typings": "./angularx-social-login.d.ts",
```

It would be possible to refer to a specific commit of your lib in the package.json dependencies

**Comment by jaibatrik** [comment]
But the files can be generated by going back to the specific commit and building the library again, isn't it?

**Comment by Boboss74** [comment]
I'm not sure to understand what you mean.

It seems weird (for me) to have to use npm package with ts libs.
I like the idea to be able to refer to a git project.

**Comment by jaibatrik** [comment]
Oh. Generally I do a `npm run build` followed by `npm publish dist` to publish the library to npm.

> I like the idea to be able to refer to a git project.

To use the dist files, won't it be enough to just clone the repo and then run `npm run build`? Please correct me if I am missing something?

**Comment by Boboss74** [comment]
It sounds like an useless additional step and boring to make the build process automated without pushing generated files from other project in our own repository.

With JavaScript libs, I use to see dist folder, like in projects:[Vue.js]( https://github.com/vuejs/vue), [jQuery.js](https://github.com/jquery/jquery,,) or [Three.js/](https://github.com/mrdoob/three.js/)...


In TypeScript, I found these with dist folder too
_https://github.com/NativeScript/NativeScript
https://github.com/sahat/satellizer
https://github.com/BabylonJS/Babylon.js
https://github.com/onivim/oni
https://github.com/jquery/esprima
https://github.com/ag-grid/ag-grid_

nb: I found more project without dist generated.

In any case, it seems that files referred from package.json should be git pushed.

**Comment by jaibatrik** [comment]
> In any case, it seems that files referred from package.json should be git pushed.

That sounds correct.

**Comment by jaibatrik** [comment]
But the package.json file gets copied to the dist folder where the relative paths become available. I was also wondering why you don't want to work with the TS files; is it that the project you are working on is not in TS?

**Comment by Boboss74** [comment]
> But the package.json file gets copied to the dist folder where the relative paths become available
Il all the previous Typescript project, there is no package.json inside the dist folder

> why you don't want to work with the TS files; is it that the project you are working on is not in TS?
I'm working with ts. but it seems that the way to do for ts libs is to use npm repository.

I will deal with it, it just make it "harder" to fork

**Comment by jaibatrik** [comment]
This is an old issue. I think the matter is subjective and the choice depends more on one's taste. Further, this does not block anything. I personally want angularx-social-login to be the type of library that does not push dist files.

If you download the library from npm, you get all the dist files anyway.

Closing this for now.
