### ISSUE TITLE
angularx-social-login issue

### ISSUE THREAD

**Issue by abdulrais** [abacritt/angularx-social-login#480]
I am using angular version 13.2.6. I am getting the below error while trying to install angularx-social-login:

npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from angularx-social-login@4.0.1
npm ERR! node_modules/angularx-social-login
npm ERR!   angularx-social-login@"4.0.1" from the root project

I tried below troubleshooting steps but had no luck:
1. npm install --save --legacy-peer-deps
2. npm audit fix --force

Deleted node modules and install again but still no luck.

Is this version of social-login not compatible with angular 13? Any kind of help is really appreciated.

**Comment by DaniVagyok** [comment]
same

**Comment by tendaikatsande** [comment]
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'signIn')
TypeError: Cannot read properties of undefined (reading 'signIn')
    at angularx-social-login.js:85:30
    at new ZoneAwarePromise (zone.js:1427:1)
    at GoogleLoginProvider.signIn (angularx-social-login.js:82:16)
    at angularx-social-login.js:267:26
    at new ZoneAwarePromise (zone.js:1427:1)
    at SocialAuthService.signIn (angularx-social-login.js:259:16)
    at AuthService.signInWithGoogle (auth.service.ts:20:23)
    at SigninComponent_Template_button_click_4_listener (signin.component.html:4:22)
    at executeListenerWithErrorHandling (core.mjs:14979:1)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:15017:1)
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at angularx-social-login.js:275:25
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.mjs:25548:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25535:1)
defaultErrorLogger @ core.mjs:6485
handleError @ core.mjs:6532
next @ core.mjs:26087
next @ Subscriber.js:91
_next @ Subscriber.js:60
next @ Subscriber.js:31
(anonymous) @ Subject.js:34
errorContext @ errorContext.js:19
next @ Subject.js:27
emit @ core.mjs:22427
(anonymous) @ core.mjs:25574
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.mjs:25447
onHandleError @ core.mjs:25574
handleError @ zone.js:376
runGuarded @ zone.js:147
api.microtaskDrainDone @ zone.js:1072
drainMicroTaskQueue @ zone.js:592
invokeTask @ zone.js:491
invokeTask @ zone.js:1648
globalCallback @ zone.js:1679
globalZoneAwareCallback @ zone.js:1712

**Comment by vinricardo** [comment]
Me too ;-;

**Comment by Pumayk26** [comment]
> Getting this Error on angular 13
> 
> ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'signIn') TypeError: Cannot read properties of undefined (reading 'signIn') at angularx-social-login.js:85:30 at new ZoneAwarePromise (zone.js:1427:1) at GoogleLoginProvider.signIn (angularx-social-login.js:82:16) at angularx-social-login.js:267:26 at new ZoneAwarePromise (zone.js:1427:1) at SocialAuthService.signIn (angularx-social-login.js:259:16) at AuthService.signInWithGoogle (auth.service.ts:20:23) at SigninComponent_Template_button_click_4_listener (signin.component.html:4:22) at executeListenerWithErrorHandling (core.mjs:14979:1) at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:15017:1) at resolvePromise (zone.js:1211:1) at zone.js:1118:1 at angularx-social-login.js:275:25 at _ZoneDelegate.invoke (zone.js:372:1) at Object.onInvoke (core.mjs:25548:1) at _ZoneDelegate.invoke (zone.js:371:1) at Zone.run (zone.js:134:1) at zone.js:1275:1 at _ZoneDelegate.invokeTask (zone.js:406:1) at Object.onInvokeTask (core.mjs:25535:1) defaultErrorLogger @ core.mjs:6485 handleError @ core.mjs:6532 next @ core.mjs:26087 next @ Subscriber.js:91 _next @ Subscriber.js:60 next @ Subscriber.js:31 (anonymous) @ Subject.js:34 errorContext @ errorContext.js:19 next @ Subject.js:27 emit @ core.mjs:22427 (anonymous) @ core.mjs:25574 invoke @ zone.js:372 run @ zone.js:134 runOutsideAngular @ core.mjs:25447 onHandleError @ core.mjs:25574 handleError @ zone.js:376 runGuarded @ zone.js:147 api.microtaskDrainDone @ zone.js:1072 drainMicroTaskQueue @ zone.js:592 invokeTask @ zone.js:491 invokeTask @ zone.js:1648 globalCallback @ zone.js:1679 globalZoneAwareCallback @ zone.js:1712

Did you find any solution for this issue..? Am getting this too...

**Comment by tendaikatsande** [comment]
In my case I had to whitelist localhost:4200 in the Google console. The so the error when I investigated it, the Google sigin in could not get initialized because localhost:4200 would have been rejected by Google hence the object becomes undefined.

**Comment by abdulrais** [comment]
I somehow figured out with "@angular/cli": "~12.0.0", version which is compatible with "angularx-social-login": "^4.0.1".

Hope this helps.

**Comment by yashitanamdeo** [comment]
> In my case I had to whitelist localhost:4200 in the Google console. When I investigated the error, the Google sigin in could not get initialized because localhost:4200 would have been rejected by Google hence the object becomes undefined.

Hey, I am facing a similar issue "TypeError: Cannot read properties of undefined (reading 'signIn')" 
Can you help me out with the steps to follow to be able to whitelist localhost:4200 ?

**Comment by benjaminsqlserver** [comment]
I resolved this by using "angularx-social-login": "^3.5.4"

**Comment by Heatmanofurioso** [comment]
Hey @abdulrais 

The most recent versions of the library that do support Angular 13 are in a different namespace in NPM.
Please check https://www.npmjs.com/package/@abacritt/angularx-social-login

Instead of installing `angularx-social-login`, you need to use `@abacritt/angularx-social-login`

**Comment by Heatmanofurioso** [comment]
Closing this one, since many people are using the library correctly with Angular 13, and the user seemed to be using the old version of the lib, and he seems to not be answering to the thread.

If you face any issues @abdulrais after migrating to the latest version of the lib, please reopen this Issue

**Comment by abdulrais** [comment]
thanks @Heatmanofurioso . Appreciate your help.
