### ISSUE TITLE
This document requires 'TrustedScript' assignment.

### ISSUE THREAD

**Issue by rahul6789sharma** [abacritt/angularx-social-login#490]
HI I am using social Login 
i am getting error after chrome update 

   this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID).then(
      (user: SocialUser) => {

// logic 

}

**Comment by programmer007007** [comment]
did u manage to solve it?

**Comment by rahul6789sharma** [comment]
No

**Comment by shlolevi** [comment]
i have the same issue, is there any solution ?

**Comment by sehcode** [comment]
I have the same issue and this is what I see on the Console in Chrome:

m=base:139 This document requires 'TrustedScript' assignment.
ne @ m=base:139
parse @ m=base:148
jh.v @ m=base:251
b @ m=base:263
m=base:139          POST https://accounts.google.com/_/IdpIFrameHttp/cspreport 400
ne @ m=base:139
parse @ m=base:148
jh.v @ m=base:251
b @ m=base:263
index.js:52 [WDS] Live Reloading enabled.
core.js:6498 ERROR Error: Uncaught (in promise): Login providers not ready yet. Are there errors on your console?
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at abacritt-angularx-social-login.mjs:269:17
    at new ZoneAwarePromise (zone.js:1427:1)
    at SocialAuthService.signIn (abacritt-angularx-social-login.mjs:267:16)
    at LoginComponent.login_with_google (login.component.ts:155:26)
    at LoginComponent_Template_button_click_19_listener (login.component.html:29:14)
    at executeListenerWithErrorHandling (core.js:15327:1)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:15365:1)
    at HTMLButtonElement.<anonymous> (platform-browser.js:561:1)
defaultErrorLogger @ core.js:6498
handleError @ core.js:6546
next @ core.js:29303
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25955
(anonymous) @ core.js:28718
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.js:28591
onHandleError @ core.js:28718
handleError @ zone.js:376
runGuarded @ zone.js:147
api.microtaskDrainDone @ zone.js:1072
drainMicroTaskQueue @ zone.js:592
invokeTask @ zone.js:491
invokeTask @ zone.js:1648
globalCallback @ zone.js:1679
globalZoneAwareCallback @ zone.js:1712

**Comment by Heatmanofurioso** [comment]
Hey. `@abacritt/angularx-social-login:1.2.0` has been deployed, can you test it with the new version if the lib, please?
