### ISSUE TITLE
Cannot read properties of undefined (reading 'signIn')

### ISSUE THREAD

**Issue by AndyVolf** [abacritt/angularx-social-login#496]
Hello, I have this error:

`abacritt-angularx-social-login.js:85 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'signIn')
    at abacritt-angularx-social-login.js:85:30
    at new Promise (<anonymous>)
    at GoogleLoginProvider.signIn (abacritt-angularx-social-login.js:82:16)
    at abacritt-angularx-social-login.js:267:26`

I do everything according to the instructions. As a result, I get here - `this.auth2 = gapi.auth2.getAuthInstance();` and here:
`const promise = !offlineAccess
                ? this.auth2.signIn(signInOptions)
                : this.auth2.grantOfflineAccess(signInOptions);` - undefined.
                
It's problem with Google. Facebook work good.

**Comment by inthegarage** [comment]
@AndyVolf Looks like the auth initialisation (deprecated problem also in this issue list) is causing the whole thing to bomb now. This happens on this library and the old one.

**Comment by inthegarage** [comment]
@AndyVolf I will provide an emergency PR to the owner, whether it's used remains to be seen.

**Comment by inthegarage** [comment]
@jaibatrik  Can I be added as contributor, my PR is ready.

**Comment by AndyVolf** [comment]
@inthegarage The most interesting thing is that I took the Client ID from the demo and everything works. Apparently, there is something with my Clint ID, but I can’t even understand what the problem is .. because I do everything according to the instructions from the Internet (I create an application and make an OAuth 2.0 Client ID for a web application)..

**Comment by inthegarage** [comment]
> @inthegarage The most interesting thing is that I took the Client ID from the demo and everything works. Apparently, there is something with my Clint ID, but I can’t even understand what the problem is .. because I do everything according to the instructions from the Internet (I create an application and make an OAuth 2.0 Client ID for a web application)..

I have the same problem, I didn't try the demo, but the Google API now throws an error instead of what I can only assume was just a warning message in the payload.
I'm not 100% convinced about my PR, but it would hopefully get people running whilst things are recoded.
In the meantime I followed this migration guide instead and that worked fully for me:
https://developers.google.com/identity/oauth2/web/guides/migration-to-gis

It can easily be placed into an Angular app, and is a lot less code than the previous solution. My advice would be to follow the migration guide and just do the auth yourself.

**Comment by jaibatrik** [comment]
Hey I'll review this over the weekend. Thanks for sending the PR.

**Comment by jaibatrik** [comment]
Oh, and I don't see any PR in the repo though.

**Comment by inthegarage** [comment]
@jaibatrik I couldn't submit one as I'm not a collaborator. If you wish please add me or suggest another way of doing this.

**Comment by Heatmanofurioso** [comment]
@inthegarage You can add one from a fork

**Comment by inthegarage** [comment]
@jaibatrik @Heatmanofurioso that is now complete. Please review and merge when you have time.

**Comment by Heatmanofurioso** [comment]
@inthegarage @AndyVolf 
The PR's been merged, and is going to be deployed now.
Can we close this specific issue?

**Comment by inthegarage** [comment]
@inthegarage Fine by me.
