### ISSUE TITLE
Founded Issuse in the package

### ISSUE THREAD

**Issue by Deep1218** [abacritt/angularx-social-login#500]
In API folder esm2015>providers>google-login-provider.js

this.loadScript(GoogleLoginProvider.PROVIDER_ID, 'https://apis.google.com/js/api.js', () => {
                    gapi.load('client:auth2', () => {
                        gapi.client.init(Object.assign(Object.assign({}, this.initOptions), { client_id: this.clientId }))
                            .then(() => {
                            this.auth2 = gapi.auth2.getAuthInstance();
                            resolve();
                        })
                            .catch((err) => {
                            reject(err);
                        });
                    });
                });

You guys have to change this Promise and the affected code.

Hope you will do this ASPS so we can use this package

**Comment by Heatmanofurioso** [comment]
There are already other issues tracking this issue. Closing, as it's a duplicated issue

#498 
#489
