### ISSUE TITLE
Add new Google Authentication mechanism provider

### ISSUE THREAD

**Issue by Heatmanofurioso** [abacritt/angularx-social-login#517]
Currently, the fix for https://github.com/abacritt/angularx-social-login/issues/489, was to update to the newest Google Authentication mechanism, which seems to be working, but we are forced to have further steps when signing in, which doesn't seem to make much sense.

This issue is to discuss & work on 2 things.
Decide if we wish to keep this method and add a new one, or just replace it for a more optimal solution.

Work & collaborate on a more optimal solution for Google Authentication.

**Comment by isaacfi** [comment]
Is there any way to not upgrade the angular version to use this fix? I'm actually using the 12 version

**Comment by isaacfi** [comment]
I updated to 13 and the button does not appear:

In the package.json
  ```
"dependencies": {
    "@abacritt/angularx-social-login": "1.1.0",
```
And in the HTML:
```
<div class="d-flex mb-2">
        <button type="button" class="btn facebook-btn" (click)="submitFacebookLogin()"><i
            class="fab fa-facebook-square"></i> {{'loginWithFacebook' | translate}}</button>
        <asl-google-signin-button></asl-google-signin-button>
</div>
```
![image](https://user-images.githubusercontent.com/647070/174671758-d503d80b-7bc8-4dd7-8bd0-03ceacee4476.png)

In the console, I'm still seeing (this had to be gone, right?): 
```
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
node_modules/webpack-dev-server/client/modules/logger/index.js:556
Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.
```
BR.

**Comment by Heatmanofurioso** [comment]
@isaacfi You can always open a PR from our latest V12 version, cherry-pick the changes onto it, and push it into a v12 support branch.

We're currently only maintaining support for V13 & V14, but I'd be happy to deploy a version of it if someone did that work.

**Comment by rat-matheson** [comment]
@Heatmanofurioso I'm stuck on angular v12 so I will try your suggestion and do a PR for v12.  

I believe this is the commit, right?

[Commit to cherry pick](https://github.com/abacritt/angularx-social-login/commit/65bf76e66222d666ccafcdc1851bec71604d70ca#diff-bbbef2dbf0187913045582b7cd75131a86cabfef5bd37134e4deb88d511eae87)

I'm having difficulty finding a v12 or v12 support branch.  Can you point me in the right direction?

[abacritt/angularx-social-login/branches/all](https://github.com/abacritt/angularx-social-login/branches/all)

**Comment by Heatmanofurioso** [comment]
Hi @rat-matheson
It's hard to suggest on that.
What you can do, is locally change the minimum version to 12, and test it out to see if it doesn't break.

If it's fine, you can add a PR with it.

I think V12 might have full compatibility

**Comment by rat-matheson** [comment]
@Heatmanofurioso That's a good approach.  I will try that if I can get unblocked.  I'm currently stuck on [this issue though](https://github.com/abacritt/angularx-social-login/issues/592) where I can't even get the demo app to work properly for google.

**Comment by rat-matheson** [comment]
This should be reopened until the change is merged in.   All the updates are complete,  just waiting for the merge

**Comment by aneshodza** [comment]
Can anyone update me on this issue? I updated to version [4.1.0](https://github.com/tralalere/angularx-social-login/blob/master/CHANGELOG.md#410), which should fix it, but non the less I keep getting the error:
![image](https://user-images.githubusercontent.com/75726773/206443265-4fa3114c-247e-4c9a-a8ae-cfd136db6d0e.png)
![image](https://user-images.githubusercontent.com/75726773/206443348-a8b8d8c6-47d4-4d1a-baf3-f484d963c1e7.png)
