### ISSUE TITLE
ReplaySubject fits perfect for AuthService (instead of BehaviorSubject)

### ISSUE THREAD

**Issue by Boboss74** [abacritt/angularx-social-login#52]
@jaibatrik , I think you should really have a look at this one:

[Challenges of AuthService with RxJs](https://stackoverflow.com/questions/44697159/angular-4-canactivate-observable-not-invoked/44701704#44701704)

[This is how I forked it](https://github.com/Boboss74/angularx-social-login/commit/255bf044ade619bc6a14ba4673dc02d7cace9e47#diff-fc44d3e9dbd69a283d10a34bedfb0443), just look at src/auth.service.ts, ignore the rest.

You can even implements ReplaySubject(1) on a new var/function, to let the dev to choose the kind of behavior they expect.

What do you think about it?

I can make a pull request if you are in

**Comment by jaibatrik** [comment]
Being discussed in https://github.com/abacritt/angularx-social-login/issues/81
