### ISSUE TITLE
Why are we loading Google login without the user's consent?

### ISSUE THREAD

**Issue by tawani** [abacritt/angularx-social-login#524]
Why are we loading Google login without the user's consent?
I need the user to explicitly click on their social login button. How can we do that?

**Comment by BruneXX** [comment]
Same issue here, I was performing logout and as soon as I redirected to login page the popup comes up, is there any workaround for this? thanks!

**Comment by sterichards** [comment]
Same here

The Google login appears automatically only by injecting SocialAuthService into a constructor

There is nothing in the documentation that helps me disable that behaviour 

I need to launch the Google login modal when I call it to do so

**Comment by gaessaki** [comment]
This is a bit of a hack, but I set the `prompt_parent_id` in initOptions to point to a div with `display: none;` to hide the prompt from the user. Hopefully PR https://github.com/abacritt/angularx-social-login/pull/588 will solve this.

**Comment by gapablaza** [comment]
Try defining "**googleLoginOptions**" with param "**oneTapEnabled**" set to "**false**" when defining the provider in **AppModule**:

```
const googleLoginOptions: GoogleInitOptions = {
  oneTapEnabled: false, // default is true
};

  ...
  providers: [
    {
      provide: 'SocialAuthServiceConfig',
      useValue: {
        autoLogin: false,
        providers: [
          {
            id: GoogleLoginProvider.PROVIDER_ID,
            provider: new GoogleLoginProvider(
              environment.google.token,
              googleLoginOptions
            ),
          },
        ],
        onError: (err) => {
          console.error(err);
        },
      } as SocialAuthServiceConfig,
    },
  ],
  ...
```
