### ISSUE TITLE
Bug when build

### ISSUE THREAD

**Issue by viniciosyals** [abacritt/angularx-social-login#53]
app.module
```
...
import { SocialLoginModule, AuthServiceConfig, FacebookLoginProvider } from 'angularx-social-login';

let config = new AuthServiceConfig([
	{
		id: FacebookLoginProvider.PROVIDER_ID,
		provider: new FacebookLoginProvider('416759688716123')
	}
]);

@NgModule({
...
	imports: [
...
		SocialLoginModule.initialize(config),
...
	],
...
})
export class AppModule { }
```

Error
![Error in console](https://image.prntscr.com/image/UjYhfGhuSXq0tKmRRSFi9g.png)

Package version.
```
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.6.2
webpack: 3.10.0
```

**Comment by wmx32** [comment]
This might be due to AoT, see https://github.com/abacritt/angularx-social-login/blob/master/README-AOT.md for more details.

**Comment by AlexandreMeledandri** [comment]
Hi, i had the same problem and followed the steps in the mentionned link but now the app doesn't load in the browser. It compiles in dev mode without error and it builds without errors too but it seems to loop endlessly on startup. Also, it doesn't give errors in the browser console.

**Comment by viniciosyals** [comment]
@wmx32 I'ill test it!

**Comment by Boboss74** [comment]
@AlexandreMeledandri Try to delete your node_modules (and yarn/npm install after of course)
It works for me (or maybe it was something else)

**Comment by viniciosyals** [comment]
@wmx32 works! Thanks =)
