### ISSUE TITLE
** Facebook login stopped WORKING **

### ISSUE THREAD

**Issue by Roman-Simik** [abacritt/angularx-social-login#537]
Today around 3 AM CES, it stopped working.

You can see it on your own [DEMO](https://abacritt.github.io/angularx-social-login/).

After clicking on FB icon -> 
![image](https://user-images.githubusercontent.com/41468539/178751717-6ff3f89a-5b37-4d22-9061-cc5ef43874ed.png)

**Comment by mslivinschi** [comment]
Hi, like temporary fix i can sugest you add in index.html 
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js"></script>

it will be loaded 2 times one in index.html , and two with loadScript from [BaseLoginProvider](https://github.com/abacritt/angularx-social-login/blob/f134053ad92bb61c283b5cd6e3d458fe33554adb/projects/lib/src/entities/base-login-provider.ts#L14) but it will fix your problem, if is critical for your site
