### ISSUE TITLE
Granting offline access with new OAuth flow

### ISSUE THREAD

**Issue by kkorniszuk** [abacritt/angularx-social-login#541]
Hello everyone - I noticed that I cannot use anymore `offlineAccess` flag - I used it to get Auth Code in order to exchange it on backend service for access token and refresh token. As I can see it's no more supported - do you know how to manage this flow with this package or without it?

**Comment by Heatmanofurioso** [comment]
Hi @kkorniszuk 
That flow isn't supported with the app, and we can't provide help on solutions that aren't with this package

**Comment by Aventrue** [comment]
I'm also really interessted how to do that and I'm googleing since one day without success. Can you give me a hint how I can exchange the access token from your library to a refresh token?
