### ISSUE TITLE
Google OneTap positioning

### ISSUE THREAD

**Issue by hheexx** [abacritt/angularx-social-login#542]
I can't style Google one tap.

https://stackoverflow.com/questions/62385138/change-google-one-tap-sign-in-positon-with-javascript

We need way to pass prompt_parent_id parameter to initialize function.

**Comment by Heatmanofurioso** [comment]
Hi @hheexx 
Would be a good Pull Request 😄

**Comment by hheexx** [comment]
https://github.com/abacritt/angularx-social-login/pull/543
