### ISSUE TITLE
Error: export 'skip' (imported as 'skip') was not found in 'rxjs'

### ISSUE THREAD

**Issue by iampaulfrolov** [abacritt/angularx-social-login#545]
When I am trying to run project I get this error

./node_modules/@abacritt/angularx-social-login/fesm2020/abacritt-angularx-social-login.mjs:449:37-41 - Error: export 'take' (imported as 'take') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/48531205/180089892-17f227c6-ac9d-45bc-96d3-bf1dc6fa3c54.png">

**Comment by Deepakds007b** [comment]
@iampaulfrolov Please install latest rxjs version.
npm install rxjs@latest

**Comment by deombernal** [comment]
Same thing here, been trying to find out a solution for days now.

**Comment by guru-dev-dan** [comment]
installing the latest worked for me

**Comment by veneliniliev** [comment]
> Same thing here, been trying to find out a solution for days now. I've tried installing latest rxjs version but got more error message after that.

 I have the same problem. please downgrade rxjs! :(

**Comment by Heatmanofurioso** [comment]
@iampaulfrolov Any news on this?
This isn't an issue related to the package, so if we can't help you anymore with this, I'd like to close this issue

**Comment by matpinsdorf** [comment]
same problems here. export 'skip' (imported as 'skip') was not found in 'rxjs'
