### ISSUE TITLE
Google scopes doesn't appear to work

### ISSUE THREAD

**Issue by sterichards** [abacritt/angularx-social-login#546]
I have followed the documentation and I have used the following provider:

`{
    id: GoogleLoginProvider.PROVIDER_ID,
    provider: new GoogleLoginProvider('xxxxx', {
        oneTapEnabled: false,
        scopes: 'https://www.googleapis.com/auth/user.phonenumbers.read'
    }),
}`
          
But the Google callback does not include the phone number

**Comment by Heatmanofurioso** [comment]
@sterichards Check if your app allows the phone number scopes
https://developers.google.com/people/v1/how-tos/authorizing
