### ISSUE TITLE
asl-google-signin-button

### ISSUE THREAD

**Issue by gorkirakosyan** [abacritt/angularx-social-login#554]
I have an issue with <asl-google-signin-button type="standard" size="large"></asl-google-signin-button> . Its placed in component which opens in dialog, first time its ok, but when I open dialog second  time, it shows only icon. 
Please help me solve this

**Comment by lo78cn** [comment]
I am using latest version (1.2.2) and face the same issue. Initially it shows the large icon button. After logout and redirect to login form, it shows a smaller icon button (defaults to medium?). Only a reload of the page shows the correct icon button size again.

```
<asl-google-signin-button type='icon' size='large'></asl-google-signin-button>
```

**Comment by mfrizqi** [comment]
for me it didnt work at all, any suggestion what should i do?
