### ISSUE TITLE
Thx Bro ,Hey, I found a solution that worked for me.

### ISSUE THREAD

**Issue by ChemaGomezST** [abacritt/angularx-social-login#559]
Hey, I found a solution that worked for me. 
Inside **app.module.ts** you have to add the following code in your _providers:_
```
providers: [
        {
          id: GoogleLoginProvider.PROVIDER_ID,
          provider: new GoogleLoginProvider(
            'clientId', {
              scope: 'email',
              plugin_name: 'login-app'
            }),
        }
      ], 
      onError: (err: any) => {
        console.error(err);
      },
    } as SocialAuthServiceConfig,
  },
  ],
```
where **plugin_name** must be the name you provided for your project in the google oauth api.

Hope this can help someone in need :)

_Originally posted by @davidmr163 in https://github.com/abacritt/angularx-social-login/issues/504#issuecomment-1142726408_

**Comment by Heatmanofurioso** [comment]
@ChemaGomezST Want to add a PR documenting this in the Readme?

**Comment by davidmr163** [comment]
@Heatmanofurioso it would be helpful

**Comment by davidmr163** [comment]
> @ChemaGomezST Want to add a PR documenting this in the Readme?

it would be really helpful

**Comment by Heatmanofurioso** [comment]
https://github.com/abacritt/angularx-social-login/issues/504#issuecomment-1142726408
