### ISSUE TITLE
FB Login

### ISSUE THREAD

**Issue by Goldtek** [abacritt/angularx-social-login#56]
fb login returns empty user after login but that of google works fine

**Comment by jaibatrik** [comment]
Could you please provide us a sample where this is happening? Have you checked the [demo application](https://abacritt.github.io/angularx-social-login/) to see whether the same thing is happening there?

**Comment by Goldtek** [comment]
i have sorted this out, another problem is that only the google gets the
token with facebook gets only refresh token, would love it if we could get
facebook token so as to be able to check for expiration on my app or site

**Comment by jaibatrik** [comment]
I think somebody did a PR and it got merged. I am unable to publish to npm due a build error. You can try using the library by cloning master.

**Comment by Goldtek** [comment]
ok

**Comment by jaibatrik** [comment]
Pushed to npm today.
