### ISSUE TITLE
can access the user details returned after login

### ISSUE THREAD

**Issue by Goldtek** [abacritt/angularx-social-login#57]
please acessing user object of type SocialUser to get a user authToken or get individual properties seems to break the app why? it useless getting a users login details without been able to use it, please look into ur package

**Comment by jaibatrik** [comment]
Could you please be more elaborate about your use case?

**Comment by mmmelo** [comment]
I've got the same issue. For instance: 

 this.authService.authState.subscribe( (user) => {
            this.user = user;
            console.log(user.email);
        });

ERROR TypeError: Cannot read property 'email' of null

What is it the best way to get it?

**Comment by jaibatrik** [comment]
The idea is that your subscription will always work. If the user is logged in, you will get a valid `SocialUser` object in your subscribed function. If the user has logged out, you'll get a null object. You can determine whether the user is logged in or not based on the null check. And you should wrap the usage of user data inside a not null block.
