### ISSUE TITLE
adding multiple scope on fbLoginOptions not working and FB login is not successful

### ISSUE THREAD

**Issue by shahin4u000** [abacritt/angularx-social-login#579]
I am currently using version 4 on my angular 13 app. While trying to add more scope on fbLoginOptions,  FB is throwing error like this: 

`Sorry, something went wrong. We're working on getting this fixed as soon as we can.
`

Here is how I tried to pass the scope as described. However, if I removed multiple scopes to a single scope it seems everything is working fine. Does anyone have this problem know what would be the solution?
```

const fbLoginOptions = {
  scope: 'pages_messaging,pages_messaging_subscriptions,email,pages_show_list,manage_pages'
}; // https://developers.facebook.com/docs/reference/javascript/FB.login/v2.11

this.authService.signIn(FacebookLoginProvider.PROVIDER_ID, fbLoginOptions);
```

**Comment by Heatmanofurioso** [comment]
@shahin4u000 Really seems to be an issue on Facebook's side of the equation.
Any more info you can provide on the issue?

**Comment by Heatmanofurioso** [comment]
@shahin4u000 Any news on this?
If not, I'd like to close this
