### ISSUE TITLE
social login working fine on web browser, but not after converting the app to android using capacitor

### ISSUE THREAD

**Issue by neerajp67** [abacritt/angularx-social-login#587]
Iam trying to allow users to login using facebook/google. On browser (laptop) it is working absolutly file, but when i am trying to do same with android (angular app converted using capacitor) I'm getting an error whenever calling login function: 
"Msg: ERROR Error: Uncaught (in promise): Login providers not ready yet. Are there errors on your console?"

**Comment by neerajpthinker** [comment]
Hi, 
This didn't work for me. 
Now I'm using 'codetrix-studio/capacitor-google-auth' for google sign in, and 'capacitor-community/facebook-login' for facebook sign in. 
Thanks

**Comment by neerajp67** [comment]
Hi,
This didn't work for me.
Now I'm using 'codetrix-studio/capacitor-google-auth' for google sign in, and 'capacitor-community/facebook-login' for facebook sign in.
Thanks

**Comment by CmarkoLukas** [comment]
Thank you so much for letting me know, can you tell please if those are working fine for Web browsers as well ? Was it hard to implement ? Thank you

**Comment by neerajp67** [comment]
yes, for me it's working fine on web and android. 
It's not hard to implement You can refer https://github.com/neerajp67/finger. The code is not well managed but you can use it for your reference.

**Comment by neerajp67** [comment]
yes, for me it's working fine on web and android.
It's not hard to implement. Just Follow the documentation instructions. Or can watch any relevant YouTube video.
