### ISSUE TITLE
Google login displaying one moment please in facebook browser & returning 403 disallowed agent

### ISSUE THREAD

**Issue by PiyushAgrawal1243** [abacritt/angularx-social-login#593]
Google Login not working properly in Facebook browser & Instagram browser.

It displaying "one moment please" with loader & 403 disallowed agent

![image (4)](https://user-images.githubusercontent.com/77185336/186854362-21446525-3d1d-43ac-a606-bd68b06dbe62.png)

Please help me if you know how can we tackle this problem and authenticate user.

**Comment by Heatmanofurioso** [comment]
Doesn't seem to be an issue with the lib, but with your app

**Comment by PiyushAgrawal1243** [comment]
> Doesn't seem to be an issue with the lib, but with your app

Please suggest some solutions so i can fix it.

**Comment by Heatmanofurioso** [comment]
> > Doesn't seem to be an issue with the lib, but with your app
> 
> Please suggest some solutions so i can fix it.


Not really sure how I can suggest a solution to an issue between your app, and google.

First, I don't have enough information to help you on that, and that is kinda outside of the scope of this library.

If you expand that Request Details tab, you can get more information @PiyushAgrawal1243

**Comment by PiyushAgrawal1243** [comment]
Hii , what i found in last few days ,

if we open our link in twitter it working fine  and user authenticated.
if we open link in linkedin it working fine.

if we open link in snapchat it gives 403 disallowed agent
if we open link in facebook it gives 403 disallowed agent and one moment please infinite loading.

if the problem in code then why am i able to login with google in twitter.

is there any way we can check google login supported or not so we can hide google login.
