### ISSUE TITLE
showing Error while import 'angularx-social-login module

### ISSUE THREAD

**Issue by gazee** [abacritt/angularx-social-login#597]
when i imported  following module s from angualrx-social-login  
 import { SocialLoginModule, SocialAuthServiceConfig } from 'angularx-social-login';
import {
  GoogleLoginProvider,
  FacebookLoginProvider
} from 'angularx-social-login';

i got error just like below in console and Failed to compile angualr project
 error TS2314: Generic type 'ɵɵPipeDeclaration' requires 2 type argument(s).

2319     static ɵpipe: ɵngcc0.ɵɵPipeDeclaration<PercentPipe, "percent", false>; 

when i remove above code angular compile is success

note:i use angular v-14

**Comment by ahmedhmedo73** [comment]
import from "@abacritt/angularx-social-login"
