### ISSUE TITLE
latest version not compiling on angular 13 projects

### ISSUE THREAD

**Issue by nik2208** [abacritt/angularx-social-login#602]
this is the message I get:
```
This application depends upon a library published using Angular version 14.2.0, which requires Angular version 14.0.0 or newer to work correctly.
```

I moved back to angularx-social-login@1.1.0 to make it work.

Is there any other solution (apart from moving to angular 14, I mean..)?

**Comment by cduerkes** [comment]
Because of breaking changes that were made to the compiler, in order to support both Angular 13 and 14, you may need to build the project using Angular 13: https://github.com/angular/angular/issues/46748#issuecomment-1178827913

**Comment by EliezerB123** [comment]
> Because of breaking changes that were made to the compiler with v14, in order to support both Angular 13 and 14, you may need to build the project using Angular 13: [angular/angular#46748 (comment)](https://github.com/angular/angular/issues/46748#issuecomment-1178827913)

As you say. The last version that supports Angular 13 appears to be version `1.2.3`, before the dependencies were updated.
