### ISSUE TITLE
LoginOpt interface is not accessible

### ISSUE THREAD

**Issue by iamSathishMohan** [abacritt/angularx-social-login#61]
![image](https://user-images.githubusercontent.com/22076855/36423807-4363588a-1667-11e8-818a-c6d47a77d81c.png)

**Comment by Gnorro** [comment]
Yes, same problem

Thanks for fixing

**Comment by vgogov** [comment]
It's all good, I just don't think the author @jaibatrik pushed it yet to NPM. Since on npm its v 1.1.1 while the latest version on GitHub is 1.1.4. Once the latest package is pushed, should all work :+1:

**Comment by jaibatrik** [comment]
Fixed and pushed to github, will push to npm shortly.

**Comment by jaibatrik** [comment]
Duplicate of #63

**Comment by jaibatrik** [comment]
Pushed to npm as well.
