### ISSUE TITLE
Google is trying to authenticate against https://play.google.com/log?format=json&hasfast=true&authuser=0

### ISSUE THREAD

**Issue by sterichards** [abacritt/angularx-social-login#610]
All of a sudden Google social sign on is not working for today after previously working

I am seeing a 401 in the browser network tab against a POST request to https://play.google.com/log?format=json&hasfast=true&authuser=0 which seems unusual

**Comment by MihalutFilip** [comment]
Same here

**Comment by alexhurtado-incae** [comment]
Same here

**Comment by franlaraa** [comment]
Same here
