### ISSUE TITLE
Google Auth Changes

### ISSUE THREAD

**Issue by ewwwgiddings** [abacritt/angularx-social-login#620]
I recently received an email stating that Google detected using their OAuth 2.0 login with an embedded webview. This is the headline of the email `We detected requests to our OAuth 2.0 authorization endpoint from one or more of your OAuth client IDs within an embedded webview context in the past 30 days.` What's odd though is I only use this in an Angular app for browser not in an app. It is related to this article:
https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html
Is this something that can or needs to be changed before the deadline? Or does it sound like an issue with something on my end?

Additionally is there any plan to migrate per this document and warning I see in the console:
https://developers.google.com/identity/gsi/web/guides/migration

Apologies if this is already fixed. I'm using `"angularx-social-login": "^4.1.0",` because of my angular version.

**Comment by signuspl** [comment]
I have the same with version 3.5.7 and Angular 11 and Ionic/Cordova app. Of course I use angularx-social-login only for WEB/PWA version but it is initialized in one of my angular modules. I received same email from Google.

**Comment by BruneXX** [comment]
Hi Guys, I'm highly interested in this topic, someone has any news about this? Thanks

**Comment by cacalo** [comment]
For anyone interested in it, this has been updated on the latests builds. You'll need to update in order for you to get the lastest features.

**Comment by PiyushAgrawal1243** [comment]
Hi Guys, anyone found any solution , i got the same mail.

**Comment by PiyushAgrawal1243** [comment]
> I recently received an email stating that Google detected using their OAuth 2.0 login with an embedded webview. This is the headline of the email `We detected requests to our OAuth 2.0 authorization endpoint from one or more of your OAuth client IDs within an embedded webview context in the past 30 days.` What's odd though is I only use this in an Angular app for browser not in an app. It is related to this article: https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html Is this something that can or needs to be changed before the deadline? Or does it sound like an issue with something on my end?
> 
> Additionally is there any plan to migrate per this document and warning I see in the console: https://developers.google.com/identity/gsi/web/guides/migration
> 
> Apologies if this is already fixed. I'm using `"angularx-social-login": "^4.1.0",` because of my angular version.

@ewwwgiddings  did you get any solution?
