### ISSUE TITLE
Wrong imports of rxjs?

### ISSUE THREAD

**Issue by alesyt0h** [abacritt/angularx-social-login#628]
Hello. 

I have an error trying to run ng serve when using this module. It basically says that **filter, take, skip** can't be imported from RxJS. After some digging I've found thtat **google-sigin-button.directive.ts** and **google-login-provider.ts** of this module are importing **filter, take and skip** from **rxjs** when it would have to be from **rxjs/operators**.

I've tried to just update the imports and recompile the module using **ng build lib --configuration production** to atleast be able to use this package, but that ended up in another error when running the application:
![image](https://user-images.githubusercontent.com/11640308/196110003-e948b23f-e406-4edd-9f92-933f5096ed24.png)

**Comment by CmarkoLukas** [comment]
npm install rxjs@latest helps :)
