### ISSUE TITLE
Autologin not working on browser refresh

### ISSUE THREAD

**Issue by Souvik-Root** [abacritt/angularx-social-login#632]
Autologin seems to be not working for me on browser refresh. I have set the property **'autoLogin: true'** as well. 

I am subscribed to the authstate, but after page refresh, socialUser is null. 

Here is the code - 

`
this.authService.authState.subscribe((user) => {
      this.user = user;
      this.loggedIn = (user != null);

      if (this.loggedIn) {
        this._snackBar.open('Welcome ' + user.firstName + ' ' + user.lastName + '!', 'Dismiss', {
          duration: 3000,
        });
      }
      else {
        this._snackBar.open('Logged out!', 'Dismiss', {
          duration: 3000,
        });
   }
`

**Comment by gjdass** [comment]
I confirm this.
I have an AuthService which serves me as a proxy for the real SocialAuthService.
Then I have AuthGuards that call my AuthService, which is itself subscribed to the SocialAuthService.

Alright, now the issue : when autoLogin is set to true (in order to keep my user logged-in and not force him to click on a button each time he visits my webapp), I get `ERROR TypeError: Cannot read properties of null (reading 'name')` errors in the console.

Also, calling `signOut()` function, even with a logged-in user, does not work. Same error.

```typescript
// my AuthService, subscribing to the SocialAuthService
export class AuthService {
  public user: SocialUser | undefined;
  public signedIn: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(
    false
  );

  constructor(private socialAuthService: SocialAuthService) {
    this.socialAuthService.authState.subscribe((user) => {
      console.log('Social auth triggered ' + user.name);
      this.user = user;
      this.signedIn.next(user !== null);
    });
    this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID);
  }

  signOut(): void {
    this.socialAuthService.signOut();
  }
}

// the AuthGuard, instantiating and calling the AuthService
export class AuthGuardService implements CanActivate {
  constructor(private router: Router, private authService: AuthService) {}

  public canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean | UrlTree> {
    return new Observable((subscriber) => {
      this.authService.signedIn.subscribe((signedIn: boolean) => {
        console.log('AuthGuardService:' + signedIn);
        if (signedIn) {
          return subscriber.next(true);
        }

        this.router.navigate(['login']);
        return subscriber.next(false);
      });
    });
  }
}
```

**Comment by theophane-girard** [comment]
Same problem here

**Comment by cody-01** [comment]
I had to enable oneTap to get it to work on refresh

`const googleOptions: GoogleInitOptions = {
  oneTapEnabled: true
};`

**Comment by Souvik-Root** [comment]
@cody-01 This doesn't seem to work for me. I have added this to the app.module.ts 

```
providers: [
        ...,
        {
            provide: 'SocialAuthServiceConfig',
            useValue: {
                autoLogin: true,
                providers: [
                    {
                        id: GoogleLoginProvider.PROVIDER_ID,
                        provider: new GoogleLoginProvider('Google-OAuth-Client-Id', { oneTapEnabled: true }),
                    },
                ],
                onError: (err) => {
                    console.error(err);
                }
            } as SocialAuthServiceConfig,
        }
    ],
```
