### ISSUE TITLE
Metadata version mismatch for module angularx-social-login.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by Gnorro** [abacritt/angularx-social-login#64]
Hi all

I don't understand if i have to install angular4-social-login or angularx-social-login

Here:
https://github.com/abacritt/angularx-social-login
under "Import the module" i see 
```
import { SocialLoginModule, AuthServiceConfig } from "angular4-social-login";
import { GoogleLoginProvider, FacebookLoginProvider } from "angular4-social-login";
```

but then 
```
import { AuthService } from "angularx-social-login";
import { FacebookLoginProvider, GoogleLoginProvider } from "angularx-social-login";
```

Which is the right one?
I ask because after uninstalling angular4-social-login and installing angularx-social-login, I f I add SocialLoginModule.initialize(config) in "imports" in app.module I get always error:
`ERROR in Error: Metadata version mismatch for module /node_modules/angularx-social-login/angularx-social-login.d.ts, found version 4, expected 3, resolving symbol AppModule in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts`

My version:
`@angular/cli: 1.4.7
node: 6.11.1
os: win32 x64
@angular/animations: 4.3.2
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/platform-server: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.4.7
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2
typescript: 2.5.3`

Thanks

**Comment by jaibatrik** [comment]
angularx is the right one. I'll update the README file.

**Comment by stewartrule** [comment]
I don't think this version works with Angular 4. I'm on Angular 4.4.6 and getting the same error. I'm only using the angularx version.

**Comment by priyesh-pandya** [comment]
I fixed this issue by this steps 

1. Make sure you delete old version **>> npm uninstall angularx-social-login@1.1.7** 
 Or 
 **>> npm uninstall angularx-social-login**

Note: 

- You can check version from package-lock.json 
-  If you can't uninstall just do hard delete of Dir node_modules/angularx-social-login


2. Delete the file **package-lock.json** 


3. Install the exact version  >> npm uninstall angularx-social-login@1.1.7

>> ng serve should work for you
