### ISSUE TITLE
SocialAuthService

### ISSUE THREAD

**Issue by JaiswalPiyush309** [abacritt/angularx-social-login#640]
when I declare 'private socialAuthService : SocialAuthService' in my login component constructor and run my project.  Then my login-component HTML page is not working [I think routing is  also not working it redirects my home page URL, not a login page URL, and when I explicitly hit login page URL but that time it also redirects home page] and  I got some error on my console

ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[SocialAuthService -> SocialAuthServiceConfig -> SocialAuthServiceConfig -> SocialAuthServiceConfig]: 
  NullInjectorError: No provider for SocialAuthServiceConfig!
NullInjectorError: R3InjectorError(AppModule)[SocialAuthService -> SocialAuthServiceConfig -> SocialAuthServiceConfig -> SocialAuthServiceConfig]: 
  NullInjectorError: No provider for SocialAuthServiceConfig!

**Comment by Marcodebo** [comment]
@JaiswalPiyush309  do you have a solution for this problem?
