### ISSUE TITLE
How Can I avoid a pop up users to log when refresh

### ISSUE THREAD

**Issue by zahasoftware** [abacritt/angularx-social-login#642]
I've implemented angular-social-login like this:

`<asl-google-signin-button type='standard' size='large' theme="filled_black"></asl-google-signin-button>`

But when I refresh It showed a popup with user, How can I disable this functionality?

![image](https://user-images.githubusercontent.com/13983901/204934657-188f8899-2bc5-4994-b18d-88002d7f72ae.png)

**Comment by jpike88** [comment]
I found it, tweak your app module to this:

```
{
								id: GoogleLoginProvider.PROVIDER_ID,
								provider: new GoogleLoginProvider(
									'BLAH BLAHABLAHL BLAH',
									{
										oneTapEnabled: false,
									}
								),
							},
```

**Comment by jpike88** [comment]
@Heatmanofurioso oneTapEnabled should be false by default, it's very confusing to newbies on this library and is quite invasive and can break SPAs

**Comment by nikxco** [comment]
On tap sign in is a great feature in terms of user experience… and it must supported out of the box, the problem is there should be a way to persist user state on the browser, maybe use cookies or local storage for maintaining/restoring the state 

I’m also facing the similar issues but not sure how to solve in a clean manner… @Heatmanofurioso

**Comment by Heatmanofurioso** [comment]
@jpike88 I agree.
Someone could propose a PR with the change, and I'll deploy it, if the community agrees

**Comment by mikila85** [comment]
i thought its one click on user to login so i removed it,... and since having trouble... thanks @jpike88

**Comment by ganholete** [comment]
Same problem. Even after the user is authenticated, when reloading the page, the popup appears again

**Comment by mikila85** [comment]
Ok "won't fix" will someone say how to code it so it will know the session? I mean there must be a way to save the "one tapped user" that has logged in and on init just set it to let the component know.. please help
