### ISSUE TITLE
Error handling 

### ISSUE THREAD

**Issue by vitto-moz** [abacritt/angularx-social-login#65]
During login it's possible to get an error: 
![image](https://user-images.githubusercontent.com/19843391/37481199-d69672d4-2889-11e8-92b2-bf2e87df08b0.png)
It would appear because of adblocker or the user manually would close a "sign in"  window
How can I handle this error?

**Comment by jaibatrik** [comment]
Somebody made a PR that enhanced the error handling. Are you using the latest version of the library?

**Comment by jaibatrik** [comment]
All PR are merged and pushed to npm.
