### ISSUE TITLE
GoogleSigninButtonDirective wont work in Sub-Modules

### ISSUE THREAD

**Issue by alexfriesen** [abacritt/angularx-social-login#652]
I am working on a large Application and we separated all peaces in lazy loaded modules. One of those is our `AuthModule`. 

Unfortunately the `GoogleSigninButtonDirective` wont render anything within our `AuthModule` and it's forbidden to import `SocialLoginModule` somewhere else than `AppModule`. 

As a workaround we downgraded to version 4.0.1 which works with a self made auth-button.

**Comment by fifiDesPlaines** [comment]
Same problem

**Comment by exequiel09** [comment]
The button should be made SCAM or a standalone component

**Comment by LiJell** [comment]
same issue here
