### ISSUE TITLE
FB login is not working give error, something went wrong

### ISSUE THREAD

**Issue by sdupworkuser** [abacritt/angularx-social-login#653]
I am currently using version 4 on my angular 12 app. While trying to login with bellow options on fbLoginOptions, FB is throwing error like this:

`Sorry, something went wrong. We're working on getting this fixed as soon as we can.`

Option 

`const fbLoginOptions = {
  scope: 'pages_messaging,pages_messaging_subscriptions,email,pages_show_list,manage_pages,public_profile',
  return_scopes: true,
  enable_profile_selector: true,
  auth_type: 'rerequest'
};
this.authService.signIn(FacebookLoginProvider.PROVIDER_ID, fbLoginOptions);`

Can anyone please help me with this!

**Comment by Heatmanofurioso** [comment]
@sdupworkuser We've added a new `master-ngx12` branch to update the V12 support.
Can you test it in there, please?
