### ISSUE TITLE
Typo in the documentation on npm website

### ISSUE THREAD

**Issue by kurti-vdb** [abacritt/angularx-social-login#659]
There is a typo in the documentation on the npm website, the import is wrong, still pointing to the deprecated version.

`import { SocialLoginModule, SocialAuthServiceConfig } from 'angularx-social-login';
import {
  GoogleLoginProvider,
  FacebookLoginProvider
} from 'angularx-social-login';`

https://www.npmjs.com/package/@abacritt/angularx-social-login

**Comment by Heatmanofurioso** [comment]
@kurti-vdb Thanks for noting.
I've updated the doc according to the readme.
Closing this
