### ISSUE TITLE
Google 'PROMPT' sign in option is not available

### ISSUE THREAD

**Issue by ahamarasinghe** [abacritt/angularx-social-login#66]
Current Behavior:
Once a user sign in with an account this will always use the same account on the consecutive logins without asking/promting the user.

Expecting Behavior:
Every time a user sign in Google will prompt the accounts to select among them.

Solution:
Google has a sign in option called **'promt'** and we need to set value of this to 'select_account' to get the above explained behavior. 
In the **LoginOpt** interface this is not available therefor users can't set it. Adding this **'prompt'** to the **LoginOpt** interface will fix this.

[google documentation](https://developers.google.com/api-client-library/javascript/reference/referencedocs#googleauthsigninoptions)

**Comment by Augustomesquita** [comment]
This also happens using Facebook API Login. Always using same account. Is there something that I can do to get around it?

**Comment by rubentrf** [comment]
As @jaibatrik said, they're going to test it a little more before a final 1.1.9 release to npm. You can always clone the repo yourself and include it into your node modules to give it a try.

Keep in mind that I focused on the Google Login option, haven't tested it with FB.

**Comment by jaibatrik** [comment]
I think it _is_ available in the latest npm release. Currently, the npm should be updated with the latest master changes.

**Comment by jaibatrik** [comment]
let me know if you are not finding it in the npm release.

**Comment by ahamarasinghe** [comment]
@jaibatrik 
Still we are receiving version 1.1.8 from the npm, since the fix is not available.

**Comment by jaibatrik** [comment]
Current version released to npm is 1.2.0

**Comment by laertispappas** [comment]
Is this fixed for facebook as well?

**Comment by nikhilbhalwankar** [comment]
Try below fix, It works for Google Login supporting multiple accounts to choose from in the popup.

https://github.com/abacritt/angularx-social-login/issues/205#issuecomment-541348868
