### ISSUE TITLE
The older Google Sign-In JavaScript platform library for Web is set to be deprecated after March 31, 2023, Will it support the integration?

### ISSUE THREAD

**Issue by Shani360** [abacritt/angularx-social-login#660]
https://developers.google.com/identity/gsi/web/guides/migration#authentication_and_authorization

`GoogleLoginProvider`

**Comment by gonzalo-lorieto** [comment]
https://github.com/abacritt/angularx-social-login/discussions/648

**Comment by Heatmanofurioso** [comment]
Thank you @gonzalo-lorieto 
Closing this, as it's been answered
