### ISSUE TITLE
Prevent Google One Tap if user already logged in

### ISSUE THREAD

**Issue by hheexx** [abacritt/angularx-social-login#661]
Is there a way to prevent showing google one tap during page load ?

**Comment by NourasHamwi** [comment]
Any solution for this scenario ?

**Comment by NourasHamwi** [comment]
My temporary work around it is this


`   
const googleLoginOptions: GoogleInitOptions = {
  oneTapEnabled: localStorage.getItem('accessToken') ? false : true, // default is true
};

 providers: [
        {
          provide: 'SocialAuthServiceConfig',
          useValue: {
            autoLogin: false,
            providers: [
              {
                id: GoogleLoginProvider.PROVIDER_ID,
                provider: new GoogleLoginProvider(
                  environment.clientId,
                  googleLoginOptions
                ),
                
              },
            ],
            onError: (err) => {
              console.error(err);
            }
          } as SocialAuthServiceConfig,
        },

      ],`
