### ISSUE TITLE
Can not use google one tap in angular 11

### ISSUE THREAD

**Issue by HenryLee2703** [abacritt/angularx-social-login#669]
Hi all, I'm migrating from `angularx-social-login` to `@abacritt/angularx-social-login` , 
The reason is google updated google-one-tap, so I've updated google service on my project. I've checked the version in `@abacritt/angularx-social-login`  but maybe it not support on Angular version that I used is 11, it's been for a long time and hard to ugrade version to 13. 

Are there any way that using Angular 11 and google one tap feature ( one of the newest version of library)
Thanks

**Comment by Heatmanofurioso** [comment]
Hi @HenryLee2703 
We've increased the minimum supported version.
If you wish, you can do a PR to a side-branch changing the supported version to 11.

Test it out. If it works, I don't mind releasing an updated V11 support version
