### ISSUE TITLE
Getting `popup_closed_by_user` after selecting  a google account to sign in with

### ISSUE THREAD

**Issue by oluwaetosin** [abacritt/angularx-social-login#67]
![image](https://user-images.githubusercontent.com/5717333/37641387-d741544a-2c19-11e8-8e0c-4218978cea83.png)

Google sign in attempt (in ionic app) returns with error : "popup_closed_by_user" when indeed popup was not closed by user.

**Comment by prabeen04** [comment]
I am also having the same issue after upgrading everything including angular, rxjs, typescript...

**Comment by adamnurdin01** [comment]
Waiting for this solution ... :D

**Comment by prabeen04** [comment]
the way I fix this is to update the version nos of all dependencies and dev dependencies to the versions used in demo of this repo. In that case Facebook and google is behaving normal but LinkedIn pop up is automatically opening when I open the application. In my case everything is in the / route.

**Comment by DarkSlayerK** [comment]
I fix this error by changing platform.js to api.js

**Comment by odahcam** [comment]
Is the fix in any release or pre-release?

**Comment by loicsalou** [comment]
same issue for me. Any plan for a realease soon ?

**Comment by fdonzello** [comment]
same here..

**Comment by fdonzello** [comment]
Is the maintainer considering to allow some dev to handle the pull requests? Righ now, the project is dead.

**Comment by jaibatrik** [comment]
One can certainly create a PR if they have a proper fix. The PR that changed platform.js to api.js could not site a reference.

**Comment by jerintk** [comment]
**Not a solution**, but if you guys just want to evade from the exception, use an error handler and handle it your own way, based on your logic.

For more about error handlers: https://medium.com/angular-in-depth/expecting-the-unexpected-best-practices-for-error-handling-in-angular-21c3662ef9e4

Mine was not a complex project. So here is what I have done.

- **global-error-handler.ts**
```
import { ErrorHandler, Injectable } from '@angular/core';

@Injectable()
export class GlobalErrorHandler implements ErrorHandler {

  handleError(error: Error) {
    console.log('Global Handler: ', error.name + ', ' + error.message);
  }
}
```

- **app.module.ts**
`providers: [
    {
      provide: ErrorHandler,
      useClass: GlobalErrorHandler
    }
  ]`

**Comment by mebibou** [comment]
Why is this issue closed even though it's still an issue with latest version?

**Comment by jaibatrik** [comment]
> Why is this issue closed even though it's still an issue with latest version?

The library has changed a lot from when this issue was created. This will be tracked with #353.

**Comment by Pumayk26** [comment]
still Am having this issue in 2021.. v4.0.1 on angular 12... Anyone found a solution..?

**Comment by bierzorutas** [comment]
Same problem still here with NG 12, no way to use this module in an older versions, should be marked as not compatible with NG < 14
