### ISSUE TITLE
not able to install in angular  version 14

### ISSUE THREAD

**Issue by joshigolu08** [abacritt/angularx-social-login#670]
i tey :-> npm i @abacritt/angularx-social-login@abacritt/angularx-social-login:1

and got this error

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/abhishek/Desktop/project/client/@abacritt/angularx-social-login:1/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/abhishek/Desktop/project/client/@abacritt/angularx-social-login:1/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by Heatmanofurioso** [comment]
@joshigolu08 You're trying to download a version `1` of the package.
The first version of `@abacritt/angularx-social-login` is `1.0.0`

Please check https://www.npmjs.com/package/@abacritt/angularx-social-login?activeTab=versions for the list of versions of the package

**Comment by rkdevstack** [comment]
npm i @abacritt/angularx-social-login
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: wasp-tek@0.2
npm ERR! Found: @angular/common@14.3.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=16.0.0" from @abacritt/angularx-social-login@2.1.0
npm ERR! node_modules/@abacritt/angularx-social-login
npm ERR!   @abacritt/angularx-social-login@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/rockybhai/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rockybhai/.npm/_logs/2023-05-16T17_58_28_908Z-debug-0.log
