### ISSUE TITLE
Error: Rxjs operators imports using angular 15

### ISSUE THREAD

**Issue by renan-alves** [abacritt/angularx-social-login#672]
PR: https://github.com/abacritt/angularx-social-login/pull/671

fixing errors by changind import path:

export 'take' (imported as 'take') was not found in 'rxjs'
export 'take' (imported as 'skip') was not found in 'rxjs'
export 'take' (imported as 'filter') was not found in 'rxjs'
found while installing the library in an angular 15 project

**Comment by dhananjayve** [comment]
I have added this lib using npm i @abacritt/angularx-social-login
this does not work yet.
please push this to npm

**Comment by Heatmanofurioso** [comment]
Which version of rxjs do you have installed @dhananjayve ?
Care to share your package-lock?

**Comment by dhananjayve** [comment]
Hello I am using rxjs 6.6.0

[package-lock.zip](https://github.com/abacritt/angularx-social-login/files/10784792/package-lock.zip)

**Comment by Heatmanofurioso** [comment]
The project is supporting `7.8.0` @dhananjayve 
Some APIs have changed. If you're forcing `6.6.0` there will be incompatibilities.
