### ISSUE TITLE
recently when "npm build" and "npm start" such an error, although before that everything worked fine

### ISSUE THREAD

**Issue by JuliaHorokhovatska** [abacritt/angularx-social-login#676]
![image](https://user-images.githubusercontent.com/111287515/221807328-a40ee9ac-2d7a-4c74-8f10-ae0114997238.png)

![Screenshot from 2023-02-28 11-19-27](https://user-images.githubusercontent.com/111287515/221808368-cc49e69e-1481-467b-89cd-4ea0eb363f15.png)

**Comment by gitshams** [comment]
@JuliaHorokhovatska not working

**Comment by Siebe-Uyttersprot** [comment]
Same problem here, changing version in package.json not doing anything
