### ISSUE TITLE
Getting error by Google login directive.

### ISSUE THREAD

**Issue by PiyushAgrawal1243** [abacritt/angularx-social-login#703]
![image](https://user-images.githubusercontent.com/77185336/236410575-8a266839-eff1-449b-bfca-ea7d1c828f35.png)

i am getting this error.

My package.json is 

  "dependencies": {
    "@abacritt/angularx-social-login": "^2.0.0",
    "@angular-material-components/datetime-picker": "^8.0.0",
    "@angular-material-components/moment-adapter": "^8.0.0",
    "@angular/animations": "^14.2.3",
    "@angular/cdk": "^14.2.2",
    "@angular/common": "^14.2.3",
    "@angular/core": "^14.2.3",
    "@angular/forms": "^14.2.3",
    "@angular/localize": "^14.2.3",
    "@angular/material": "^14.2.2",
    "@angular/platform-browser": "^14.2.3",
    "@angular/platform-browser-dynamic": "^14.2.3",
    "@angular/router": "^14.2.3",
    "@material-extended/mde": "^3.0.3",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@ngxs/storage-plugin": "^3.7.1",
    "@ngxs/store": "^3.7.1",
    "@swimlane/ngx-datatable": "20.0.0",
    "angular-google-tag-manager": "1.6.1",
    "bootstrap": "^4.4.1",
    "i": "^0.3.6",
    "ngx-bootstrap": "^5.3.2",
    "ngx-captcha": "^12.0.2",
    "ngx-color-picker": "^8.2.0",
    "ngx-csv-parser": "1.2.0",
    "ngx-google-places-autocomplete": "^2.0.5",
    "ngx-infinite-scroll": "^8.0.0",
    "ngx-quill": "13.2.0",
    "ngx-youtube-player": "^12.0.1",
    "ngxs-reset-plugin": "^2.0.0",
    "quill": "^1.3.6",
    "rxjs": "~6.6.6",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.3",
    "@angular/cli": "^14.2.3",
    "@angular/compiler": "^14.2.3",
    "@angular/compiler-cli": "^14.2.3",
    "@angular/language-service": "^14.2.3",
    "@ngxs/devtools-plugin": "^3.7.1",
    "@schematics/angular": "^12.2.9",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^14.14.31",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage": "^2.0.3",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "~7.0.0",
    "sonar-scanner": "^3.1.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.3",
    "typescript": "~4.6.4"
  }

**Comment by PiyushAgrawal1243** [comment]
@Heatmanofurioso 
 can you please check and let me know whats wrong.
 Thanks

**Comment by anasvikh** [comment]
Hi! Try to use @abacritt/angularx-social-login@1.3.2

**Comment by anasvikh** [comment]
Hi! Try to use @abacritt/angularx-social-login:1.3.2
