### ISSUE TITLE
unable to install in angular 14 

### ISSUE THREAD

**Issue by rkdevstack** [abacritt/angularx-social-login#707]
I tired with 
npm i @abacritt/angularx-social-login:1

npm i @abacritt/angularx-social-login@1.0.0
npm i @abacritt/angularx-social-login:1.3.0
npm i @abacritt/angularx-social-login

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: wasp-tek@0.2
npm ERR! Found: @angular/common@14.3.0
npm ERR! node_modules/@angular/common
npm ERR! @angular/common@"^14.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=16.0.0" from @abacritt/angularx-social-login@2.1.0
npm ERR! node_modules/@abacritt/angularx-social-login
npm ERR! @abacritt/angularx-social-login@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/rockybhai/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/rockybhai/.npm/_logs/2023-05-16T17_58_28_908Z-debug-0.log

**Comment by nttruong21** [comment]
you should try a lower version (1.2.5)

**Comment by justincastlight** [comment]
I had a similar issue while installing angularx-social-login on Angular 14. My project is running on Angular 14, as per doc For angular 13,14 and 15 we should use  @abacritt/angularx-social-login:1 | 13, 14, 15. I tried installing versions 1.3.0 and 1.3.2, its throwing a dependency error. When I installed 1.2.6 it is successful but in run time its giving some rxjs error

.```
/node_modules/@abacritt/angularx-social-login/fesm2020/abacritt-angularx-social-login.mjs:42:27-31 - Error: export 'skip' (imported as 'skip') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

./node_modules/@abacritt/angularx-social-login/fesm2020/abacritt-angularx-social-login.mjs:61:34-40 - Error: export 'filter' (imported as 'filter') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

./node_modules/@abacritt/angularx-social-login/fesm2020/abacritt-angularx-social-login.mjs:117:39-43 - Error: export 'take' (imported as 'take') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)




```
