### ISSUE TITLE
Error TS2307 :can not find module 'rxjs' and '"angular/core'

### ISSUE THREAD

**Issue by MohitSChauhan** [abacritt/angularx-social-login#72]
![issue1](https://user-images.githubusercontent.com/37956082/38163251-9b07fdf0-350e-11e8-96eb-d2550297f2e8.png)

**Comment by jaibatrik** [comment]
Can you post your `package.json` file?

**Comment by hopefulRialist** [comment]
same issue. attached is my package.json file
[package (copy).txt](https://github.com/abacritt/angularx-social-login/files/2717239/package.copy.txt)

**Comment by kaiserkumars** [comment]
Facing same issue. Below are the contents of package.json file:
`{
  "name": "frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.11",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/forms": "~8.0.1",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/router": "~8.0.1",
    "bootstrap": "^4.3.1",
    "jquery": "^3.4.1",
    "ngx-toastr": "^10.2.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.3",
    "@angular/compiler-cli": "~8.0.1",
    "@angular/language-service": "~8.0.1",
    "@types/jasmine": "^3.3.16",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.6",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}
`
