### ISSUE TITLE
Google changed something about login button render

### ISSUE THREAD

**Issue by blueiceprj** [abacritt/angularx-social-login#722]
On GoogleSigninButtonDirective class "width" type of property must be number and you have to pass this value as a number. Except it throw an error. Or without using width property it working properly

**Comment by johnchege159** [comment]
is there a quick fix to this?

**Comment by AntoninKadrmas** [comment]
Hi I had same problem and I fixed it by changing property `width="300"` of `asl-google-signin-button` component to `width="300px"`.

**Comment by aluuu** [comment]
Same problem is discussed in #720.
