### ISSUE TITLE
file to big in bundle 

### ISSUE THREAD

**Issue by amanecer2** [abacritt/angularx-social-login#73]
When compressed in --prod mode. The library is way to big in the bundle main file.
State size (not compressed): 1023.31 KB
Parsed size( minified): 190.23 KB
Gziped size: 35.42 KB.

![image](https://user-images.githubusercontent.com/8917429/38315646-916e90d0-3831-11e8-8167-f4f41451b57b.png)

**Comment by nishesj** [comment]
Seems like its including whole Rxjs lib

**Comment by jaibatrik** [comment]
I see the following in build.js - 

```
commonjs({
    include: ['node_modules/rxjs/**']
})
```

Looks like this is causing the trouble. May be this should go to external dependencies or globals?

**Comment by jaibatrik** [comment]
Removed the above line from build.js and published version 1.2.0@npm. Somebody should test the functionality properly.
