### ISSUE TITLE
Update to Angular v17

### ISSUE THREAD

**Issue by tsenguunchik** [abacritt/angularx-social-login#734]
As title

**Comment by ValeryYuntsevichUltralab** [comment]
Dear all,
This update is very welcomed by my team as well. We are looking forward to it too.

**Comment by jdlee726** [comment]
Is there any temporal workaround?

**Comment by tsenguunchik** [comment]
> Is there any temporal workaround?

This version is still working for my v17 project. It would be just nice to get the support

**Comment by cacalo** [comment]
While I'm hoping for proper ng17 support, I guess that making this work in an module-less environment might require a significant rewrite.
A simple bump in the library requirements would be sufficient to use this without a --force.

**Comment by Heatmanofurioso** [comment]
Hi all

I will work on this on this weekend.
Please bear with me, as this is a project that I'm maintaining on my free time, which is not that much

Thanks

**Comment by Heatmanofurioso** [comment]
PRs are also welcome :)
