### ISSUE TITLE
Package scope/org proposal

### ISSUE THREAD

**Issue by odahcam** [abacritt/angularx-social-login#74]
Hey, I've tryied and sucecssful registered NPM's scope `@social-auth`. I saw that `ngx-social-auth` is already in use, so I seek for a cooler name and I think I got it.

You can publish the package under the scope and also take profit on publish the social providers as separated packages like `@social-auth/ngx-facebook-provider`, `@social-auth/ngx-google-provider`, etc.

Also, it would reduce the main package size, once devs would download only the providers they want to use.

PS.: I found the demo very, very exciting.

**Comment by jaibatrik** [comment]
Sounds good, may be someone can send a PR?

**Comment by jaibatrik** [comment]
Given only Facebook and Google provide JS only SDKs, the chances of modularizing further is low.
