### ISSUE TITLE
SocialAuthService should not be provided in 'root'

### ISSUE THREAD

**Issue by DmitryEfimenko** [abacritt/angularx-social-login#771]
Providing it in root means that a lot of the dependencies pertaining to social login need to be loaded on the application start.
If I want to defer loading of social login related functionality, I need a way to provide `SocialAuthServiceConfig` at the component level. This requires providing `SocialAuthService` also at the component level.

**Comment by DmitryEfimenko** [comment]
actually, manually providing it at the component level does the trick already. Closing this

**Comment by mallajay** [comment]
How you solve it it seems this problem is coming for me after upgrade to 2.4.0
