### ISSUE TITLE
LinkedIn Login not working when I am integrating it with my application.

### ISSUE THREAD

**Issue by AchintMaheshwari** [abacritt/angularx-social-login#79]
![image](https://user-images.githubusercontent.com/38721943/39240803-7a231ae6-48a2-11e8-8ece-5d7a14de7ead.png)
This is the error I am getting when I am integrating the social login for linkedin.
Kindly help me on this.

**Comment by devotebest** [comment]
@AchintMaheshwari 
I got same error.
Do you find solution?
Thanks

**Comment by devotebest** [comment]
@AchintMaheshwari 
Do you have any good news?
Looking forward to your hearing.
Thanks

**Comment by isaleem** [comment]
Added a comment on https://github.com/abacritt/angularx-social-login/issues/97, can you confirm if it helps.

**Comment by jaibatrik** [comment]
Duplicate of #97
