### ISSUE TITLE
Ionic

### ISSUE THREAD

**Issue by w0dm4n** [abacritt/angularx-social-login#8]
Hey, the module is working well on a simple browser but in a ionic app (with angular 4) the popup for signing in doesn't pop up.

**Comment by c00** [comment]
You can't use a module like this in an Ionic app. Google is actively blocking that. use Ionic native google plus sign in instead: https://ionicframework.com/docs/native/google-plus/

**Comment by andy008** [comment]
I got it working fine in an Ionic PWA.

**Comment by jaibatrik** [comment]
Consider in #6.
