### ISSUE TITLE
Angular social login logo design

### ISSUE THREAD

**Issue by batarian71** [abacritt/angularx-social-login#86]
Hello! I contribute to open source software in my spare time. Do you want me to make a logo for hats?

It will be perfect for the readme file.

**Comment by jaibatrik** [comment]
Not sure about this. I don't think we need a logo. But you can send a PR if you want.

**Comment by batarian71** [comment]
https://github.com/abacritt/angularx-social-login/pull/103 

I hope you like it. I sent a pullrequest
