### ISSUE TITLE
FB login: picture size

### ISSUE THREAD

**Issue by venoby** [abacritt/angularx-social-login#87]
How I can get large size photo instead of 50x50 ?
and other users details?

**Comment by jaibatrik** [comment]
Once the user is authenticated, you can request to https://graph.facebook.com/<fb-user-id>/picture?type=large

Let me know if this does not work.

**Comment by jainnimish7** [comment]
I tried using this URL ( https://graph.facebook.com//picture?type=large) for large image. But getting this response. 
Any success for fetching large image?

```{
   "error": {
     "message": "(#12) picture edge for this type is deprecated for versions v2.3 and higher",
      "type": "OAuthException",
      "code": 12,
      "fbtrace_id": "C+mwBP0yjB2"
   }
}```
