### ISSUE TITLE
Not Logging out properly.

### ISSUE THREAD

**Issue by vijayphani** [abacritt/angularx-social-login#92]
My login and logout are on different components.  Every instance of authservice is different and that is not logging me out properly. Is there a destroy method that would destroy all instances of authservice?

**Comment by SergeMaikere** [comment]
Same as @vijayphani here, my logout is in another component and does not seem to work.

**Comment by jaibatrik** [comment]
Could you please build a small app that demonstrates the issue and share with us?

**Comment by cfalzone** [comment]
I have the same issue ... but haven't had time to make a sample app and all that.  I can share the basic idea of what I am doing with two components, a login component with the login button and profile component with a logout button.

Both Components subcribe to the authState:
```
  ngOnInit() {
    this.authService.authState.subscribe((user) => {
      this.user = user;
      // This part only in the login component to route to the profile component after login:
      if (user) {
        this.router.navigate(['/profile']);
      }
    });
  }
```

In the login component I have the login button that calls:
```
  login(): void {
    this.authService.signIn(GoogleLoginProvider.PROVIDER_ID);
  }
```

In the profile component I have the logout button that calls:
```
  logout() {
    this.authService.signOut();
    this.router.navigate(['/login']);
  }
```

However, when the logout button on the profile component routes to the login component the authState still says it is logged in, unless I Browser Refresh.

**Comment by bodinaren** [comment]
@vijayphani @SergeMaikere @cfalzone Where did you import the module? If you don't import only in the root module then you'll get multiple instances of the authService, which will give the result you get here.

**Comment by sirwesley** [comment]
For Faceboook logout, I did the following...

This invalidates my Facebook permissions and forces a page refresh.
The next time I try to login however, I must accept the FB permissions again.  
```
this.user = null;
this.loggedIn = false;
FB.api('/me/permissions', 'delete', function(response) {
            console.log(response); // true
        });
window.location.reload();
```

**Comment by cfalzone** [comment]
In my app.module.ts I import:
```
import { SocialLoginModule,
         AuthServiceConfig,
         GoogleLoginProvider }      from "angularx-social-login";
```

Then in each of my components I import:
```
import { AuthService, SocialUser } from 'angularx-social-login';
```
and my login/logout component I also import the provider.
```
import { AuthService, GoogleLoginProvider, SocialUser } from "angularx-social-login";
```

I don't see anywhere in my app where I import the Module again.

**Comment by jaibatrik** [comment]
@cfalzone Can you show the relevant constructor code of your component? Ideally the AuthService should be injected.

**Comment by cfalzone** [comment]
I put in the component like:
```
  constructor(
    private authService: AuthService,
    ...
  ) { }
```

**Comment by nguyentrunghieu3010** [comment]
```
signOut(): Promise<any> {
    return new Promise((resolve, reject) => {
      if (!this._user) {
        reject(AuthService.ERR_NOT_LOGGED_IN);
      } else {
        let providerId = this._user.provider;
        let providerObject = this.providers.get(providerId);
        if (providerObject) {
          providerObject.signOut().then(() => {
            // resolve();

            this._user = null;
            this._authState.next(null);
             resolve(); // Fixed
          }).catch((err) => {
            reject(err);
          });
        } else {
          reject(AuthService.ERR_LOGIN_PROVIDER_NOT_FOUND);
        }
      }
    });
  }

```

**Comment by jaibatrik** [comment]
I think this might be an issue with dependency injection. Try to provide the service in root module so that only one instance of the service is created.

**Comment by madu419** [comment]
to solve the issues i need to put singout inside timer  setTimeout(() => {
        this.socialAuthService.signOut()
      }, 1);
