### ISSUE TITLE
Angular 6 Support

### ISSUE THREAD

**Issue by MainaWycliffe** [abacritt/angularx-social-login#94]
Which version should i install for Angular 6?

**Comment by satsangswami** [comment]
`npm install --save angularx-social-login@latest`
installs only 1.1.8 which is incompatible with Angular 6

**Comment by MainaWycliffe** [comment]
@satsangswami  Yes, that's true. And i can see support for Angular 6 has been added on the repo, yet not published on npm.

**Comment by satsangswami** [comment]
is there a way to still update?

**Comment by MainaWycliffe** [comment]
Am not aware of one.

**Comment by MainaWycliffe** [comment]
On second thought, you could install directly from github repository: 

`npm install --save https://github.com/abacritt/angularx-social-login.git`

**Comment by DoruFurtuna** [comment]
We have same issue and installing it from github does not work. 
@MainaWycliffe maybe you can help with a hint of how to build it from github?

**Comment by satsangswami** [comment]
Any update on the issue please. @MainaWycliffe @jaibatrik the latest version is not published to npm

**Comment by MainaWycliffe** [comment]
@DoruFurtuna sorry, my mistake. I tried that and it did't work. @satsangswami it seems this library is no longer being supported or something. May be we should fork it and continue development as a community under a different name like ngx-social-login or something.

**Comment by jaibatrik** [comment]
Updated and pushed to npm. Kindly check if this works or some issue is present.

**Comment by chatpack** [comment]
<code>
npm install --save-dev angular6-social-login

npm ERR! 404 Not Found: angular6-social-login@latest
</code>
... still got the blues ...
