### ISSUE TITLE
LinkedIn Login not working when I am integrating it with my application.

### ISSUE THREAD

**Issue by devotebest** [abacritt/angularx-social-login#97]
![39240803-7a231ae6-48a2-11e8-8ece-5d7a14de7ead](https://user-images.githubusercontent.com/10233895/41082727-39fe7430-6a6a-11e8-81ee-a7989e83a6d8.png)

This is the error I am getting when I am integrating the social login for linkedin.
Kindly help me on this.

**Comment by isaleem** [comment]
In your LinkedIn app, Application Settings->JavaScript section you need to add the domain http://localhost:4200/ for it to work.
![screen shot](https://user-images.githubusercontent.com/871058/41186357-655180a6-6bae-11e8-9473-8b28a1f24434.png)

**Comment by jaibatrik** [comment]
Did the suggestion fix the issue?

**Comment by danim-hub** [comment]
I am having the same issue.  It ocurrs on linkedin-login-provider.ts, in line 54:

    IN.API.Raw(`/people/~:(${this.fields})`).result(function (res: any) {

apparently there is a problem with the "this" scope, so I used two intermediate variables _this1 and _thsi2 for fixing it on my node_modules/angularx-social-login  folder.

Could you please include this change on the next release? Currently my linkedin needs this fix to work, if I do npm update I'll lose this change.

```
function () {
        var _this1 = this;  // ** HERE ** //
        return new Promise(function (resolve, reject) {
            _this.onReady().then(function () {
                var _this2 = _this1;  // ** AND HERE ** //
                IN.User.authorize(function () {
                    IN.API.Raw("/people/~:(" + _this2.fields + ")").result(function (res) {
                        var /** @type {?} */ user = new SocialUser();

```

**Comment by bodinaren** [comment]
The fix will be the same as in #117, use fat arrow functions instead of regular functions.

**Comment by jaibatrik** [comment]
#117 is merged.

**Comment by bodinaren** [comment]
Sorry, it seems I was a bit unclear. The fix needs to be the same as in #117, but it's **NOT** done for the `LinkedInLoginProvider`. There are three places where fat arrow functions are not used. Fixing those will fix this issue. Anyone feel free to submit a PR to this effect.

**Comment by piyush-ampersand** [comment]
@bodinaren  Hey thank you for the clarification. Can you tell me how to do it as I have not done that before but seems I just need to use the arrow functions in those places if its not much to ask.
Thanks.

**Comment by bodinaren** [comment]
@piyush-ampersand Just look at the changes in #117 and do the same fix for all 4 places (I just saw it was 4, not 3 as previous stated) in the linked in login provider.

https://github.com/abacritt/angularx-social-login/blob/master/src/lib/src/providers/linkedIn-login-provider.ts#L44
https://github.com/abacritt/angularx-social-login/blob/master/src/lib/src/providers/linkedIn-login-provider.ts#L65
https://github.com/abacritt/angularx-social-login/blob/master/src/lib/src/providers/linkedIn-login-provider.ts#L66
https://github.com/abacritt/angularx-social-login/blob/master/src/lib/src/providers/linkedIn-login-provider.ts#L88

E.g. `function (res: any)` becomes `(res: any) =>`
and `function ()` becomes `() =>`

Fix those lines and then submit a PR.

**Comment by piyush-ampersand** [comment]
@bodinaren and @jaibatrik I have generated the PR can anyone verify and publish it on the npm

**Comment by bodinaren** [comment]
This looks good to me. @jaibatrik has to merge and publish though.

**Comment by piyush-ampersand** [comment]
@jaibatrik If possible can you do it by the end of this week as I need to give a demo. If this is not much to ask. TIA.
@jaibatrik This was my first fork and PR, learnt thanks to you. Cheers !!

**Comment by jaibatrik** [comment]
Just merged and published to npm. Thanks all!

**Comment by jaibatrik** [comment]
Related PR #152

**Comment by shakalya195** [comment]
Below is a working code for ANGULAR 6.
Put below in index.html
```
<script type="text/javascript" src="//platform.linkedin.com/in.js">
  api_key: "APPID"
  authorize: true
</script>
```
Put this in any service. and hit linkedinlogin() from any login component. See the console.

```
  linkedinlogin() {
   /* bind auth event with getLinkedinUserData */
    IN.Event.on(IN, "auth", r=>{
      this.getLinkedinUserData();
    });


    if(!IN.User.isAuthorized()){
   /* if not authorised */
      console.log('NOT AUTHORISED');
      /* make authentication */
      IN.User.authorize(r=>{
        console.log('IN');
        this.linkedinlogin();
      },error=>{
        console.log('OUT',error);
      });
    }else{
   /* if authorised */
      this.getLinkedinUserData()
    }
  }

  getLinkedinUserData(){
    IN.API.Raw("/people/~:(first-name,last-name,email-address,headline,picture-url)").result(r=>{
      console.log(r);
    }).error(error=>{
    });
  }
```

**Comment by webkhushboo** [comment]
> Below is a working code for ANGULAR 6.
> Put below in index.html
> 
> ```
> <script type="text/javascript" src="//platform.linkedin.com/in.js">
>   api_key: "APPID"
>   authorize: true
> </script>
> ```
> 
> Put this in any service. and hit linkedinlogin() from any login component. See the console.
> 
> ```
>   linkedinlogin() {
>    /* bind auth event with getLinkedinUserData */
>     IN.Event.on(IN, "auth", r=>{
>       this.getLinkedinUserData();
>     });
> 
> 
>     if(!IN.User.isAuthorized()){
>    /* if not authorised */
>       console.log('NOT AUTHORISED');
>       /* make authentication */
>       IN.User.authorize(r=>{
>         console.log('IN');
>         this.linkedinlogin();
>       },error=>{
>         console.log('OUT',error);
>       });
>     }else{
>    /* if authorised */
>       this.getLinkedinUserData()
>     }
>   }
> 
>   getLinkedinUserData(){
>     IN.API.Raw("/people/~:(first-name,last-name,email-address,headline,picture-url)").result(r=>{
>       console.log(r);
>     }).error(error=>{
>     });
>   }
> ```

I tried using it , Its not working for me . Its giving error Cannot read property 'then' of undefined
    at Object.authorize (in.js:18)

**Comment by sajjadjutt4u** [comment]
It's giving me Error on IN. Cannot find name IN TS2304

**Comment by sajjadjutt4u** [comment]
@shakalya195 Please help me in this regard

**Comment by sajjadjutt4u** [comment]
![image](https://user-images.githubusercontent.com/43935954/82329876-6ba46b80-99fb-11ea-9114-265e8b5c799f.png)


facing this error. because IN is not defined @shakalya195  @webkhushboo

**Comment by jaibatrik** [comment]
LinkedIn login is not supported any more.

**Comment by sajjadjutt4u** [comment]
Another way to integrate LinkedIn login?
